### ISSUE TITLE
Implement Iron Bank images for all baseline images

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#10]
Most IB images currently are either missing or the version is missing that we need. Additionally, some nearly all of the IB images are baselined off of UBI when they could easily run on a distroless IB baseline instead and cut the overall size significantly.

---

Migrated from https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/16

**Comment by RothAndrew** [comment]
What opportunity is there to chunk something out that is easy to deliver on in the short term? Big Bang's OPA policies don't like the containers that make up the utility cluster and the k8s control plane. I can add DockerHub as an allowed host but that eliminates the value of the OPA policies (and the people I'm demoing to won't like seeing that)

**Comment by RothAndrew** [comment]
Closing in favor of individual tickets that have a better chance of making it across the finish line.

/cc @runyontr @jeff-mccoy

**Comment by RothAndrew** [comment]
* #213 
* #214 
* #215

**Comment by ntwkninja** [comment]
@Racer159 @eddiezane @jeff-mccoy are there any plans for the project to maintain a zarf init package w/IB images?

**Comment by Racer159** [comment]
Likely not - if you'd like an IB init package we'd recommend: https://github.com/radiusmethod/zarf-init-bigbang or using that as a template.  The base init package is pretty flexible as is
