### ISSUE TITLE
Each E2E test should be runnable locally

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#100]
The E2E tests use Terratest to spin up EC2 instances in AWS so that we can parallelize them and make them ephemeral. We want the ability to run the same tests locally, possibly using Vagrant.

- Each Terratest-based E2E test should have a local variant
- Code should be shared as much as possible. One idea that has been floated is to abstract the test logic into a Makefile that both sides use

**Comment by RothAndrew** [comment]
This issue needs to be reworked due to the changes in #237 

@jeff-mccoy Can you brain-dump your thoughts here on what you want to be able to do?

**Comment by RothAndrew** [comment]
Blocked by #265

**Comment by jeff-mccoy** [comment]
Closed by #319
