### ISSUE TITLE
Unexpected behavior for manifests containing helm template strings

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/zarf#1008]
### Overview
My zarf package definition has [a component which references a kustomization file](https://github.com/naps-dev/dco-foundation/blob/98e9ceb064f93356137b51a91c25f39ef9716511/zarf.yaml#L78-L84). In turn, the kustomization [generates a configmap](https://github.com/naps-dev/dco-foundation/blob/98e9ceb064f93356137b51a91c25f39ef9716511/kustomizations/bigbang/kustomization.yaml#L4-L9) from a [values.yaml](https://github.com/naps-dev/dco-foundation/blob/98e9ceb064f93356137b51a91c25f39ef9716511/kustomizations/bigbang/values.yaml) file to be consumed in the cluster by a flux helm release. 

In the `values.yaml`, some of the fields are [helm template strings](https://github.com/naps-dev/dco-foundation/blob/98e9ceb064f93356137b51a91c25f39ef9716511/kustomizations/bigbang/values.yaml#L36) which are evaluated by the upstream (flux managed) chart.

### Expected Behavior
A `kustomize build` of the local files results in the following data in the configmap:
```
istio:
  gateways:
    public:
      hosts:
        - "*.{{ .Values.domain }}"
```
This is what I expect to be applied to the cluster by a zarf package/deploy.

### Observed Behavior
Instead, it appears that internally, either at the package or deploy step, zarf is attempting to render my `values.yaml` file as a template on its own and the expected template strings are effectively removed, resulting in the following configmap data:
```
istio:
  gateways:
    public:
      hosts:
        - "*."
```

### Temporary Resolution
I intend to work around this for now by using either a local chart, or a flux kustomization in order to abstract my `values.yaml` file from Zarf itself. Alternatively, I may use zarf variable substitution to "hard code" the desired template strings with the dynamic domain value. That would resolve the current behavior, but may not be sufficiently flexible later. 
  
### Desired Change
To be honest, I'm not sure if anything here is "broken", but the behavior was unexpected enough and difficult enough to root-cause that it felt it merited opening a discussion...

At the very least there may be an opportunity for adding clarity (or warnings) in the docs. I'm not sure if we have a "frequently encountered issues" log, or suggested common use patterns (outside of the examples), but maybe something like that would be appropriate.

**Comment by Racer159** [comment]
Resolved by https://github.com/defenseunicorns/zarf/pull/1350
