### ISSUE TITLE
Migrate a non-Zarf controlled cluster to Zarf

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/zarf#1054]
**Is your feature request related to a problem? Please describe.**
I have workloads running on a cluster that were not created using Zarf, but I'd like to migrate them to be controlled by Zarf.

**Describe the solution you'd like**
A clear path for migrating non-Zarf workloads to Zarf. I have a Zarf package that mirrors what is currently deployed, how do I deploy this package such that it tags existing workloads and doesn't throw an error

**Comment by UncleGedd** [comment]
YOLO mode effectively does this for me

**Comment by UncleGedd** [comment]
I lied...YOLO didn't solve this issue. Here's what happens:
1. I have a cluster containing resources not created by Zarf
2. I have a Zarf package that will deploy/upgrade those resources already in the cluster
3. I run `zarf package deploy ...`
4. WOMP. Because the resources in the cluster weren't deployed as part of a Helm chart, and Zarf expects it's resources to have Helm annotations

Example error from logs:

> ```DEBUG   2023-02-26T17:48:29-06:00  -  rendered manifests contain a resource that already exists. Unable to continue with install: GitRepository "zarf-playground" in namespace "zarf-playground" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "zarf-4b149ec8f25712385e4d8d5eb2817223da01443a"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "podinfo" └ (/home/runner/work/zarf/zarf/src/pkg/message/spinner.go:136) ```

**Comment by Racer159** [comment]
As discussed in another thread this could take the form of a `--import-existing` flag on zarf deploy so as to not interrupt the Zarf lifecycle too much.
