### ISSUE TITLE
Configurable `init` package

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1062]
**Is your feature request related to a problem? Please describe.**
Would like to be able to configure the following within an init package:

- Traafik in k3s
- Gitea/logging resource limits
- Existing Agent Image/Injector Tag
- Container images used

**Describe the solution you'd like**
Ideally this would use a zarf-config.toml to provide the configuration so that it just works with zarf package create (no Makefile knowledge needed)

**Describe alternatives you've considered**
This could go into the Makefile but editing that would be more obtuse (most likely) for other people.

**Additional context**
This would be useful if you wanted to make a slightly tweaked init package for your organization (i.e. using Iron Bank images) without needing deeper knowledge of Zarf.

**Comment by lucasrod16** [comment]
This is relevant to some work I've been doing with zarf. I'd like to be able to pass in the `--tls-san` arg to k3s with zarf so that a zarf-created k3s cluster can be accessed remotely

If this is outside the desired scope of this issue, I'm glad to open a new issue relating to this

**Comment by Racer159** [comment]
@lucasrod16 if you can open an issue and link back to here that would be great!  I think this issue will spawn a few different ones (I linked two new ones above).  In your case could you use the configuration file as well? https://docs.k3s.io/installation/configuration#configuration-file

**Comment by lucasrod16** [comment]
@Racer159 Yes I will open a new issue and link back here. The k3s configuration file seems like a good option for this use-case. I'll give that a shot. The alternative method we are using is to setup a k3d cluster and registry on the host, but having some problems with getting registry mirroring to work properly. Having zarf set this up for us would be great

**Comment by Racer159** [comment]
Closing as completed (we even have a tutorial: https://docs.zarf.dev/docs/zarf-tutorials/custom-init-packages)
