### ISSUE TITLE
Create Zarf Ecosystem Webpage using landscape Tool

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1068]
Look into Landscape App for building an ecosystem map similar to 
CNCF - https://github.com/cncf/landscape
Open SSF - https://landscape.openssf.org/sigstore

<img width="1787" alt="Screen Shot 2022-12-02 at 11 06 26 AM" src="https://user-images.githubusercontent.com/92826525/205346641-843382d2-4bf2-4444-8800-9dbb3aa63948.png">

- [ ]  Display an infographic that shows all of the tools/apps Zarf works with
- [ ] Organize by category
- [ ] Simple flow for external contributors to add project to map (ex. CNCF)
- [ ] Team only has to review request once set up
- [ ] Set up netlify preview (ask @mike-winberry)
- [ ] Create blog announcement (ex. https://blog.sigstore.dev/new-sigstore-landscape-add-your-signed-project-dda0517723b6)
- [ ] Work with @Madeline-UX to usability test filters and information architecture

**Comment by Racer159** [comment]
Relates to https://github.com/defenseunicorns/zarf/issues/1042
