### ISSUE TITLE
Repository cache gets invalidated after several builds

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#1079]
Related to #1069 

When rebuilding a package, zarf will attempt to use repositories that already exist in the `~/.zarf-cache/repos` directory. When testing the fix for another (relatively similar issue) I realized that rebuilding the same package multiple times (3+ times) will result in a failure because the HEAD of the repository in the cache directory ends up picking up changes from `online-upstream` somehow.

### Steps to Replicate
> Running from the root of the Zarf repo

```
# make sure the cache is clear
zarf tools clear-cache


# Build all the things!
zarf package create examples/git-data/ --confirm       # This will result with the git repositories being added to the cache
zarf package create examples/git-data/ --confirm       # This will result with the cached repositories having unstaged changes
zarf package create examples/git-data/ --confirm       # This will result in a creation failure
```

<img width="1241" alt="Screen Shot 2022-12-04 at 6 09 15 PM" src="https://user-images.githubusercontent.com/18587823/205521235-a77fa44a-1540-4956-be2a-4223a2803c7f.png">

**Comment by runyontr** [comment]
Looking forward to this fix
