### ISSUE TITLE
Zarf init fails on OpenShift

### ISSUE THREAD

**Issue by djcass44** [defenseunicorns/zarf#1081]
### Environment
Device and OS: N/A
App version: `v0.22.2`
Kubernetes distro being used: K3S on OpenShift (using VCluster)
Other:

### Steps to reproduce
1. Run `zarf init` on an OpenShift cluster without `cluster-admin` or any special `SecurityContextConstraint` (i.e. using only the default `restricted` SCC)
2. Notice that the Registry fails to schedule
3. Notice that the agent goes into `CrashLoopBackoff`

### Expected result

1. Registry and Agent should be able to start without requiring excessive privileges

### Actual Result

1. Registry sets a SecurityContext value that is not supported on OpenShift
2. Agent does not appropriately configure ephemeral storage and crashes

### Visual Proof (screenshots, videos, text, etc)

1. Can't be easily provided as the OpenShift cluster in question is disconnected.

### Additional Context

I'm running VCluster on OpenShift (https://www.vcluster.com/) to avoid needing to give Zarf cluster-level privileges. The issues I'm running into are not related to Cluster admin and are more to do with how the underlying pods are created.

## Possible solutions

All of these issues can be easily fixed by a few changes to the `init` package. I'd be happy to open an MR if you'd like.

### Agent

* Mount `emptyDir` [volumes](https://github.com/defenseunicorns/zarf/blob/main/packages/zarf-agent/manifests/deployment.yaml#L47) to `/.config` and `/etc/xdg`. This fixes the crashlooping.

```diff
          volumeMounts:
            - name: tls-certs
              mountPath: /etc/certs
              readOnly: true
            - name: zarf-state
              mountPath: /etc/zarf-state
              readOnly: true
+           - name: config
+             mountPath: /.config
+           - name: xdg
+             mountPath: /etc/xdg
      volumes:
        - name: tls-certs
          secret:
            secretName: agent-hook-tls
        - name: zarf-state
          secret:
            secretName: zarf-state
+       - name: config
+         emptyDir: {}
+       - name: xdg
+         emptyDir: {}
```

### Registry

* Set `securityContext.enabled: false` in the Registry `values.yaml` (for both the seed and standard registry) so that OpenShift allows the pod to run. 
* Perhaps a followup could be adding a `--openshift` flag to `zarf init`

**Comment by jeff-mccoy** [comment]
these are reasonable changes and good finds.  I believe `/etc/xdg` comes from our [k9s](https://github.com/derailed/k9s) vendoring, not super sure where `/.config` is coming from off the top of my head.  I'm working on a larger refactor of the registry package in #1039 and will try these changes out there.

**Comment by jeff-mccoy** [comment]
Was going to add these changes to that PR but it got a bit bigger, so recommend a separate PR now for this. I just to make sure we understand the changes fully and that they won't cause us headaches on other distros--but don't think that will be the case.
