### ISSUE TITLE
prepare find-images doesn't work on local helm chart paths

### ISSUE THREAD

**Issue by joelcomp1** [defenseunicorns/zarf#1087]
### Environment
Device and OS: Laptop Ubuntu 22.04
App version:  v0.22.2
Kubernetes distro being used: RKE2 1.24.8
Other:

### Steps to reproduce
1.  git clone https://github.com/rancher/charts.git
2.   Create a zarf.yaml file with the below content:

`
kind: ZarfPackageConfig
metadata:
  name: test
  description: "Deploys a helm chart from local files"
components:
  - name: demo-helm-local-chart
    required: false
    charts:
      - name: rancher-monitoring
        #gitPath: charts/rancher-monitoring/101.1.0+up40.1.2
        localPath: charts/charts/rancher-monitoring/101.1.0+up40.1.2
        namespace: rancher-monitoring
        version: 101.1.0+up40.1.2
`

Fails with: ERROR:  Unable to pull the helm chart

### Expected result
Output images in the helm chart

### Actual Result

Saving log file to /tmp/zarf-2022-12-05-08-07-30-4154958969.log
  DEBUG   2022-12-05T08:07:30-05:00  -  k8s.generateLogShim()
└ (/home/runner/work/zarf/zarf/src/internal/k8s/common.go:157)
  DEBUG   2022-12-05T08:07:30-05:00  -  Log level set to info
└ (/home/runner/work/zarf/zarf/src/cmd/root.go:87)
  DEBUG   2022-12-05T08:07:30-05:00  -  Loading zarf config zarf.yaml
└ (/home/runner/work/zarf/zarf/src/config/config.go:236)
  DEBUG   2022-12-05T08:07:30-05:00  -  config.isCompatibleComponent(demo-helm-local-chart, false)
└ (/home/runner/work/zarf/zarf/src/config/config.go:243)
  DEBUG   2022-12-05T08:07:30-05:00  -  packager.ComposeComponents()
└ (/home/runner/work/zarf/zarf/src/internal/packager/prepare.go:42)
  DEBUG   2022-12-05T08:07:30-05:00  -  Using temp path: '/tmp/zarf-3369520469'
└ (/home/runner/work/zarf/zarf/src/internal/packager/common.go:46)
  DEBUG   2022-12-05T08:07:30-05:00  -  could not find protocol handler for:                                                                                                                                       
└ (/home/runner/work/zarf/zarf/src/internal/message/spinner.go:116)
     ERROR:  Unable to pull the helm chart

### Additional Context

I assume the find images should work with local paths?  It doesnt seem to work with Git URL's either (unless I have syntax wrong) but seems to work fine with a actual helm repo link.

**Comment by Racer159** [comment]
@joelcomp1 thanks for the bug report! I created #1111 to address the local paths issue.  `gitPath`s should still work, but do work a little differently in that you need to use both `url` and `gitPath` where `url` is the `url` of the base git repository and `gitPath` is the path _within_ that repository. (here is an example: https://github.com/defenseunicorns/baffles-matlab-demo/blob/f5006be3b7a7d07dd98ae93382de98e69e28db76/zarf.yaml)

We do have some docs improvements that are coming that will explain that better on the Zarf schema page in our docs but those are pending our next release.

**Comment by joelcomp1** [comment]
Awesome thanks that does help.  Appreciate the quick fix as well.
