### ISSUE TITLE
Add ability to make Zarf quieter

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#109]
I'd like the ability to do something like `zarf --quiet` that will suppress the big Zarf ascii image, so that if I'm logging output from Zarf it doesn't clutter my logs with extra fluff.

**Comment by btlghrants** [comment]
Might something like `zarf --no-banner` be more fitting?

I can imagine a distinction between wanting **no output at all** (sort of like `grep --quiet`) and just not wanting the art.  A `zarf --quiet` command makes me (at least) imagine something more like that first case.

**Comment by RothAndrew** [comment]
![the-road-to-el-dorado-both](https://user-images.githubusercontent.com/16000938/137811510-c3854f82-b8a6-481a-8e23-201592b786f3.gif)

**Comment by jeff-mccoy** [comment]
Talking with @Madeline-UX today about this and there does seem to be a good use-case for only showing top-level status and not the details, especially for newer users.  Also would like to shamelessly steal what https://github.com/anchore/syft is doing with their cool CLI progress stuff for that.

**Comment by wadedesir** [comment]
@jeff-mccoy @YrrepNoj will #237 close this issue or does it still need to be addressed?

**Comment by Madeline-UX** [comment]
@jeff-mccoy This still needs to be addressed - I will be working toward this once I switch over to the team full time.

**Comment by jeff-mccoy** [comment]
Actually this issue should be closed. #237 only shows the zarf header on help or init, pipes all non-output logs to stderr for piping and only does top-level summaries of actions in favor of progress bars and spinners instead.
