### ISSUE TITLE
Simplify Deploying Big bang

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1093]
**Is your feature request related to a problem? Please describe.**
Deploying BigBang is hard, and specifying what's needed for BigBang is hard.

**Describe the solution you'd like**
A new component for BigBang usable in the Zarf.yaml

**Comment by Madeline-UX** [comment]
Will these components require any additional functionality to the Zarf binary or file type?

**Comment by runyontr** [comment]
This change, as currently proposed in #1094 , would change the Zarf.yaml schema as described here:

https://github.com/defenseunicorns/zarf/pull/1094/files#diff-af9aa00008a4dd143fdf7c1ad56f79f475692881f1d92e4c875b8dd2d318298b


Zarf and the workflow would work the same, but be able to consume a new type of component definition

**Comment by Racer159** [comment]
This is completed by #1094
