### ISSUE TITLE
zstd requirement

### ISSUE THREAD

**Issue by rushyrush** [defenseunicorns/zarf#1115]
### Environment
Device and OS: CIS Red Hat Enterprise Linux 7 STIG Benchmark
App version: v0.22.2
Kubernetes distro being used: zarf included k3s
Other:

### Steps to reproduce
1. `zarf init`

### Expected result
zarf initializes

### Actual Result
`     ERROR:  Unable to extract the package contents`

### Severity/Priority
low

### Additional Context
No extraction issues if zstd is installed.
I consider this to be a unique edge case when working with redhat in an airgap environment where zstd is not installed by default.  I also did not see a zstd dependency in the docs.

**Comment by jeff-mccoy** [comment]
There must be something deeper going on, zstd is not a requirement as we use a native go implementation of zstd. Do you have debug logs for the error you received?

**Comment by rushyrush** [comment]
log is very tiny
```
  DEBUG   2022-12-12T22:09:46Z  -  k8s.generateLogShim()
└ (/home/runner/work/zarf/zarf/src/internal/k8s/common.go:157)
  DEBUG   2022-12-12T22:09:46Z  -  Log level set to info
└ (/home/runner/work/zarf/zarf/src/cmd/root.go:87)
  DEBUG   2022-12-12T22:09:46Z  -  packager.Deploy()
└ (/home/runner/work/zarf/zarf/src/internal/packager/deploy.go:34)
  DEBUG   2022-12-12T22:09:46Z  -  Using temp path: '/tmp/zarf-1086457438'
└ (/home/runner/work/zarf/zarf/src/internal/packager/common.go:46)
```

**Comment by rushyrush** [comment]
Ignore my ignorance. This bug is purely user error presenting itself in pipelines due to different size nodes.  on small test nodes its was failing due to memory constraints limiting `/tmp` causing  the extraction to fail. Increasing node size fixed the issue. installing zstd was completely unrelated.

**Comment by lucasrod16** [comment]
Was working with @rushyrush on this, and assumed the same thing about `zstd`. The error led me to believe that the `archiver` library depended on shelling out to the `zstd` binary. After installing, it worked, but now know that was likely because of the node size being different than before. Good to know that increasing node size is the fix
