### ISSUE TITLE
Use variables for Gitea's values

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1122]
**Is your feature request related to a problem? Please describe.**
Gitea's configuration values are still hard coded

**Describe the solution you'd like**
Gitea's configuration values use variables

**Describe alternatives you've considered**
none

**Additional context**
https://github.com/defenseunicorns/zarf/pull/1117

**Comment by RothAndrew** [comment]
I recommend making the default value for cpu limit some arbitrarily large number, like "10". [CPU limits tend to constrain resources when they don't need to be constrained](https://home.robusta.dev/blog/stop-using-cpu-limits).

**Comment by RothAndrew** [comment]
Screenshot demonstrating Gitea being throttled during a large zarf package deployment even though there was more than enough CPU to go around on the node.

![image](https://user-images.githubusercontent.com/16000938/207657093-51d7f5cd-2002-473f-be77-e462965ed26d.png)

**Comment by YrrepNoj** [comment]
I know you said you picked a random arbitrarily large number as a recommendation. I would suggest we use the same default value we use for the container registry, which in this case [is 3](https://github.com/defenseunicorns/zarf/blob/3de6e411b7098f083a57fdee2c6d59230a8afcf9/packages/zarf-registry/zarf.yaml#L25).

**Comment by Racer159** [comment]
I agree with Jeff's comments on the Variablization of the gitea values, it would be (relatively) trivial to make that happen.

**Comment by RothAndrew** [comment]
Jeff's comment for context: https://github.com/defenseunicorns/zarf/pull/1117#pullrequestreview-1216941666

> I think we should follow the [pattern of the registry now](https://github.com/defenseunicorns/zarf/blob/main/packages/zarf-registry/zarf.yaml?rgh-link-date=2022-12-14T07%3A52%3A48Z#L15) and use variables to give users control of this rather than making an arbitrary very high CPU limit.
