### ISSUE TITLE
Set up CODEOWNERS

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#113]
As a maintainer of Zarf I'd like a CODEOWNERS configuration so that GitHub can automatically decide who should be an approver of a change. 

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-code-owners

**Comment by RothAndrew** [comment]
Proposed solution:

1. Create a couple of GH teams that represent different engineering practices in the codebase. My initial thoughts are one for the zarf golang code and another for the automation stuff, but I think there's a bunch of different ways this can go
2. Create the CODEOWNERS file that assigns the new teams as codeowners for different parts of the codebase
3. Update the branch protection rule from "require one review" to "require one review from a codeowner"

**Comment by JasonvanBrackel** [comment]
Proposing that @YrrepNoj, @Racer159, @jeff-mccoy, and @JasonvanBrackel be added as global code owners.  Also suggest that @Madeline-UX additioally be made a code owner over anything doc related.

Who am I missing

**Comment by YrrepNoj** [comment]
@mike-winberry mostly has worked on docs/website stuff but has picked up a ticket or two for the main repo so he would be good to add.


@RothAndrew Has been focusing on package development but often has lots of good contributions and should be a code owner too

**Comment by Madeline-UX** [comment]
@JasonvanBrackel  With the addition of the Zarf UI would i need to be a code owner in order to review PR related to that work?

**Comment by JasonvanBrackel** [comment]
@Madeline-UX That makes sense to me.
