### ISSUE TITLE
Ability to pass TLS SAN option to k3s component in init package

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns/zarf#1130]
**Is your feature request related to a problem? Please describe.**
Would like to be able to configure TLS SAN options for k3s with zarf so that a zarf-created k3s cluster can be accessed remotely

**Describe the solution you'd like**
Use a zarf package variable to pass the `--tls-san` option to k3s, or use a flag like `zarf init --tls-san=<hostname>`

**Describe alternatives you've considered**
- Use a [k3s config file](https://docs.k3s.io/installation/configuration#configuration-file) to configure tls-san
- Use k3d instead. Would like to not have to because setting up the local registry and docker networks is not as simple as `zarf init`

**Additional context**
This would be useful for creating k3s clusters with zarf that can be accessed remotely (see https://github.com/defenseunicorns/zarf/issues/1062)

**Comment by Racer159** [comment]
Fixed in https://github.com/defenseunicorns/zarf/pull/1171

**Comment by Racer159** [comment]
@lucasrod16 we can reopen if that does not work
