### ISSUE TITLE
Expand the FAQs!!!

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#1134]
Open issue to add more FAQs, anyone can comment to add a new question we should include in the [Doc FAQs](https://docs.zarf.dev/docs/faq)

- [ ] Is Zarf approved for use on Government Systems?
- [ ] Is Zarf only for Airgap Systems?
- [ ] Does Zarf have a plugin System?
- [ ] What license does Zarf use?

**Comment by sdkreimier** [comment]
One person asked, "Is Zarf approved for use on Government Systems?"
