### ISSUE TITLE
Add generic key:value store into Zarf

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/zarf#1142]
As a package developer, I want Zarf to remember variable values from a `zarf package deploy` and make them available to future `zarf package deploy` actions so that engineers do not need to specify variables on subsequent deploys.

As a package developer, I want Zarf to remember component outputs from a `zarf package deploy` and make them available to future `zarf package deploy` actions so that components can share information with future components in a single Zarf package or between Zarf packages.

---

Incorporating a key:value store in Zarf can satisfy both user stories above. During a `zarf package deploy`, a golang `map[string]string` is instantiated and Zarf attempts to populate it from a Kubernetes secret. If the secret does not exist, the map remains empty. While the Zarf package deployment workflow is executed, variables and their values are stored in the map. Optionally, components can publish additional values to the map and also consume values from the map using the standard `###ZARF_PKG_VAR...###` nomenclature. When the Zarf deployment workflow is coming to an end, the contents of the map are written to a Kubernetes secret.

**Comment by jeff-mccoy** [comment]
Part of the idea around config files was the ability to re-run the variables consistently without managing command flags. Curious how that plays into this idea.
