### ISSUE TITLE
Deprecated binary alerts for package create

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1157]
HMW inform/warn the user during the package creation process that their package contains information (ex. scripts) that is no longer supported by the updated Zarf binary. 

Questions: 
where in the flow should this be?
Should it be in the log or a prompt?
What should the message say?

**Comment by Racer159** [comment]
Closing as completed with https://github.com/defenseunicorns/zarf/issues/1722 resolving placement
