### ISSUE TITLE
Have separate examples for create-time variables and deploy-time variables

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1165]
**Is your feature request related to a problem? Please describe.**
I was trying to give a tutorial on deploy-time variables and tried to use the package-variables example in this repo to do it, but it was confusing to the person I was giving the tutorial to because I had to use create-time variables at the same time (i.e. `zarf package create --set ACTION=template --set CONFIG_MAP=simple-configmap.yaml`) because of the way the example is set up.

**Describe the solution you'd like**

2 examples exist:

* One that only uses create-time variables
* One that only uses deploy-time variables

**Comment by Racer159** [comment]
I believe this will be addressed by https://github.com/defenseunicorns/zarf/pull/1474
