### ISSUE TITLE
Documentation in the examples folder is hard to read in GitHub

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1166]
**Is your feature request related to a problem? Please describe.**
The markdown documentation that lives in the examples folder has special characters that the docs website understands, but GitHub markdown does not. If one is trying to read docs in GitHub or in their IDE it is much harder to read

**Describe the solution you'd like**

Not sure what the best solution would be here. 2 possibilities I see are either having separate locations for the Docusaurus "code" that the docs website is generated from, or the addition of a note on each markdown page that links to the corresponding page on docs.zarf.dev.

![image](https://user-images.githubusercontent.com/16000938/211070646-20388e6f-3103-4920-90aa-278c5cee105f.png)

**Comment by Madeline-UX** [comment]
Feedback moved to issue #1168
