### ISSUE TITLE
No longer able to `zarf package deploy` an init package

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1182]
### Environment
Device and OS: Ubuntu EC2 instance
App version: v0.23.2
Kubernetes distro being used: built-in k3s
Other:

### Steps to reproduce
1. Download the init package that matches the version of zarf, rename it to something else like `init.tar.zst`
2. Run `./zarf package deploy init.tar.zst --components k3s --confirm`
3. Zarf will error, giving the following error:

<img width="1548" alt="image" src="https://user-images.githubusercontent.com/16000938/211432472-e8831345-36f9-486a-a173-b2ae653b8a40.png">

### Expected result

Zarf deploys the init package, in the same way that running `zarf init` would have. This worked in previous versions of Zarf (the version I'm upgrading from is v0.21.3.

Suggestion: Read the zarf.yaml of the package and interrogate its `kind:` rather than relying on the filename.

### Actual Result

The above error

### Severity/Priority

Functionality that worked previously is broken, but it's not the end of the world for me to upgrade my automation. It may be a bigger issue for people that create custom init packages though.

### Additional Context

* This behavior is useful because without it, automation processes will need to have a greater understanding of what version of Zarf is being used. I was previously able to have a makefile target `make build/zarf-init-amd64.tar.zst`, which is great, because Make will automatically detect when the file is present or not, or old, and skip running that download when it doesn't need to.
* It was also useful if a user was creating a custom init package.

Log showing zarf thinks it isn't an init package because of the filename:
<img width="675" alt="Screen Shot 2023-01-09 at 4 04 59 PM" src="https://user-images.githubusercontent.com/16000938/211432511-ca42f664-048b-43b1-a5b7-b8d571e01ff6.png">

**Comment by Racer159** [comment]
This is not due to the filename, looks like Init/Deploy options got split here so it is due to the use of the --components flag (Zarf has two copies of this internally split across deploy/init).  Pushing a PR fix for this now.
