### ISSUE TITLE
Helm chart error when installing zarf registry during init

### ISSUE THREAD

**Issue by Boojapho** [defenseunicorns/zarf#1185]
### Environment
Device and OS: Ubuntu 22.04.1
App version: v0.23.3
Kubernetes distro being used: K3D v1.24.8+k3s1
Other:

### Steps to reproduce
1. Start k3d cluster
2. zarf init
   a. Download init package - Y
   b. Deploy Zarf package - Y
   c. Deploy k3s component - N
   d. Deploy logging component - N
   e. Deploy git-server component - Y

### Expected result

Successful init of cluster

### Actual Result

Error deploying Zarf registry component: Helm chart failure

### Visual Proof (screenshots, videos, text, etc)

![image](https://user-images.githubusercontent.com/9620318/211651656-a764201f-ab97-4a80-8456-299550fa9ccb.png)

**Comment by jeff-mccoy** [comment]
We're in the processing of making error messages more useful, because this obviously isn't enough to hep you see what's really happening. Zarf be default creates log files with debugging, could you provide that or run the init with `-l=trace` ?

**Comment by Racer159** [comment]
@Boojapho just following up on this if you had more info from the log file.

**Comment by Racer159** [comment]
Closing as stale.  @Boojapho let us know if you were able to get more info and we can reopen
