### ISSUE TITLE
Make it easier to view contents of registry

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1186]
**Is your feature request related to a problem? Please describe.**
It is difficult to view the contents of the zarf docker registry.

**Describe the solution you'd like**
`zarf tools registry catalog` displays the contents of the registry with no other configuration or actions needed

**Describe alternatives you've considered**
I think this is what needs to happen?

* `zarf connect <the registry>`
* then `zarf tools registry login <the registry>`
* then `zarf tools registry catalog`

**Additional context**
<img width="1498" alt="image (3)" src="https://user-images.githubusercontent.com/16000938/211691168-5b416d9c-7df8-4c5f-98b0-b126367f49a9.png">

**Comment by RothAndrew** [comment]
It would make sense that `zarf tools registry catalog` with no argument to specify which registry, would by default automatically pick Zarf's registry.

**Comment by RothAndrew** [comment]
Documenting my "pain journey" on how to figure out what's in the registry.

#### Figure out what the password is for the registry so I can log into it.
1. I didn't catch what the password was when it was displayed at the end of `zarf init` cause it was run using automation. AFAIK there's no way to easily re-display that little table that you get at the end of `zarf init`
1. There's no equivalent to `zarf tools get-git-password` for the registry, so I had to run `zarf tools k9s`, navigate to the secrets in the zarf namespace, decode the `zarf-state` secret, and scrape through the minified json to find it

#### Port forward the registry
1. Look up what the name of the connect "name" is for the registry by running `zarf connect list`
2. Facepalm for not already remembering that it is "registry"
3. Run `zarf connect registry`
4. Figure out which port it used (in my case it was 35121)
5. Minimize that terminal window (it's a running/blocking command)

#### Login to the registry
1. Open a new terminal window, ssh into my server, `sudo su`, and change directory to where I've got all my zarf stuff
2. Re-do section 1 since I copy/pasted something and lost the password...
3. `zarf tools registry login localhost:35121 -u zarf-push -p <the password>`

#### Get contents of registry
1. `zarf tools registry catalog localhost:35121`

**Comment by RothAndrew** [comment]
What was the resolution here? Am I able to just run "Zarf tools registry catalog"? Or something else?

**Comment by Racer159** [comment]
Yes just `zarf tools registry catalog` https://github.com/defenseunicorns/zarf/blob/main/docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_tools_registry_catalog.md
