### ISSUE TITLE
Assess current Big Bang airgap documentation / procedures for any additional insights not currently covered by Zarf

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#12]
Refs:

https://repo1.dso.mil/platform-one/big-bang/bigbang/-/tree/master/docs/airgap
https://confluence.il2.dso.mil/pages/viewpage.action?spaceKey=ONBOARD&title=Edge+Deployment+Scenarios+Defined

---

Migrated from https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/18

**Comment by RothAndrew** [comment]
![image](https://user-images.githubusercontent.com/16000938/132417270-394c18db-33e2-4aa8-ab5b-1850fc82c80d.png)

**Comment by jeff-mccoy** [comment]
I think we've pretty much covered this one now since Zarf now fully replaces the BB airgap docs flow.
