### ISSUE TITLE
Invalid container image hash being pulled from registry

### ISSUE THREAD

**Issue by NunoSav** [defenseunicorns/zarf#1210]
### Environment
Device and OS: Ubuntu 22.04.1
App version: 0.23.3
Kubernetes distro being used: v1.25.4+k3s1
Other:

### Steps to reproduce
1. spin up a k8s Job with k8s go api library

### Expected result
Container uses correct image hash

### Actual Result
Incorrect registry image hash is used (best seen in screenshots below)

### Visual Proof (screenshots, videos, text, etc)
![Screenshot 2023-01-17 at 17 58 50](https://user-images.githubusercontent.com/26490343/212977399-0680fcdc-4afa-4ee4-97b1-79297b676f1d.png)
<img width="1778" alt="Screenshot 2023-01-17 at 18 00 17" src="https://user-images.githubusercontent.com/26490343/212977417-23f82447-bbb4-4581-8706-1b92ec00f22d.png">

### Additional Context
I use the same code to spin up a Job with "ubuntu:jammy" image and i have no issues there.

**Comment by jeff-mccoy** [comment]
This usually happens when there is some mismatch between the complete image url in the calling manifest and the image url given to zarf, e.g. `mydomain.com/repo/image:tag` will not be the same as `mydomaiin.net/repo/image:tag`. This includes the port.
