### ISSUE TITLE
Improve the docs for the Zarf config-file

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1216]
**Is your feature request related to a problem? Please describe.**
My automated deployment process runs Zarf from a couple of different folders, such that it is difficult/annoying to have a zarf config file in each folder where zarf runs

**Describe the solution you'd like**
I'm able to have one zarf config file in a centralized place (like my home directory)

**Describe alternatives you've considered**
* multiple config files (gross)
* Add environment variables to my .bashrc (messy, and wouldn't work in cases where bash isn't being used)

**Comment by jeff-mccoy** [comment]
We probably just need to update the docs, it already does home dir like kubectl:

```golang
// Search config paths in the current directory and $HOME/.zarf.
		v.AddConfigPath(".")
		v.AddConfigPath("$HOME/.zarf")
		v.SetConfigName("zarf-config")
```

**Comment by RothAndrew** [comment]
What am I doing wrong?
<img width="531" alt="image" src="https://user-images.githubusercontent.com/16000938/213269267-a3870948-e5b0-42e3-82a0-3c97dbacc3b9.png">

**Comment by abhiyant-10** [comment]
Hello , I would like to contribute to this issue , but I cannot find this command in docs .  Can you please direct me so that I can correct and make my 1st contribution to zarf

**Comment by wirewc** [comment]
@abhiyant-10 the closest I can find using `grep -nriHe "zarf-config"` in the docs folder was discovered [here](https://github.com/defenseunicorns/zarf/blob/main/docs/4-user-guide/1-the-zarf-cli/100-cli-commands/zarf_prepare_generate-config.md).

**Comment by jeff-mccoy** [comment]
👋 I believe [this](https://docs.zarf.dev/docs/user-guide/the-zarf-cli/#using-a-config-file-to-make-cli-command-flags-declarative) might be the area we could add it. There should be an edit button on that page.

**Comment by abhiyant-10** [comment]
@jeff-mccoy I did went through that part but as described here the path needs to be corrected and I am not finding any path described in that section. Please , correct me if I am wrong


> I figured it out. Needed the file to be at `~/.zarf/zarf-config.toml` rather than `~/zarf-config.toml`
> 
> Agree docs need updated. It's not mentioned that this is doable or where to put the file.
> 
> <img alt="image" width="541" src="https://user-images.githubusercontent.com/16000938/213270966-31f56374-0db1-4fd9-98a9-409d358506c2.png">

**Comment by Racer159** [comment]
@abhiyant-10 correct, that section doesn't mention the home dir location currently but should expand on the description of using environment variables to specify a config file name by mentioning that it will also pickup config files from either your current working directory or `~/.zarf/` @Madeline-UX if there is specific verbiage you would like to include.

**Comment by abhiyant-10** [comment]
I might still need some help for that :( . I would be glad to work on that but would be really thankful for any assistance

**Comment by Madeline-UX** [comment]
@Racer159 I am happy to review a draft but do not have the technical context to come up with verbiage on my own. 

Suggestion for format
1. Include a description of default behavior (home dir)

2. Add a subsection with the additional behavior options - use environment variables to specify config file name. 

Should include a description of the use case for each option as well as an example of what commands you would paste into the terminal in order to execute it

**Comment by Racer159** [comment]
@abhiyant-10 no problem if you review our contributing guidelines (https://github.com/defenseunicorns/zarf/blob/main/CONTRIBUTING.md) and then draft up some edits to line 143 or so here (https://github.com/defenseunicorns/zarf/blob/main/docs/4-user-guide/1-the-zarf-cli/index.md?plain=1) to add that it should be fine.  @Madeline-UX  and I can review it from there and provide suggestions/tweaks.

**Comment by Racer159** [comment]
Adding to this issue a list of things to add based on a convo with @corang.

- [ ] Move the [config-file section](https://docs.zarf.dev/docs/the-zarf-cli/#using-a-config-file-to-make-cli-command-flags-declarative) to it's own page (still linked from a shorter section in the CLI page)
- [ ] Provide examples of the high-level config file keys on that page and descriptions of what they do / how to use them (with `toml`, `json`, and `yaml` versions in tabs like we have on [components](https://docs.zarf.dev/docs/create-a-zarf-package/zarf-components#chart-examples) now)
- [ ] Describe more specifically where the config files load from - Home directory, CWD, ENV Var location.
