### ISSUE TITLE
How to remove Zarf from Kubernetes cluster

### ISSUE THREAD

**Issue by n8ores** [defenseunicorns/zarf#1217]
How can we remove ZARF From our Kubernetes cluster? We accidently installed Zarf into a K8's cluster that we dont want it in, and now whenever we create a new project it appears to be looking for the container images on localhost instead of the external registry. 

I can't seem to find any documentation on how to remove Zarf from a cluster and remove all of its dependencies. I tried doing `kubectl delete namespace zarf` but now we just get errors when trying to create new projects in the cluster.

**Comment by n8ores** [comment]
I tried doing `zarf destroy` and now get this error (probably because I did a `kubectl delete namespace zar` )

`zarf destroy --confirm

Saving log file to /tmp/zarf-2023-01-18-12-03-50-4125058721.log
 WARNING  Failed to load Zarf state from cluster
 WARNING  Unable to find the folder ("/opt/zarf") which has the scripts to cleanup the cluster. Do you have
          the right kube-context?`

**Comment by YrrepNoj** [comment]
`zarf destroy --confirm --remove-components` will remove Zarf and anything it has attempted to install.

That said.. that command uses a secret in the zarf namespace to determine what it  has installed. Let me try to pull together an example secret you can apply so that it can probably be happy.

**Comment by n8ores** [comment]
That was exactly it, I tried deleting ARGOCD from the cluster entirely, and reinstalling and it didn't fix it, but then tried 

`kubectl delete mutatingwebhookconfiguration zarf` and that fixed it, thanks!

Appreciate the rapid feedback too.
