### ISSUE TITLE
Component Dependencies

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1222]
There are components that have un-defined, but real, dependencies on other components existing in the cluster.  For example, when uploading a repo, there needs to exist a git server configured in the Zarf init.  If that doesn't exist, then deploying the component on the cluster will fail since the repos can't get uploaded.

There are/will be comparable dependencies in the future with BigBang needing Flux or other capabilities.  

Would like to look for a standardized way to either:
* assure the cluster has been initialized with the correct/necessary components
* provide scripts/actions default to specify that a component was installed, even if its not part of the same Zarf package.

This might also lead to some features that would add components to a zarf package that are dependencies  (once #1060 ) and conditionally add them if they're not already installed by another zarf package

**Comment by Noxsios** [comment]
I believe `wait` actions in `onDeploy.before` would suffice for this.
