### ISSUE TITLE
Cannot reference git repositories over SSH

### ISSUE THREAD

**Issue by lsoica** [defenseunicorns/zarf#1245]
### Steps to reproduce
1. For this zarf.yaml
```
kind: ZarfPackageConfig
components:
  - name: name
    description: description
    required: true
    repos:
    - git@<gitlab server>:<group>/<repository>.git
```
2. Creating the package with:
```
zarf package create --confirm
```
3. Results in the following error being thrown:
```
  ✔  Loading 1 git repos                                                                                                    
     ERROR:  Failed to create package: unable to add component: unable to pull git repo
             git@<gitlab server>:<group>/<repository>.git: unable to get extract the
             repoName from the url git@<gitlab server>:<group>/<repository>.git
```
### Expected result
Successfully clone and package the repo over SSH.

**Comment by Racer159** [comment]
Thanks for the report!  This is something that is possible on `main` if you include the protocol in the URL (we use that right now to allow us to better handle a mix of ssh and http repos) and should be in the next release.

`ssh://git@<gitlab server>:<group>/<repository>.git`

![image](https://user-images.githubusercontent.com/3977569/214175651-db06b17d-8645-47ec-8f86-05f84f34a992.png)

This is something that does deserve better documentation / messaging however so adding the UX / documentation labels.

Also even on older versions of Zarf you can move the git repos around in this way (if that is useful to you) it is just flux that wouldn't work until we release some more fixes for that.

**Comment by lsoica** [comment]
@Racer159 Thanks! It worked by following the syntax you provided: ssh:// as the protocol and then '/' as a delimiter between gitlab group and project, instead of ':'
