### ISSUE TITLE
FindImages doesn't run any images found in Job Hooks

### ISSUE THREAD

**Issue by joelcomp1** [defenseunicorns/zarf#1246]
### Environment
Device and OS: Ubuntu 22.04
App version:  0.23.5
Kubernetes distro being used: KRE2

### Steps to reproduce
1.  Provide a helm chart to zarf.yaml (Like Flux) that contains a Job in the hook

kind: ZarfPackageConfig
metadata:
  name: test-helm-local-chart
  description: "Deploys Flux"
components:
  - name: flux
    required: true
    charts:
      - name: flux2
        localPath: charts/flux2
        namespace: flux-system
        version: 2.4.1

Because the Job is a hook, it is not included in the output Template from the Helm chart and as such is not included in the output image list.

### Expected result

Should include the image that the hook job uses that way when deployed air-gapped the container exists in that environment.

### Actual Result
Image is misssing.

### Visual Proof (screenshots, videos, text, etc)

Output of the above helm chart is:

- name: flux
    images:
      - ghcr.io/fluxcd/helm-controller:v0.27.0
      - ghcr.io/fluxcd/image-automation-controller:v0.27.0
      - ghcr.io/fluxcd/image-reflector-controller:v0.23.0
      - ghcr.io/fluxcd/kustomize-controller:v0.31.0
      - ghcr.io/fluxcd/source-controller:v0.32.1

### Additional Context

I think the issue is in chart.go in TemplateChart(), the templatedChart has a hook attribute but that is not included in the Manifest object.  Need to just append the Hook YAML to the existing manifests I believe and the rest of the code should work as it already does.

**Comment by joelcomp1** [comment]
I can put a PR in if this change makes sense but I think all that is required is this modification to chart.go

	manifest := templatedChart.Manifest

	for _, hook := range templatedChart.Hooks {
		manifest += "---\n" + hook.Manifest
	}

	spinner.Success()

	return manifest, nil

**Comment by Racer159** [comment]
Apologies that this issue had fallen off of the project board - I actually combined this into a PR in #1645 that cleans up the prepare commands more generally.
