### ISSUE TITLE
Add a way to version control components

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/zarf#1270]
Problem:

Zarf integration with 3rd-party applications like Spectro Cloud's Palette happens at the package level. When a Zarf package maintainer wants to patch a component, Palette is applying the package and show's two packages. There isn't a clean mechanism for Palette or other 3rd-party tools to track and manage Zarf packages at the component level.

Proposed solution:

Natively version control components. Constrain components to have unique names within a given Kubernetes cluster, apply a content- and date-based hash, and sign the component so Palette or other 3rd-party tools can differentiate based on the component's version.

**Comment by Racer159** [comment]
Do you have an example of this integration? Also have you looked seen the package secrets? `kubectl get secrets -n zarf zarf-package-dos-games -o jsonpath='{.data.data}' | base64 -d`

Zarf only versions things at the package level (and components (except for optional ones) are deployed per package)

**Comment by Racer159** [comment]
@mikevanhemert just following up on the above

**Comment by mikevanhemert** [comment]
Thank you for the reminder. We are still heading down a path to deploy with Palette and have are going to deploy 1 Zarf package for every capability because there isn't a way to version control individual components. Recommend closing this issue.
