### ISSUE TITLE
Main README: Coming Soon - Roll Your Own

### ISSUE THREAD

**Issue by btlghrants** [defenseunicorns/zarf#132]
As a learner of Zarf
I need to get comfortable with making my own Zarf packages
Because it's how I'll use Zarf "in the field"

---

1. Write new docs/your-own-package.md page walking through creation & deployment of a custom package
2. Update "Roll Your Own - Coming Soon" link in main README to point to new page

---

Spun off from #47

**Comment by Daemonslayer2048** [comment]
I am new to zarf and have deployed the demo, I am now moving on to trying to roll my own package. As this issue is still open is it possible someone may be willing to share notes? 
Would the documentation also include how to handle secrets and parameters?

**Comment by RothAndrew** [comment]
The best way right now IMO is to use the examples that are in the examples folder. They mostly cover the various features and are constantly updated. Since Zarf is changing so fast right now it has been hard to keep up with the docs.

**Comment by RothAndrew** [comment]
Feel free to ask if you have questions, either here in the issues or in the discussions section.

**Comment by RothAndrew** [comment]
Blocked by #237

**Comment by jeff-mccoy** [comment]
Going to re-evaluate these stale doc issues, closing for now.Going to re-evaluate these stale doc issues, closing for now.
