### ISSUE TITLE
zarf.yaml flag `metadata.uncompressed` now changes compression of `./components/<name>.tar`.

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1323]
Discussion https://github.com/defenseunicorns/zarf/discussions/1298
Epic https://github.com/defenseunicorns/zarf/issues/1319

Dependent on completion of:
* Issue #1322
* Issue #1321 

Note: 
Needs to be a feature branch before being merged into project

**Comment by wirewc** [comment]
Is this feature still needed? It seems to fundamentally break how the Zarf data injector package works.

**Comment by Racer159** [comment]
Closing as unimplemented
