### ISSUE TITLE
Warn users about compatibility of zarf packages between Zarf verisons

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1325]
### Is your feature request related to a problem? Please describe.
Deploy users don't have a way to ensure that the zarf package they are accepting from the creator will run with their current version of the Zarf CLI.

### Describe the solution you'd like
On deploy we should check the Zarf version in the build data of the Zarf package and warn the user if it does not match the current CLI version.

### Describe alternatives you've considered
We could try another more complicated solution but this would be the simplest way to notify the user for now.

### Additional context

**Loosely tied to:**
Discussion https://github.com/defenseunicorns/zarf/discussions/1298
Epic https://github.com/defenseunicorns/zarf/issues/1319

**Comment by Racer159** [comment]
@YrrepNoj is this more of an *ility on the issue you are already working?

**Comment by Racer159** [comment]
We could also in a future ticket compare the zarf.schema.json if we include it in the zarf package.
