### ISSUE TITLE
Main README: Coming Soon - Simple Applications (Appliance Mode)

### ISSUE THREAD

**Issue by btlghrants** [defenseunicorns/zarf#133]
As a prospective user of Zarf
I want to know how Zarf can help me "just run apps"
So that I can understand & convince others of Zarf's applicability

---

1. Write new docs/appliance-mode.md page describing what "appliance mode" means & "what you get" by using it
2. Update "Simple Applications - Coming Soon" link in main README to point to new page

---

Spun off from #47

**Comment by RothAndrew** [comment]
Blocked by #237

**Comment by jeff-mccoy** [comment]
Going to re-evaluate these stale doc issues, closing for now.
