### ISSUE TITLE
Main README: Coming Soon - Disconnected GitOps (The Utility Cluster)

### ISSUE THREAD

**Issue by btlghrants** [defenseunicorns/zarf#134]
As a prospective user of Zarf
I want to know how Zarf can help me "in the airgap"
So that I can understand & convince others of Zarf's applicability

---

1. Write new docs/utility-cluster.md page describing what "utility cluster" means & "what you get" by using it
2. Update "Disconnected GitOps - Coming Soon" link in main README to point to new page

---

Spun off from #47

**Comment by RothAndrew** [comment]
Blocked by #237

**Comment by jeff-mccoy** [comment]
Going to re-evaluate these stale doc issues, closing for now.
