### ISSUE TITLE
Unable to re-build zarf package if it contains a git repo that has been moved

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1348]
### Environment
Device and OS: Ubuntu EC2 instance
App version: v0.24.0-rc5
Kubernetes distro being used: built-in k3s
Other:

### Steps to reproduce
1. Create a zarf.yaml with a git repo that has been moved (but you are specifying the old location)
2. Create the zarf package (works successfully, Gitlab automatically redirected to the new location)
3. Re-create the zarf package (fails with below error)

### Expected result

Package is able to be re-created

### Actual Result

(Note: This repo is a public repo. Does not require authentication)

<img width="1634" alt="image" src="https://user-images.githubusercontent.com/16000938/217935739-4ff58d0e-2de8-480d-afee-15a13c272a3b.png">

### Severity/Priority

I will need to delete my zarf cache more often which adds time to my feedback loop, but not an immediate urgent issue.

### Additional Context

* The `Repo already cloned, pulling any upstream changes...` makes me think the issue here lies in the logic around caching of git repos
* Deleting ~/.zarf-cache and re-running fixed the issue

**Comment by dsmithbauer** [comment]
Agreed. I see the same behavior and can confirm the workaround of clearing the Zarf cache (zarf tools clear-cache) works.  Using Zarf v0.24.1.

**Comment by AbrohamLincoln** [comment]
I did some testing and this is what I found:
- I cannot re-create the issue with github.com repositories.
- I can re-create the problem with gitlab.com repositories, moved or not.
- If you supply credentials via a netrc file (even though the repo is public), the cached repo updates properly.
- The credentials supplied via a netrc file must be valid.

**Comment by AbrohamLincoln** [comment]
It looks as though there are changes in [this](https://github.com/defenseunicorns/zarf/pull/1094) PR that will resolve this issue.

**Comment by Racer159** [comment]
Git behavior was refactored in https://github.com/defenseunicorns/zarf/releases/tag/v0.25.0 and this should be fixed (can reopen if needed)
