### ISSUE TITLE
Running zarf connect git uses 100% CPU

### ISSUE THREAD

**Issue by dsmithbauer** [defenseunicorns/zarf#1357]
### Environment
Device and OS: MacBook Pro MacOS Ventura 13.2
App version: v0.24.1
Kubernetes distro being used: Rancher Desktop (Moby) + Kind k8s cluster @ v1.24.7
Other:

### Steps to reproduce
1. Run `zarf connect git`
2. Note CPU at 100% in Activity Monitor

### Expected result
Creating a tunnel to Gitea or other services in cluster should not use 100% CPU.

### Actual Result
zarf process uses 100% CPU every time.

### Visual Proof (screenshots, videos, text, etc)
![image](https://user-images.githubusercontent.com/32399829/218812468-e2b1eeef-6e47-4bac-a5b9-74abca53b37f.png)

**Comment by Racer159** [comment]
@dsmithbauer are you still seeing this as of v0.26.2? Tested with @Noxsios and saw 6% and 10% CPU usage on Linux and macOS respectively.

**Comment by dsmithbauer** [comment]
Sorry for the delay. I took some time to retest with the latest Zarf v0.26.4 version today. Unfortunately, I'm still seeing the behavior.

<img width="785" alt="image" src="https://github.com/defenseunicorns/zarf/assets/32399829/ed6e2cec-17e2-44ac-984b-55442a48a07a">

Same configuration as before
- Rancher Desktop (Moby) v1.8.1 /w k8s disabled
- Clean/empty Kind Cluster v1.24.7
- zarf init (v0.26.4 ) with Yes to all options
- zarf connect git

Let me know if you require any additional information.

**Comment by Racer159** [comment]
Hmm adding this to a future milestone for some more investigation

**Comment by bdw617** [comment]
Reproduced in 0.30.1 on WSL2. let me see if I can profile it.

**Comment by bdw617** [comment]
Hi! Yes, this is a problem. I ran pprof on the code and noticed: runtime.Gosched() called in a loop is the problem. I removed it and zarf functioned normally (and the tunnel still worked). I've got a fix to test.
