### ISSUE TITLE
Support additional GitOps tooling (fleet)

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1360]
### Is your feature request related to a problem? Please describe.
Zarf should support more GitOps tools than just flux, fleet (https://fleet.rancher.io/) is another tool commonly used for this task that also has CRDs that should be modified by Zarf.

### Describe the solution you'd like
Additions to the agent to support fleet CRDs

### Describe alternatives you've considered
Manifests could be mutated beforehand but this can be cumbersome across updates/larger projects

### Additional context
https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1676395239817589

**Comment by dsmithbauer** [comment]
Why close this? And there were unmerged code commits related to this that are being thrown away?

**Comment by Noxsios** [comment]
The associated PR was closed two months ago (the PRs branch was not deleted however `1360-initial-fleet-support`), and this effort has not seem much progress for almost a year.

The Zarf team is going through all current issues and closing all that are either stale or do not reflect project goals. Making Zarf more GitOps native is definitely a nice feature to have, but it is not a current top priority of the team.

If you, or others you know have the bandwidth to support adding this, feel free to reach out to the team on which parts of the codebase would need changes! With the upcoming donation to OpenSSF, this project is going to be more community owned and maintained.
