### ISSUE TITLE
Zarf Package Schema Lacks Clarity

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/zarf#1366]
### Is your feature request related to a problem? Please describe.
The Zarf Package Schema is not clear. Things like the `metadata.architecture` have type `string` without example on what is valid or preferred. New parties interested in creating Zarf packages aren't guided by the schema as it is defined.

### Describe the solution you'd like
Schema fields that are enumerable strings should be enumerated [like this](https://pkg.go.dev/github.com/swaggest/jsonschema-go#example-Enum) requiring a change in the [package type](https://github.com/defenseunicorns/zarf/blob/main/src/types/package.go).

Other fields' descriptions should be improved to help new Zarf converts. Non-enumerable string fields descriptions should clearly indicate potential values.

### Describe alternatives you've considered
Improving and expanding the Examples in the Docs would help. However, it is unlikely that a single example will align with all Zarf package developer's goals. Developers will be left pulling together information from many examples. It is preferable to bolster a single authoritative source: the schema itself.

### Additional context
Architecture field definition in Zarf package schema on the zarf.dev webpage
![image](https://user-images.githubusercontent.com/108541208/219505084-80397bda-212c-4a2a-bf44-d4be9c25be7b.png)

**Comment by mikevanhemert** [comment]
Docker's [officially supported architectures](https://github.com/docker-library/official-images#architectures-other-than-amd64) (not that aligning to Docker is a goal but it is a jumping off point) are `arm32v6`, `arm32v7`, `arm64v8`, `amd64`, `windows-amd64`. There are also options like `i386`, `riscv64`, `s390x`, and `ppc641e`.

Is there an argument to focus on field descriptions that include likely examples over adding rigid enums?

**Comment by jeff-mccoy** [comment]
The arch metadata field isn't very common as its job is to actually restrict what arch a package uses. But we could add an enum like we do a few lines above it: https://github.com/defenseunicorns/zarf/blob/main/src/types/package.go#L9

**Comment by Racer159** [comment]
@mikevanhemert I made some tweaks to the schema to include examples and reflowed a lot of it to make CTRL-F more likely to work, and to make the TOC more consistent.  Let me know if you have feedback:

https://deploy-preview-1381--zarf-docs.netlify.app/docs/user-guide/zarf-schema

cc @bdfinst @Madeline-UX and @Jessy-Morris

**Comment by Madeline-UX** [comment]
@Racer159 I have some broader concerns about the navigation of this page and some ideas for improvement but i think this change adds value now so i added those thoughts to a new issue so we do not hold up this PR
