### ISSUE TITLE
Zarf pushing to Registry should check if digest already exists

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1369]
### Is your feature request related to a problem? Please describe.
When deploying and iterating on a Zarf package deployment that shares a lot of the same artifacts (e.g. BigBang), the zarf binary pushes the image digest to the zarf registry every time rather than checking to see if the digest is already present in the registry.

**Comment by Racer159** [comment]
@runyontr are you still seeing this behavior? It should do `HEAD` checks before image pushes that may already exist

**Comment by Racer159** [comment]
Closing per the above - this should be resolved now - can reopen if needed.
