### ISSUE TITLE
Documentation for built-in Zarf variables (i.e. ZARF_REGISTRY)

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1374]
**As** Ezra **I want** to see what built-in templates are available **so that** I can use them in my own packages.

## Acceptance Criteria

**Given** I am on `docs.zarf.dev`
**When** I visit a new page under https://docs.zarf.dev/docs/create-a-zarf-package/
**Then** I will see a new page discussing package defined variables and built-in deploy-time variables
**And When** I select that page
**Then** I will see sections for Variables, Constants and all of the built in templates that Zarf has.

https://github.com/defenseunicorns/zarf/blob/main/src/internal/packager/template/template.go#L75

## Additional Context

I was trying to identify what zarf variables are automatically available to zarf package creators, e.g. something like ###ZARF_PKG_NAME#### or ###ZARF_PKG_NAMESPACE### but couldn't find any documentation on it.

**Comment by Racer159** [comment]
@Madeline-UX here is another example of Docs <> Examples <> Walkthroughs information architecture mixups.

@runyontr there are _some_ docs here: https://docs.zarf.dev/examples/package-variables/#how-to-use-create-time-package-variables

**Comment by Noxsios** [comment]
My initial thoughts would be an addition to `make docs-and-schema` to add a `go run main.go internal gen-variables-docs` (or something along those lines)
