### ISSUE TITLE
Docs Update: Warning on Package Create Variables page 

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1382]
### Is your feature request related to a problem? Please describe.

A user tried to use the package create variables feature to add secrets to a package and ran into issues that resulted in a reach out on K8 channel for help. There seems to be missing information from docs addressing the best way to add secrets to a package.

The user chose to use package create variables which is not the best practice because it hardcodes the variables into the deployment. 

See this thread for reference: https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1677250811500439

### Describe the solution you'd like
I would like to see

- [x] add Admonition (caution) on package variables page https://docs.zarf.dev/examples/package-variables/  that warns against using this feature for secretes. Message something like this "Package create variables will hard bake their values into the package and are not recommended for secrets
- [x] ~Add a page on best way to handle credentials and secrets to package to the security page (@Noxsios for issue linking)~ converted into https://github.com/defenseunicorns/zarf/issues/1684
- [x] Add a package create tutorial 

### Additional context

- https://docusaurus.io/docs/markdown-features/admonitions

**Comment by Madeline-UX** [comment]
@Racer159 is there any other context or solution you think would be helpful for resolving this issue

**Comment by Racer159** [comment]
I think we just need better docs (and maybe a variables walkthrough) initially.  We can also rethink create-time variables at some point as well since they are very different from deploy time variables but both could be called "Zarf Variables"

**Comment by Racer159** [comment]
This actually could also be a package create walkthrough more generally, with tips and tricks for a variety of different things.
