### ISSUE TITLE
Information Architecture Redesign: Navigation Tree for Docs site

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1383]
### Is your feature request related to a problem? Please describe.
Current navigation on docs site has the shown the following user issues:
- Users do not understand what an operator manual is and how it is different from user manual
- Examples are often confused with tutorials and lead to users trying solutions that do not fit their user need
- Users claim that information is difficult to find in tree
- Information is not sorted by action or role

### Describe the solution you'd like

Conduct user testing on current state to get more feedback 

- [x] Card Sort 
- [x] Survey
- [x] Usability testing (observation and feedback)

Redesign the Navigation tree 

- [x] Mock tree in figma or other tool
- [x] Retest for validation

Make changes in the code
- [x] Change developer guide > Contribute to Zarf
- [x] Remove operator manual

### Describe alternatives you've considered
blowing it all up lol jk but kind of. 

### Additional context

Add design files and research finding as they come

**Comment by Madeline-UX** [comment]
@Racer159 how do we want to track this work in milestones. This is the overarching epic that @jessy and I will use to track the work related to the IA redesign of the docs sites.

**Comment by Jessy-Morris** [comment]
commenting

**Comment by Racer159** [comment]
I think we could split it into three issues as you outlined above (and more as needed) along the user interview -> redesign -> implement lines.  Not sure how we feel about the `spike` issue pattern but it is one that I have liked for prototyping and researching solutions for an end product (usually an issue is labeled as a `spike` and then there is some documented outcome from that (i.e. documented user interview notes/analysis) that is used to build the next story or spike.

**Comment by Madeline-UX** [comment]
Done!
