### ISSUE TITLE
Communicate Feature - Convert SBOM to security compliant formats .spdx or .cyclone.dx

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1387]
### Current State

I spoke with someone who works in defense cyber security about SBOM. They were very eager and concerned about the format type for SBOM to meet compliance. The conversation could not proceed much past them knowing what formats Zarf supported for SBOM - indicating that it is important to potential users to know upfront if SBOM supports file formats that are compliant with government controls. 

As a potential Zarf users - I would like to easily be able to find information on what SBOM file formats Zarf supports. This is important to my contract requires me to have an SBOM in a compliant format (.spdx or .cyclone.dx) to delivery my software to a controlled system. 

### Describe the solution you'd like

- [x]   1. Create SBOM Docs page  under user guide (currently just CLI commands and SBOM UI pages)
- [ ]  2. Add button to convert SBOM file type in UI
- [ ]   3. Add reference to SBOM file type compliance to website home page (why use zarf section)
- [x] 4. Add as a feature to the to feature list on the docs overview
- [ ] 5. Add as a feature to feature list in github read.me

**Comment by Noxsios** [comment]
Completed in https://github.com/defenseunicorns/zarf/pull/1688
