### ISSUE TITLE
UX Testing - Release Notes Major

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1392]
## Driving Question 
*What are we hoping to validate?*

- Are Zarf major release notes easy to read and understand for Zarf users?
- Do the release notes have enough information for a user to discover and use new features quickly?
- How might we improve our release notes?

## Testing Plan 

- [x] Create a user test in Maze to gather feedback on the current format of zarf release notes. 
- [x] Run test (sample - internal unicorns & k8 slack)
- [ ] Analyze results
- [ ] Create recommendations for @Racer159 
- [ ] Add release notes guidance to style guide

## Results

https://app.maze.co/report/Zarf-Significant-Release-Notes/1bmgilfiqm0lv/intro

## Additional context 

Test using release. [v0.24 ](https://github.com/defenseunicorns/zarf/releases/tag/v0.24.0)

**Comment by gregclark-defenseunicorns** [comment]
Hey @Madeline-UX, did you mean to put _"...major release notes?"_ in stead of _"...minor release notes?"_?
