### ISSUE TITLE
UX Test: Zarf Deploy UI Navigation

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1396]
## Driving Questions ##
*What are we hoping to validate?*

- Does the hierarchal structure of the left draw make sense (sections and subheaders)?
- Do users understand the naming convention used for pages?
- Does the user know where to navigate to find the SBOM compare tool?
- Does the user know where to find the currently deployed packages?
- Does the user know where to find more help/guide using the tool?

## Testing Plan ##

- [ ] Create a user test in Maze to gather feedback on current wireframes for Zarf UI
- [ ] Run test (sample - internal unicorns & k8 slack)
- [ ] Analyze results
- [ ] Iterate on design based on feedback or handoff to devs

## Additional context ##
*Screenshot or link to what needs to be tested*

Related to issue #1310 

[Prototype to test ](https://www.figma.com/proto/MUItIzpzLBLuIyt225Bwgl/Zarf-UI?node-id=1031%3A54553&scaling=min-zoom&page-id=2%3A11577)

[Figma Design ](https://www.figma.com/file/MUItIzpzLBLuIyt225Bwgl/Zarf-UI?node-id=2%3A11577&t=jdZ6atUZHsZiydfM-1)

![🚧 Navigation Drawer](https://user-images.githubusercontent.com/92826525/222008419-9836fd6b-18ff-47a1-874f-bf5d7f0f5ad7.png)

## Link to Test ##

Preview Test here - https://app.maze.co/maze-preview/mazes/146834275

**Comment by Noxsios** [comment]
Closing due to https://github.com/defenseunicorns/zarf/issues/1500
