### ISSUE TITLE
Add zarf config schema

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#14]
Be cool like @runyontr and use a schema to prevent simple errors with `zarf-config.yaml` files.

---

Migrated from https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/29

**Comment by RothAndrew** [comment]
This is done. In the repo there is `/zarf.schema.json`. `zarf tools config-schema` generates it.

**Comment by YrrepNoj** [comment]
Should we reopen this for the purpose of adding it to a precommit? Right now it has been manually added to git so future updates won't get caught automatically.

**Comment by RothAndrew** [comment]
I'll write up a new issue to add a pre-commit hook. Good catch.
