### ISSUE TITLE
Evaluate options to replace containerd mirroring config

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#140]
K3s containerd mirror config works really well, but makes it harder to easily support other K8s distros without knowing the underlying container runtime details.  Deploying a mutating webhook would enable a k8s-native approach to this problem.  The Google surfaced a couple possibilities to consider adopting (both have very small contributor lists):

https://github.com/jainishshah17/tugger
https://github.com/estahn/k8s-image-swapper?ref=golangrepo.com

**Comment by RothAndrew** [comment]
@jeff-mccoy do we still need this issue? Or will it already happen in the native apply stuff you're doing now?

**Comment by RothAndrew** [comment]
@jeff-mccoy will #237 close this?

**Comment by jeff-mccoy** [comment]
absolutely
