### ISSUE TITLE
docs need improving

### ISSUE THREAD

**Issue by bdw617** [defenseunicorns/zarf#1421]
https://docs.zarf.dev/docs/walkthroughs/big-bang#package-big-bang

in order to do a "zarf package create" on bigbang, you need to be logged into repo1. 

See here:
https://repo1.dso.mil/big-bang/bigbang/-/blob/master/docs/guides/deployment-scenarios/quickstart.md#step-6-verify-your-ironbank-image-pull-credentials

**Comment by Noxsios** [comment]
I am confused, that is handled by the setup section: https://docs.zarf.dev/docs/walkthroughs/big-bang#setup

![Screenshot 2023-03-07 at 3 49 04 PM](https://user-images.githubusercontent.com/50058333/223561055-7e957ccb-c303-4e23-acee-8f3f237c40a2.png)

**Comment by bdw617** [comment]
nope, you're not confused, we missed the step. I've asked Josi to put in a comment on the error you get if you can't auth to repo1 that explains you missed this step. :)
