### ISSUE TITLE
Differential Updates for Composable Components 

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/zarf#1426]
### Is your feature request related to a problem? Please describe.
As a package creator using composable components, it is frustrating to rebuild / update large zarf packages that apply only small updates / incremental changes. 

### Describe the solution you'd like
I would like 'zarf package create` on a composed package to only rebuild the component packages that have changed. This would encourage smaller, more frequent updates more efficiently. Conversely, the current state of zarf may incentivize larger batch updates (which carry more risk) or decentralized zarf packages(requires documentation outside of the packages / introduces more opportunities for human error).

### Describe alternatives you've considered
Planning long walks and engagements during package build pipelines, using decoupled / decentralized zarf packages, naps, or potentially looking at zarf actions to help build differential Updates smartly (introduces additional complexity and doesn't afford reusability for others).

**Comment by ntwkninja** [comment]
Once zarf packages can be [composed from an OCI registry](https://github.com/defenseunicorns/zarf/pull/1376), could we reuse the image logic (which I believe only pulls if the hash is different) for packaging of OCI components?

**Comment by Racer159** [comment]
Added a discussion here: https://github.com/defenseunicorns/zarf/discussions/1438

**Comment by Racer159** [comment]
Relates to https://github.com/defenseunicorns/zarf/issues/19

**Comment by Racer159** [comment]
#1650 delivered this partially but moving the OCI piece back to be delivered after OCI composability is actually released.
