### ISSUE TITLE
Rearchitect documentation generator from markdown

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1429]
### Describe what should be investigated or refactored
We have had issues with Docusaurus and would like to explore other options for hosting a documentation site.  This should explore:

1. If we can modify Docusaurus to fit our needs better
2. If another solution better meets our needs

This should not lose the following:

1. Search - including good index and offline support
2. Support for custom MDX syntax (notes and admonitions)
3. Configurability/themability

This will also need an ADR comparing different options and explaining why we went a particular direction.

### Links to any relevant code
https://github.com/defenseunicorns/zarf/tree/main/docs-website

### Additional context
This comes out of us looking at our docs and thinking about how we could incorporate them into Zarf to bring it along to the airgap.

**Comment by Racer159** [comment]
relates to - https://github.com/defenseunicorns/zarf/issues/1278

**Comment by Racer159** [comment]
also - https://github.com/defenseunicorns/UnicornUI/issues/86

**Comment by abhiyant-10** [comment]
We can also add DocsGPT support by training the model for Zarf , it can give better understanding to the  users and also handle most of the queries

**Comment by Racer159** [comment]
Summarizing this thread (https://kubernetes.slack.com/archives/C03BP9Z3CMA/p1678915928812279): 

I think this is a good place to build off from for an ADR I know @mike-winberry is working this: https://github.com/defenseunicorns/UnicornUI/issues/86 to see if docs can just be inside of Zarf and there are other options we should explore (including Kiwix which we experimented with a while back: https://github.com/defenseunicorns/zarf/tree/example/kiwix) in addition to the more traditional md to docs generators.

The biggest thing will be offline support most likely since our primary deploy persona (Ashton) is usually less tech savvy, and won't always have internet access.
