### ISSUE TITLE
Cleanup OCI Image Config creation

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/zarf#1434]
### Describe what should be investigated or refactored

`src/pkg/packager/publish.go` has a `generateManifestConfig` function that _could_ be modified. In essence it creates a OCI compliant Image Manifest Config when pushing Zarf packages as OCI Images. This config is not used and is pretty pointless (but is a requirement to create image manifests). If we wanted to consume this config and use it for Zarf things, it would need to be expanded and fleshed out.

### Links to any relevant code

https://github.com/defenseunicorns/zarf/pull/1423#discussion_r1136286097

### Additional context
Add any other context or screenshots about the technical debt here.

**Comment by Racer159** [comment]
With `generateManifestConfig` refactored was there more you wanted to do with this issue?
