### ISSUE TITLE
UX Test: SetVariables to add functionality of lists, custom bulions, types, etc.

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1443]
## Driving Questions ##
*What are we hoping to validate?*

- How might we expand the functionality of SetVariable to support lists, custom bullion (ex. for hiding sensitive information), file type (ex. JSON, YAML)
- Does the proposed changes from setvariable (string) to setVariables (array) add value?
- Does the proposed command name setVariables make sense to users?
- Can we replace current feature setVariable with new feature setVariables without removing cabiablies.

## Testing Plan ##
User personas: Package Creator

- [x] Create mocks of solution
- [x] Create Maze test
- [ ] Run Maze test (moderated) with 3-5 package creators

## Additional context ##
*Screenshot or link to what needs to be tested*
<img width="461" alt="Screenshot 2023-03-16 at 2 28 41 PM" src="https://user-images.githubusercontent.com/92826525/225732293-8718b63f-a354-4d10-bb65-b21d87db9f85.png">
<img width="500" alt="Screenshot 2023-03-16 at 2 28 22 PM" src="https://user-images.githubusercontent.com/92826525/225732313-a79d6bc4-5f66-4ebe-a638-3f13f5116ae4.png">
<img width="482" alt="Screenshot 2023-03-16 at 2 28 32 PM" src="https://user-images.githubusercontent.com/92826525/225732316-ca394cf4-63c6-4b5d-987e-433ab818433c.png">

Related to issue #1413 

Users are reported the need to be able to keep secrets that are outputting during setVariables command from being expressed in the log output. Additionally, there are use cases where a user may need to set multiple variables for the same command - this soltuion allows for both. 

[Add video/pictures of current flow]

<img width="446" alt="Screenshot 2023-03-16 at 2 31 35 PM" src="https://user-images.githubusercontent.com/92826525/225732851-f92a17f4-c314-4b39-be6f-36e863b51467.png">

## Link to Test ##
https://app.maze.co/maze-preview/mazes/150455954

**Comment by Madeline-UX** [comment]
from @Racer159 
<img width="519" alt="Screenshot 2023-03-16 at 2 32 16 PM" src="https://user-images.githubusercontent.com/92826525/225732979-d7e5949e-32c4-42ca-bd31-c2f361ab8652.png">

**Comment by Racer159** [comment]
Initial implementation in https://github.com/defenseunicorns/zarf/pull/1474
