### ISSUE TITLE
zarf registry login hangs indefinitely with --password-stdin flag

### ISSUE THREAD

**Issue by mikevanhemert** [defenseunicorns/zarf#1444]
### Environment
Device and OS:
* On-prem customer server with Ubuntu 22.04.2 LTS
* System76 Darter Pro with Pop!_OS 22.04 LTS

App version: v0.25.0-rc1
Kubernetes distro being used: n/a
Other:

### Steps to reproduce
1. Attempt zarf registry login with valid credentials to `registry1.dso.mil`
    ```bash
    zarf  tools registry login -u [username] --password-stdin registry1.dso.mil -l debug
    # enter your password
    ```

### Expected result
Zarf prompts for password or entering password immediately proceeds to registry login

### Actual Result
Zarf hangs with no indication of success, failure, next steps, etc.

### Visual Proof (screenshots, videos, text, etc)
n/a

### Severity/Priority
Low

### Additional Context
Zarf registry login with valid credentials and the `-p` flag is successful
```bash
zarf tools registry login -u [username] -p [password] registry1.dso.mil -l debug
2023/03/16 14:17:22 logged in via /home/[system username]/.docker/config.json
```

**Comment by Racer159** [comment]
The zarf tools registry login command is from crane and pulls the password from a pipe like:

```
echo $MYPASSWORD | zarf  tools registry login -u [username] --password-stdin registry1.dso.mil
```

The closest issue I could find upstream is this: https://github.com/google/go-containerregistry/issues/718
