### ISSUE TITLE
@latest-rc is broken in brew

### ISSUE THREAD

**Issue by corang** [defenseunicorns/zarf#1457]
When trying to run `brew install zarf@latest-rc` brew responds with an error about an invalid class name:
```
Error: No available formula with the name "zarf@latest-rc".
In formula file: /home/linuxbrew/.linuxbrew/Homebrew/Library/Taps/defenseunicorns/homebrew-tap/zarf@latest-rc.rb
Expected to find class Zarf@latestRc, but only found: ZarfATlatestRc.
```

**Comment by corang** [comment]
My guess is that the `-` is being stripped out when the function is created? I don't know much about brew tbh

**Comment by Racer159** [comment]
Not sure that we necessarily want to (or have in the past) supported this.  RCs aren't meant to be installed and ran continuously over time by normal users - and while brew provides a function for updating them - I am not sold on implementing this currently. (happy to reopen to discuss further however).
