### ISSUE TITLE
FAQ re-design

### ISSUE THREAD

**Issue by Jessy-Morris** [defenseunicorns/zarf#1460]
### Is your feature request related to a problem? Please describe.
FAQ section could become too long/hard to pinpoint specific information due to the lack of collapsible content. It could be difficult to navigate in the future if more FAQs are added.   
### Describe the solution you'd like
Incorporate an accordion-style FAQ section to make navigating and finding information easier for readers.

### Additional context
Something along the lines of this reference photo: 
![image](https://user-images.githubusercontent.com/123977818/226688771-736c7d4b-bd3c-4378-80c2-d229ee07f033.png)

**Comment by Racer159** [comment]
@Jessy-Morris here is an older issue related to this for reference: https://github.com/defenseunicorns/zarf/issues/1134
