### ISSUE TITLE
Extracting Individual Components of a Composed / Published OCI package

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/zarf#1553]
### Is your feature request related to a problem? Please describe.
When consuming composed OCI packages that contain different component types (i.e. charts, images, files, sboms, etc.) in the early stages of a CI/CD process, I would like the ability to extract a single component of that package (i.e. images or charts or files).

### Describe the solution you'd like
Extract objects in a component of an OCI package that has been published in order to handle the types differently throughout a CI/CD process.

### Describe alternatives you've considered
Publishing artifacts independently and correlating them in a matrix / table

**Comment by Racer159** [comment]
@ntwkninja if you have time to chat about this would love to learn more about it - it isn't clear to me exactly what is wanted from this?

**Comment by RothAndrew** [comment]
Not following. What was my involvement with this?
