### ISSUE TITLE
Use ECR as an external registry during 'Zarf Init'

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#1594]
### Is your feature request related to a problem? Please describe.
**As** Ashton **I want** an easy way to deploy Zarf configured with ECR as an external registry **so that** I can take advantage of the HA benefits of running a registry out of the cluster in AWS.

### Describe the solution you'd like

- **Given** I have a fresh EKS cluster and IAM access to ECR
- **When** I run `zarf init` with an ECR registry domain configured
- **Then** Zarf successfully initializes the cluster
- **And** Creates the ECR repositories for me
- **And** _(optional for this issue)_ Creates a mechanism to keep the `private-registry` credentials up to date.

### Additional context
ECR has a few 'unique' quirks that make it difficult to use as an external registry at the moment.

1. ECR credentials are only valid for 12 hours, so something within clusters would have to refresh the zarf image pull secrets so that the kubelet is able to authenticate and pull images from ECR during package deployments.

2. ECR registries do not have the ability to 'push to create' repositories that do not exist yet. Since Zarf packages will be pushing all sorts of images into the registry when the package is being deployed, this is a pretty big blocker.

Using ECR as an external registry would be really useful for a lot of people so we should implement some solution to the two issues above.

**Comment by Racer159** [comment]
This might be something to look into:

https://cloud-provider-aws.sigs.k8s.io/credential_provider/
https://kubernetes.io/docs/tasks/administer-cluster/kubelet-credential-provider/

**Comment by Racer159** [comment]
Ideas:

This could be solved with something like a preDeploy hook and the ability to inspect a package for a list of images and repos. (would keep things out of the zarf code).

We could also have a long running pod that we call out to in a standardized way

We could include AWS specific code inside of Zarf.

**Comment by ntwkninja** [comment]
> 1. ECR credentials are only valid for 12 hours, something within clusters would have to refresh the zarf-secret so that agent is able to correctly redirect push/pull requests to the image registry

We may want to document setting up an IAM role (that can be assumed) as a pre-requisite and have zarf be opinionated to use assume-role so it doesn't need to worry about static creds and rotations

**Comment by lucasrod16** [comment]
Noting that the solution for this will be implemented in this repo:
https://github.com/defenseunicorns/zarf-init-aws
