### ISSUE TITLE
Docs Update - Add SBOM page and updates to SBOM docs

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1595]
### Current
*Is your feature request related to a problem? Please describe.*

Information about SBOM is on the SBOM UI Page. This seems misplaced and like it should be up somewhere in the "Package Create" section. There is much more to the SBOM than just viewing it on deployment. The current SBOM UI page describes what SBOM is in detail instead of just focusing on the SBOM UI features. 

### Describe the solution you'd like

Docs page for all information on SBOMs in Zarf - under package create
- single source of SBOM information 
- Tool used to generate
- Structure/file type supported (security compliance)
- Security reference/compliance
- How to use/import to other tools
- How to save SBOM locally
- How SBOM is updated
- link to SBOM UI  page (UI Section)
- Links to SBOM commands pages (CLI commands section)

### Additional context

![image](https://user-images.githubusercontent.com/3977569/236316383-3cd83174-60b1-47d8-92c6-4949a311e3c1.png)

**Comment by Madeline-UX** [comment]
@Racer159 Interested in your thoughts on this, given your work on the SBOM tools

**Comment by Racer159** [comment]
Steps:

- [ ] UI Dashboards moved under deploy a zarf package
- [ ] New SBOM page under create a zarf package
- [ ] Update Overview and README links for above feature split

**Comment by Racer159** [comment]
These could be tied together as well: https://github.com/defenseunicorns/zarf/issues/1387
