### ISSUE TITLE
Add Package commands to deployed package context menu

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1606]
## User Story ##

As Ashton, I would like to be able to view the yaml package definitions for a package so that I can get more technical information about what is deployed.

Each command has it's own story, this issue is just for adding the menu component

CLI command: zarf inspect

Acceptance Criteria

Given - the user has packages deployed in their cluster
When - selects view code... from the actions menu
Then - Open a drawer that shows the Zarf.yaml for the package.
DESIGN THINGS..
And - Return user to previous screen

## Designs ## 

<img width="382" alt="Screenshot 2023-04-06 at 4 22 14 PM" src="https://user-images.githubusercontent.com/92826525/230496941-57445d1b-c992-4682-8c6b-d6d72714ca70.png">

**Comment by Racer159** [comment]
@Madeline-UX this one needs a design too
