### ISSUE TITLE
zarf tools kubectl version returns error code

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1614]
### Environment
Device and OS: OSX
App version: v0.25.2
Kubernetes distro being used: v1.23.16
Other:

When creating a pre-flight check for the kubernetes version, the zarf tools kubectl command was returning an error. It looks like the clientVersion is not getting set in a way the command likes, potentially based on how its being imported and used by Zarf tools.

### Steps to reproduce
Run the following:

```shell
$ zarf tools kubectl version --short        
Flag --short has been deprecated, and will be removed in the future. The --short output will become the default.
Client Version: v0.0.0-master+$Format:%H$
Kustomize Version: v4.5.7
Server Version: v1.23.16-eks-48e63af
error: could not parse pre-release/metadata (-master+$Format:%H$) in version "v0.0.0-master+$Format:%H$"
$ echo $?
1
```

### Expected result
For the return code for the command `zarf tools kubectl version --short ` to be zero.
### Severity/Priority

Simple work around by:

```yaml
  - name: one
    required: true
    actions:
      onDeploy:
        after:
        - cmd: "./zarf tools kubectl version --short || true"
          setVariable: OUTPUT
```

**Comment by Racer159** [comment]
https://github.com/defenseunicorns/zarf/pull/1624 - this will actually be resolved in 1624
