### ISSUE TITLE
Nightly testing of integration points (Azure)

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1615]
### Describe what should be investigated or refactored
Zarf integrates with many external services and each of these has its unique *ilities that are likely to change over time. We should be checking against the following:

 -  A wide range of kubernetes cluster versions and distros
 -  A wide range of git repositories (for flux deployments)
 -  A wide range of image registries (for deployments and zarf package publishing/deploying)

### Links to any relevant code
https://github.com/defenseunicorns/zarf/tree/main/.github/workflows

### Additional context
This is the Azure version of this issue and focuses on AKS and ACR for deployment and ACR for package publish (see #1407)

**Comment by Noxsios** [comment]
Since GHCR is hosted on Azure (pretty sure), Github/GHCR tests should also happen in this PR.

First one to test: https://github.com/defenseunicorns/zarf/issues/1677, pulling unauthenticated from GHCR

**Comment by schristoff-du** [comment]
At this time, we aren't seeing enough issues with Azure to commit to creating & maintaining an Azure E2E test.
