### ISSUE TITLE
`zarf prepare find-images` should modify the `zarf.yaml`

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/zarf#1651]
### Is your feature request related to a problem? Please describe.

Currently `prepare find-images` will only print images to the terminal.

I propose this operation be able to directly mutate the `zarf.yaml`'s component definitions to add / remove images. This can be primarily an interactive CLI where users choose `y/n` to add / remove an image from a component and the `--confirm` flag will bypass these checks. This will aid in CI pipeline checks of `zarf.yaml`'s as you could do the following to check if images have been added/removed:

```sh
$ zarf prepare find-images
$ git diff HEAD zarf.yaml
```

**Comment by fallenpixel** [comment]
Just a thought  from the community, something that cleanly outputs the image list would also be useful. I'm thinking that using `:r !zarf prep find-images` in vim would be more useful.

**Comment by Noxsios** [comment]
Closing this as out of scope currently. The main use of `zarf prepare find-images` is not during CI. And most teams / users are using tools like release-please, or renovate to keep track and update their image references accordingly.  

Zarf's current `renovate.json` for reference: https://github.com/defenseunicorns/zarf/blob/main/renovate.json
