### ISSUE TITLE
Remove support for publishing packages as `artifact.manifest` mediatypes

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/zarf#1659]
### Describe what should be investigated or refactored

The OCI spec has removed the `artifact.manifest` spec in favor of using the `image.manifest` for everything due to registry support and there not being a good enough reason to have another entire spec. https://github.com/opencontainers/image-spec/pull/999

As such, Zarf should remove support for this, as very few registries support `artifact.manifest` anyways and none will support in the future.

**Comment by Noxsios** [comment]
Refactoring the manifest's image config should also take place in this PR: https://github.com/defenseunicorns/zarf/issues/1434

**Comment by Racer159** [comment]
This is blocking us from updating oci spec and crane - we could pull these local like oras did but might as well rip off the bandaid.

**Comment by Noxsios** [comment]
Bandaid ripped w/ https://github.com/defenseunicorns/zarf/pull/1469/commits/ceb6da1f69c8b12dfe1d8ec5ace38da6003517b6 @Racer159

**Comment by Noxsios** [comment]
closed by #1376
