### ISSUE TITLE
"Brew for DevOps"

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#167]
User feature request, Details TBD - Would love to see a "registry" of common packages that one can deploy, with the ability to host a private registry (because air gap)

**Comment by RothAndrew** [comment]
> asking for a place to keep / host / serve pre-built versions of them
this ^

Just like I can do `brew install kubectl` they'd like `zarf deploy doom`... or something to that effect

**Comment by btlghrants** [comment]
Right, gotcha.  This is different from "components" because they're all about how the "Zarf Cluster" runs, not so much about the things that "the Zarf cluster" would serve for end users.

**Comment by btlghrants** [comment]
Seems like a cool idea... but also like it'll require a _lot_ of storage space since we'd basically be storing/re-hosting (potentially) a bunch of binaries + container images + git repositories + etc.  :man_shrugging:

**Comment by RothAndrew** [comment]
The MVP for this could be just the ability to host your own private registry, and then decide if it is worth us hosting a public one (or getting someone else to do it)

**Comment by RothAndrew** [comment]
But, we can already do a `zarf package deploy` on remote assets, so that may be sufficient already for this.

**Comment by jeff-mccoy** [comment]
Closing this older issue now that we have a lot of new capability that with #550 and #621 are merged in.
