### ISSUE TITLE
Big Bang YOLO mode support

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1670]
### Is your feature request related to a problem? Please describe.
Would like to have support for YOLO mode added to the Big Bang extension to allow online versions of big bang to be deployed without images or repos.

### Describe the solution you'd like
Passing the YOLO mode package metadata flag to the bb extension so that it knows not to include images.

### Describe alternatives you've considered
We could have a new extension key but this would require more work for what is already a global package key.

### Additional context
This was requested from our k8s slack channel: https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1683059584720439?thread_ts=1682704735.709779&cid=C03B6BJAUJ3

**Comment by willswire** [comment]
Our use-case for such a feature would enable us to have a faster build time for our low-side, internet-connected environment prior to pushing the same package to an air-gapped network.

I would say YOLO-mode (or some other form of an internet-connected toggle switch) for the Big Bang extension is likely our most critical request for Zarf.

**Comment by willswire** [comment]
Package create and deploy working with BB extension and YOLO mode enabled [here](https://github.com/willswire/zarf/tree/bigbang-yolo-mode). Still need to test functionality and probably refactor code better.

**Comment by Noxsios** [comment]
Closed by #1681
