### ISSUE TITLE
Make k3s installer stages completely generic to the packaging system

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#17]
Removing all hard-coded elements of K3s will enable transparent support for alternative cluster technologies including K3d to make development and testing simpler.  This will likely require #23 to be implemented.

---

Migrated from https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/31

**Comment by RothAndrew** [comment]
@jeff-mccoy is what you are calling "k8s native apply" or something else?

**Comment by jeff-mccoy** [comment]
That will block this, but the code and work are still independent.  This has to do with cluster init.

**Comment by RothAndrew** [comment]
@jeff-mccoy will #237 close this?

**Comment by RothAndrew** [comment]
@jeff-mccoy will this be resolved when #237 merges?

**Comment by jeff-mccoy** [comment]
Yes
