### ISSUE TITLE
Flux Example - Flux deployment + Utility Cluster on same node

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#170]
As a user of Zarf and Flux I want a Zarf package that deploys Flux to the same cluster as my Utility Cluster, so that i can deploy flux easily without depending on Registry1 being up and without needing to run a separate Utility Cluster

Acceptance Criteria:
- New Zarf example `flux-single-node` (or some other appropriate name) exists
- It packages the Flux manifests and images needed to run flux in a single-node airgapped cluster

Nice-to-have:
- The manifests are pulled from [Repo1](https://repo1.dso.mil/platform-one/big-bang/bigbang/-/tree/master/base/flux) so they don't need to be frequently updated

**Comment by jeff-mccoy** [comment]
Closing this stale issue, can be re-opened if the community determines it's still needed.
