### ISSUE TITLE
Better error message when using old kubernetes version

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1704]
### Describe what should be investigated or refactored
A clear and concise description of what should be changed/researched. Ex. This piece of the code is not DRY enough [...]

The warning/error message that you get when you try to `zarf init` on an older version of kubernetes is not very helpful.

Potential solutions:
* Expand compatibility so that Zarf does work on older versions of kubernetes
* Check k8s version as a preflight check and bail out if it isn't a supported version
* Improve the error message so that the user understands why the init is not working (they are using an incompatible version of kubernetes)

### Additional context
Add any other context or screenshots about the technical debt here.

On K8s 1.21:

![image](https://github.com/defenseunicorns/zarf/assets/16000938/f5e5e126-33e6-4765-beef-2244cd777d0d)

![image](https://github.com/defenseunicorns/zarf/assets/16000938/fde14c0d-a107-4466-9ca2-c1f25844dfb0)

**Comment by Racer159** [comment]
Marking this as complete since the error messaging here has been improved more globally
![image](https://github.com/defenseunicorns/zarf/assets/3977569/a944a2da-a715-4f46-b4f4-2aaf21f04914)
