### ISSUE TITLE
Flux Example - Prod Flux Deploy

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#171]
As a user of Zarf and Flux I want a Zarf package that resembles a production deployment of flux to a separate cluster than my Utility Cluster, so that I have something to use as a reference when trying to do a prod Flux deployment in my own environment.

Acceptance Criteria:
- New Zarf example `flux-resembles-prod` (or some other appropriate name) exists
- Has 1 Zarf package that just loads the images into a utility cluster and another one (or some other method if #16 isn't ready yet) that uses the Utility Cluster images to deploy flux in a different cluster

Nice-To-Have:
- Pulls the manifests from [Repo1](https://repo1.dso.mil/platform-one/big-bang/bigbang/-/tree/master/base/flux) so they don't have to be frequently updated

**Comment by jeff-mccoy** [comment]
Closing this stale issue, can be re-opened if the community determines it's still needed.
