### ISSUE TITLE
New CRC Hash not being calculated the same?

### ISSUE THREAD

**Issue by charlescva** [defenseunicorns/zarf#1742]
### Environment
Device and OS: Virtualbox 6.1 with Guest OS: RHEL 8.7
App version: zarf_v0.26.4_Linux_amd64
Kubernetes distro being used: k3s version v1.24.1+k3s1 (0581808f)
Other: go version go1.18.1

### Steps to reproduce
1. run zarf package create to create a Zarf .ZST Package that includes Images Component and related Charts Component within the zarf.yaml. Example:
```
components:
 - name: required-images
    description: "All images for required services"
    images:
      - some.registry.com/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5
      - some.registry.com/ironbank-mirror/ironbank/opensource/strimzi/kafka:0.28.0-kafka-3.1.0
      - some.registry.com/ironbank-mirror/ironbank/opensource/strimzi/operator:0.28.0
 
 - name: istio-operator
    description: Installs the istio-operator
    charts:
      - url: https://wiremind.github.io/wiremind-helm-charts
        name: istio-operator
        releaseName: istio-operator
        version: 1.12.0
        namespace: istio-operator
        valuesFiles:
          - ./services/system/istio-operator/values.yaml

```
Once the package is created, copy to target system for testing...

3. Run Zarf Init, Y - k3s, N - logging, N - gitea
4. Run Zarf package deploy <package.tar.zst>

### Expected result

The docker registry running on the local k3s cluster has the appropriate images and tags from the images component, that allow the subsequent chart components to successfully complete/

### Actual Result

Component Deployment 'hangs' with `WARNING: Unable to complete helm chart install/upgrade, waiting 10 seconds and trying again.`

Looking at the kubectl describe <pod> the tag referenced does not match the tag that was created for the images component with the appended CRC hash.

Inside the local k3s registry, the two tags exist: "1.12.5" and "1.12.5-zarf-3644333575"
```
[root@localhost ~]# curl http://zarf-push:z7UCjyyUdM5I~yJUHFsk6MRU@127.0.0.1:31999/v2/ironbank-mirror/ironbank/opensource/istio/operator/tags/list
{"name":"ironbank-mirror/ironbank/opensource/istio/operator","tags":["1.12.5-zarf-3644333575","1.12.5"]}
```
However, the helm chart deployment is attempting to pull "1.12.5-zarf-1021806520"

Since "1.12.5-zarf-1021806520" != "1.12.5-zarf-3644333575"  The helm deployment fails.

### Visual Proof (screenshots, videos, text, etc)

```
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  9m38s                   default-scheduler  Successfully assigned istio-operator/istio-operator-8666dd87cf-22fn2 to localhost.localdomain
  Normal   Pulling    8m7s (x4 over 9m38s)    kubelet            Pulling image "127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5-zarf-1021806520"
  Warning  Failed     8m7s (x4 over 9m38s)    kubelet            Failed to pull image "127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5-zarf-1021806520": rpc error: code = NotFound desc = failed to pull and unpack image "127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5-zarf-1021806520": failed to resolve reference "127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5-zarf-1021806520": 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5-zarf-1021806520: not found
  Warning  Failed     8m7s (x4 over 9m38s)    kubelet            Error: ErrImagePull
  Warning  Failed     7m54s (x6 over 9m38s)   kubelet            Error: ImagePullBackOff
  Normal   BackOff    4m26s (x21 over 9m38s)  kubelet            Back-off pulling image "127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5-zarf-1021806520"
```

### Severity/Priority
Blocker for me

### Additional Context
To quick fix that single component, I ran the following commands and with a matching tag in the registry, the stalled component completed in the zarf package deploy script.  
```
# docker pull 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5-zarf-3644333575
# docker tag 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5-zarf-3644333575 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5-zarf-1021806520
# docker push 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5-zarf-1021806520
```

However, i have several components and this manual process is not viable for me.  I cannot change the helm deployment via upgrade in the background, because there is another operation in progress

```
[root@localhost istio-operator]# helm -n istio-system upgrade istio-operator charts/istio-operator-1.12.0.tgz -f values/istio-operator-1.12.0-0
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
```

**Comment by Noxsios** [comment]
@charlescva What is the output of `zarf prepare find-images`?  This should auto discover images from your Helm charts and values files.  The CRC reference is derived from the full image URL, so an image CRC from `registry1.dso.mil/nginx` will not match the image CRC from say `docker.io/nginx`.

**Comment by Noxsios** [comment]
Your first component will load the specified images into the internal registry, but your second component most likely is looking for images from a public registry (like docker or ghcr). `zarf prepare find-images` will tell you what image references are used, and how you can update your `zarf.yaml` to pull them.  I would use your `values.yaml` file to update the image references from that chart to use `some.registry.com/ironbank-mirror/...` image references.

**Comment by charlescva** [comment]
It may be worth noting, that when I `zarf package deploy` there is no internet connection.  Where is the Go code that calculates the CRC when processing a helm chart to execute a package deployment?  And what is the input to the CRC function when executing a package create? I'm curious to have a look.

**Comment by charlescva** [comment]
Similar but different issue with 0.25.2
CRC doesnt match, but breaks the image name vs. the image tag

```
Use "zarf tools registry [command] --help" for more information about a command.
[root@localhost ~]# zarf tools registry catalog
  ✔  Creating port forwarding tunnel at http://127.0.0.1:36993/v2/_catalog                                                                                                
defenseunicorns/zarf/agent
ironbank-mirror/ironbank/bitnami/postgres/postgresql11
ironbank-mirror/ironbank/bitnami/postgres/postgresql11-1654791486
ironbank-mirror/ironbank/bitnami/redis
ironbank-mirror/ironbank/bitnami/redis-401942053
ironbank-mirror/ironbank/kiwigrid/k8s-sidecar
ironbank-mirror/ironbank/kiwigrid/k8s-sidecar-2266270376
ironbank-mirror/ironbank/opensource/coreos/kube-state-metrics
ironbank-mirror/ironbank/opensource/coreos/kube-state-metrics-2306844272
ironbank-mirror/ironbank/opensource/grafana/grafana
ironbank-mirror/ironbank/opensource/grafana/grafana-996598607
**ironbank-mirror/ironbank/opensource/istio/operator
ironbank-mirror/ironbank/opensource/istio/operator-3644333575**
ironbank-mirror/ironbank/opensource/istio/pilot
ironbank-mirror/ironbank/opensource/istio/pilot-1795317328
ironbank-mirror/ironbank/opensource/istio/proxyv2
ironbank-mirror/ironbank/opensource/istio/proxyv2-765764439
ironbank-mirror/ironbank/opensource/keycloak/keycloak
ironbank-mirror/ironbank/opensource/keycloak/keycloak-3117259472
ironbank-mirror/ironbank/opensource/prometheus/alertmanager
ironbank-mirror/ironbank/opensource/prometheus/alertmanager-4240119283
ironbank-mirror/ironbank/opensource/prometheus/node-exporter
ironbank-mirror/ironbank/opensource/prometheus/node-exporter-441296841
ironbank-mirror/ironbank/opensource/prometheus/prometheus
ironbank-mirror/ironbank/opensource/prometheus/prometheus-3650373021
ironbank-mirror/ironbank/opensource/prometheus-operator/prometheus-config-reloader
ironbank-mirror/ironbank/opensource/prometheus-operator/prometheus-config-reloader-3390320267
ironbank-mirror/ironbank/opensource/prometheus-operator/prometheus-operator
ironbank-mirror/ironbank/opensource/prometheus-operator/prometheus-operator-3857549989
ironbank-mirror/ironbank/opensource/strimzi/kafka
ironbank-mirror/ironbank/opensource/strimzi/kafka-2354209213
ironbank-mirror/ironbank/opensource/strimzi/operator
ironbank-mirror/ironbank/opensource/strimzi/operator-1783982026
ironbank-mirror/ironbank/opensource/tchiotludo/akhq
ironbank-mirror/ironbank/opensource/tchiotludo/akhq-2237172729
library/registry
library/registry-2874453864

[root@localhost ~]# kubectl describe pods istio-operator-8666dd87cf-k2bgp -n istio-operator | grep "not found"
  Warning  Failed     14m (x4 over 15m)   kubelet            Failed to pull image "127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator-1021806520:1.12.5": rpc error: code = NotFound desc = failed to pull and unpack image "127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator-1021806520:1.12.5": failed to resolve reference "127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator-1021806520:1.12.5": 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/**operator-1021806520:1.12.5: not found**
```

**Comment by Noxsios** [comment]
@charlescva the CRC behavior was changed in release [v0.26.0](https://github.com/defenseunicorns/zarf/releases/tag/v0.26.0) with the CRC being appended to the image refereence, not the name. I would upgrade your version of zarf, and re-initialize your cluster + repackage and redeploy.

> "i do not see any calculated CRC in the ouput"

correct, the CRC is derived from the image name, as a user you do not control it directly.

> "I'm not sure I follow why the component is most likely looking for images from a public registry."

Image references are intercepted by the zarf agent (a mutating webhook installed in the cluster during `zarf init`) to point to the internal registry. So `docker.io/library/nginx` transparently becomes `127.0.0.1:31999/library/nginx`.

Make sure that the images referenced in your `images:` key match _exactly_ within your `values.yaml` / chart. If the names+tags do not exactly match, you will receive a CRC mismatch.

**Comment by Racer159** [comment]
As an additional add here is where Zarf makes those CRC32s: 

https://github.com/defenseunicorns/zarf/blob/49835054fcb6411eb7405409107923cf316f8b9d/src/internal/packager/images/push.go#LL101C38-L101C38
https://github.com/defenseunicorns/zarf/blob/main/src/pkg/transform/image.go#L26

This is done dynamically on deploy based on the image name given in the `zarf.yaml` in order to provide backwards compatibility with older Zarf packages (built on older Zarf versions).

One thing to make sure of though is that the Zarf Agent version (the agent pod's images in cluster) and the Zarf CLI version match each other - the Zarf CLI as of v0.26.0 will do this check and warn when deploying interactively.  Based on the `ImagePullBackoff` error you have it looks like you have a `v0.26.0+` Zarf agent which will require the use of a `v0.26.0+` Zarf CLI (which will still be able to deploy a `v0.25.2` Zarf package).

Also on `zarf prepare find-images` that allows you to see the image as it would be pulled and placed in the `zarf.yaml` to later be mutated with a CRC32 and pushed to the airgap registry by the above code.

**Comment by Racer159** [comment]
Also because this is the istio-operator it is likely that it has an internal image reference that Zarf cannot interrogate. (since operators often hide their images inside).

The values file could be useful to debug here since it looks like that helm chart uses `hub` and `tag` for its overrides of the image.

**Comment by Racer159** [comment]
Another way to look at things would be to look at the `Deployment` that defines these pods since Zarf won't touch it that would contain the pre-modified image reference for comparison with the `zarf.yaml`

**Comment by charlescva** [comment]
@Racer159 @Noxsios 
Thanks both for taking the time to review/respond.

I understand it is best to use the same Zarf CLI for package as used for deploy, and I am ensuring that I have been consistent there.

For Terminology describing the element(s) that are passed to the CRC32 hashing algorithm, I feel like I'm using terminology that may be different?  My understanding from https://docs.docker.com/engine/reference/commandline/tag/#description  which i also understand is different than the OCI spec supporting more than 2 slash separated components, which i use, for example, `harbor.mydomain.com/ironbank-mirror/ironbank/opensource/tchiotludo/akhq`

- harbor.mydomain.com is the registry
- harbor.mydomain.com/ironbank-mirror/ironbank/opensource/tchiotludo/akhq is the (image) name
- 0.1.0 is the tag (name)

What I was saying earlier, is that in my original post, using 0.26 I saw a mismatch in the CRC under the tag:
`harbor.mydomain.com/my-image:0.1.0-zarf-12345678` vs. `harbor.mydomain.com/my-image:0.1.0-zarf-87654321`

When I downgraded to 0.25.2, I saw a mismatch in the CRC under the "Image Name"
`harbor.mydomain.com/my-image-zarf-12345678:0.1.0` vs. `harbor.mydomain.com/my-image-zarf-87654321:0.1.0`

That being said, i only just ran `zarf tools registry catalog` on the 0.25.2 test, so maybe in my original post I should have done that instead of using curl, and i would have seen images with the CRC appended to the name as well.

With regard to the zarf agent intercepting the webhook, i was aware and was wondering if that had something to do with the CRC that is generated during the chart component deployment?  Aka, the package is being created with `harbor.mydomain.com` and then the deployment is using `127.0.0.1:33391` and so the CRC mismatch was because the Registry URL was different.

However, after double checking my values.yaml for the istio operator, it looks like it may have been an istio/operator vs istio-operator issue in the values:

```
# git diff services/system/istio-operator/values.yaml
diff --git a/services/system/istio-operator/values.yaml b/services/system/istio-operator/values.yaml
index 8aa2234..1bd8919 100644
--- a/services/system/istio-operator/values.yaml
+++ b/services/system/istio-operator/values.yaml
@@ -1,3 +1,3 @@
 operatorNamesapce: istio-operator
-hub: 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio
+hub: 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator
 tag: 1.12.5
```

So my `values.yaml` for istio-operator has the same  value in 'hub' and 'tag' as what is defined in the zarf.yaml:
```
[root@localhost istio-operator]# zarf tools registry catalog | grep istio/operator
  ✔  Creating port forwarding tunnel at http://127.0.0.1:42657/v2/_catalog       (1s)
ironbank-mirror/ironbank/opensource/istio/operator
ironbank-mirror/ironbank/opensource/istio/operator-3116871966
[root@localhost istio-operator]# cat values.yaml 
operatorNamesapce: istio-operator
hub: 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator
tag: 1.12.5
```

So, I have cleared /tmp/zarf-* and ~/.zarf-cache, (rm -rf)
Ensured I'm using 0.25.2, ran zarf package create (no issues)
Ran zarf init (specifying k3s only)
zarf package deploy (specified package i just built, no other packages in CWD)

Still I have these two images loaded in the Zarf Registry:
```
ironbank-mirror/ironbank/opensource/istio/operator
ironbank-mirror/ironbank/opensource/istio/operator-3116871966
```

Kubectl Deployment (pre-modified Image reference):
```
Pod Template:
  Labels:           name=istio-operator
  Service Account:  istio-operator
  Containers:
   istio-operator:
    Image:      127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator/operator:1.12.5
```

Kubectl Pod Event Error:
```
127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator/operator-372805693:1.12.5: not found
```

After looking at functions like the ones found in, https://github.com/defenseunicorns/zarf/blob/49835054fcb6411eb7405409107923cf316f8b9d/src/pkg/transform/image.go#L26

I'm thinking there is an issue with the values.yaml and how the CRC is computed.  Looking at our values.yaml files, I'm seeing:
```
hub: 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator
tag: 1.12.5
```
and
```
image:
  repository: 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/tchiotludo/akhq
  tag: "0.21.0"
```
or
```
image:
  repository: 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/keycloak/keycloak
  tag: "16.1.1"
```

So I'm not sure if maybe the syntax of using `hub` or what is causing an issue.  But I'm now seeing like, bizarre results with the >2 slash separated components, so I'm going to tinker with the values.yaml and make a CRC32 function I can run externally to do some validation before re-running the time consuming rebuild of package, try again pattern.

Thanks again for all the help.

**Comment by Racer159** [comment]
I think I see the issue - `hub` should use whatever the upstream value is.

i.e.

```
hub: 127.0.0.1:31999/ironbank-mirror/ironbank/opensource/istio/operator
```

should be

```
hub: harbor.mydomain.com/ironbank-mirror/ironbank/opensource/istio/operator
```

to allow the CRC32 to be calculated the same between the deployment manifest and the `zarf.yaml`

**Comment by charlescva** [comment]
Yea, I'm getting there... I wrote this script: 
```
package main

import (
    "fmt"
    "hash/crc32"
    "os"
    "bufio"
    "strconv"
)

func main() {

    readFile, err := os.Open("/tmp/strings")
      if err != nil {
        fmt.Println(err)
    }
    fileScanner := bufio.NewScanner(readFile)
     fileScanner.Split(bufio.ScanLines)
      for fileScanner.Scan() {
        fmt.Println(fileScanner.Text() + " HAS CRC32: " + strconv.FormatUint(uint64(GetCRCHash(fileScanner.Text())), 10))
    }
      readFile.Close()
}

// GetCRCHash returns the computed CRC32 Sum of a given string
func GetCRCHash(text string) uint32 {
	table := crc32.MakeTable(crc32.IEEE)
	return crc32.Checksum([]byte(text), table)
}
```
Then pasted all my possible variations into /tmp/strings and ran it.  I found that the CRC being generated in the Zarf repo is based on the string defined in my zarf.yaml

So the issue is how the values.yaml CRC is generated, which I now see will never match what is in zarf.yaml for the packaging!

Gotta run, but will re-test tomorrow.

**Comment by charlescva** [comment]
Update:
**zarf.yaml** - Used when running `zarf package create`
```
  - name: istio-operator
    description: Installs the istio-operator
    images:
      - harbor.mydomain.com/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5
    charts:
      - url: https://wiremind.github.io/wiremind-helm-charts
        name: istio-operator
        releaseName: istio-operator
        version: 1.12.0
        namespace: istio-operator
        valuesFiles: 
          - ./services/system/istio-operator/values.yaml
```

Here is the, `./services/system/istio-operator/values.yaml`
```
operatorNamesapce: istio-operator
image: harbor.mydomain.com/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5
```

I verified the values file is updated in the package that is extracted into /tmp during `zarf package deploy`:
```
[root@localhost zarf-package-fcem]# cat /tmp/zarf-1059059371/components/istio-operator/values/istio-operator-1.12.0-0 
operatorNamesapce: istio-operator
image: harbor.mydomain.com/ironbank-mirror/ironbank/opensource/istio/operator:1.12.5
```

The result still is:
```
  Warning  Failed     2s (x3 over 42s)   kubelet            Failed to pull image "127.0.0.1:31999/istio/operator-4142174219:1.12.0": rpc error: code = NotFound desc = failed to pull and unpack image "127.0.0.1:31999/istio/operator-4142174219:1.12.0": failed to resolve reference "127.0.0.1:31999/istio/operator-4142174219:1.12.0": 127.0.0.1:31999/istio/operator-4142174219:1.12.0: not found
 ```

The CRC Checksum 4142174219 still does not match the one calculated when the Image is pushed into the local/airgapped zarf registry on k3s:
```
[root@localhost zarf-package-fcem]# zarf tools registry catalog | grep istio
  ✔  Creating port forwarding tunnel at http://127.0.0.1:44135/v2/_catalog       (1s)
ironbank-mirror/ironbank/opensource/istio/operator
ironbank-mirror/ironbank/opensource/istio/operator-3116871966
```

My earlier script verified that 3116871966 is the correct checksum for the [REGISTRY/IMAGE] (without the tag).  So the Image Checksum going into the registry does not include the tag (even though the tag is on the image line in my `zarf.yaml`

So even though I have the same exact string in the chart's `values.yaml`  as in my `zarf.yaml`, the new CRC the webhook injects doesnt seem to match what is in the registry.  However, I have not seen the CRC 4142174219 yet, so the checksum produced IS clearly different than what i was getting in the error before, but still doesnt match what is in the registry.

**Comment by Racer159** [comment]
I think this is a separate issue now - `127.0.0.1:31999/istio/operator-4142174219` doesn't have the `ironbank-mirror/ironbank/opensource/istio` namespace which makes me think that this is trying to look for something like https://hub.docker.com/r/istio/operator/tags instead somewhere else in that chart.

**Comment by charlescva** [comment]
The Chart, 
https://github.com/wiremind/wiremind-helm-charts/tree/istio-operator-1.12.0/charts/istio-operator

**Comment by charlescva** [comment]
The Chart does have a default values.yaml using `hub: docker.io`,

```
[root@localhost charts]# pwd
/tmp/zarf-668200519/components/istio-operator/charts
[root@localhost charts]# grep -rl docker *
istio-operator/values.yaml
[root@localhost charts]# cat istio-operator/values.yaml 
hub: docker.io/istio
tag: 1.12.0

# ImagePullSecrets for operator ServiceAccount, list of secrets in the same namespace
# used to pull operator image. Must be set for any cluster configured with private docker registry.
imagePullSecrets: []

# Disabled as of istio-operator 1.12
# operatorNamespace: istio-operator

# Used to replace istioNamespace to support operator watch multiple namespaces.
watchedNamespaces: istio-system
waitForResourcesTimeout: 300s

# Used for helm2 to add the CRDs to templates.
enableCRDTemplates: false

# revision for the operator resources
revision: ""

# Operator resource defaults
operator:
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 50m
      memory: 128Mi

# Additional labels and annotations to apply on the pod level for monitoring and logging configuration.
podLabels: {}
podAnnotations: {}
```

However, I can't generate a hash that matches with what the zarf deploy is using, 4142174219
```
[root@localhost charts]# ~/crc_check 
harbor.<mydomain>.com/ironbank-mirror/ironbank/opensource/istio/operator HAS CRC32: 3116871966
docker.io/istio-operator HAS CRC32: 3625105549
docker.io/istio-operator:1.12.0 HAS CRC32: 2224470027
docker.io/istio:1.12.0 HAS CRC32: 223129544
docker.io/istio HAS CRC32: 636425818
```

The only checksum i can verify is the one appended to the image that is added to the local zarf registry before the deployment is attempted:
`harbor.<mydomain>.com/ironbank-mirror/ironbank/opensource/istio/operator HAS CRC32: 3116871966`

I can see it with the `zarf tools registry catalog` command
```
[root@localhost charts]# zarf tools registry catalog | grep istio
  ✔  Creating port forwarding tunnel at http://127.0.0.1:45953/v2/_catalog       (1s)
ironbank-mirror/ironbank/opensource/istio/operator
ironbank-mirror/ironbank/opensource/istio/operator-3116871966
```

**Comment by charlescva** [comment]
Resolved! 

So in the upstream chart, the syntax for the image is "hub:",  when i changed from 127.0.0.1 -> harbor.mydomain.com/... i used the 'image' key instead of 'hub'.  So while I was chasing the first issue, and figured out how the CRC is generated for the image... i inadvertently triggered a separate issue with how the chart is traversed. (hub key vs image key, vs image w/ tag included vs seperate tag key...etc)

Now the checksums are matched up and the deployment worked!

Huge thanks to @Racer159 and also @Noxsios for helping me through this.  I now know more about how zarf does the checksum during packaging and deployment as a result!  I hope this thread can be of value to another.  Feel free to scrape anything from this thread for a blog or docs down the road.
