### ISSUE TITLE
WEB UI: SBOM Permission Denied and then not found

### ISSUE THREAD

**Issue by JasonvanBrackel** [defenseunicorns/zarf#1745]
### Environment
Device and OS: MacOS M1 
App version: Zarf 0.27.0
Browser: Brave 1.51.118 Chromium: 113.0.5672.126 (Official Build)
Kubernetes distro being used: K3d
Other:

### Steps to reproduce
1.  Open Zarf UI
1.  Create Package from Postgres Example
1. Attempt to Deploy Postgres Example.
1. SBOM Shows permission denied.
1. Close SBOM Viewer using Ctrl+C
1. Try Deploy again

### Expected result
See SBOM in the Web UI per  https://github.com/defenseunicorns/zarf/pull/1713

### Actual Result

![image](https://github.com/defenseunicorns/zarf/assets/942110/47c9ef2f-9b51-4f0f-9211-b0695e4707aa)

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by Racer159** [comment]
I was able to get an error when using `--skip-sbom` (which was expected as that state wasn't in the UI) but not this error.  Did your `zarf-sbom` folder exist before you tested with the UI?

**Comment by JasonvanBrackel** [comment]
I did not use --skip-sbom, but did open the SBOM view prior.  See https://www.twitch.tv/videos/1827335126 around the 29 minute mark

**Comment by Racer159** [comment]
Closing as we are not able to repo (we can open again if the issue comes back)
