### ISSUE TITLE
Explore places to add more unit tests to library code

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1750]
### Describe what should be investigated or refactored
We should look at targeted areas to add unit tests (specifically in `src/pkg`) to provide better assurances over the interfaces in this code.

### Links to any relevant code
https://github.com/defenseunicorns/zarf/tree/main/src/pkg

### Additional context
This is something we should look at as we move toward GA and get Zarf's interfaces (both schema and library code) to be more stable.

**Comment by schristoff-du** [comment]
Closing as a dupe
