### ISSUE TITLE
Zarf k3s distro ownership and update process

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/zarf#1754]
### Describe what should be investigated or refactored
For Situational Awareness: Kubernetes 1.24 is reaching end of Active Support and transitioning to Maintenance Mode 5/28/23.

The K3s distro is currently using v1.24.1. This should likely be updated - but would love to hear/discuss what ownership the Zarf team has for supporting this distro and how others can contribute to keeping it up-to-date (including what the preferred version the default k3s init component should be). 

Any information around how updates are tested and if there is any additional tech debt that should be considered in optimizing the inclusion of k3s in the init package. 

### Links to any relevant code
https://github.com/defenseunicorns/zarf/blob/main/packages/distros/k3s/zarf.yaml#L17

### Additional context
https://endoflife.date/kubernetes

**Comment by Racer159** [comment]
For this we just need to get renovate on the case and we should be able to keep it more up to date.  We should have plenty of testing (including upgrade testing) for it to catch any issues.  Thanks for the issue!

**Comment by Racer159** [comment]
Closing this as we now have:

1. Renovate setup for k3s updates
2. Better support for handling deprecated APIs across k8s versions
3. Better tests for k3s to be updated and running correctly
