### ISSUE TITLE
OCI Layer Optimizations

### ISSUE THREAD

**Issue by docandrew** [defenseunicorns/zarf#1763]
### Is your feature request related to a problem? Please describe.

We're building a monolithic (>50 GB) Zarf package containing multiple components, and storing it in an OCI image registry. Using `zarf package publish` to push the repo upstream pushes every layer each time, even if layers are unchanged between pushes. Using `zarf package deploy` from the OCI with a subset of the package's components likewise results in downloading every layer, not just the layers necessary to deploy the selected components.

### Describe the solution you'd like

- Given a call to `zarf package publish`, if a layer with matching hash is already present in the upstream repo, I would like Zarf to skip uploading that layer, similar to how the Docker cli tool does with the `layer already exists` message.

- Given a call to `zarf package deploy` from an `oci://` URL, with a list of `--component` options, I'd like Zarf to pull only those layers necessary to deploy the selected components.

- Additionally, if possible `zarf package create` might be able to calculate the overall checksum of the contents for an individual component and avoid re-packaging it if it when the intended destination is an OCI repo and the component layers already exist.

### Describe alternatives you've considered

We've attempted to reduce unnecessary build & publish steps by baking in the commit hash into the Zarf package metadata and skipping a build of the package if it already exists upstream. However this only works for the package as a whole, which is a less common situation than us modifying individual components.

**Comment by Noxsios** [comment]
@docandrew 

I am interested in:

> Using zarf package publish to push the repo upstream pushes every layer each time, even if layers are unchanged between pushes.

As Zarf does not push layers that have not changed.

During publish the same message is used when a layer exists, or has successfully been pushed.

```✔  46564f0eff85 images/blobs/sha256/46564f0...06008f762391a7bb7d58f339ee```

**Comment by Noxsios** [comment]
For point 3, would something like work?:

```
zarf package create <path> -o oci://repo:ref
```

This would mean that the destination is OCI, and the created package _will_ not be saved to disk.

**Comment by docandrew** [comment]
@Noxsios skipping the on-disk save would be great, that might enable us to use smaller CI runners as well!

**Comment by Racer159** [comment]
Closing since the majority of this issue has been addressed and bundles mitigate the last point.  We can revisit later but currently our SBOM logic makes the latter point difficult to do directly in Zarf.

**Comment by Noxsios** [comment]
i concur
