### ISSUE TITLE
Publish Zarf Init Skeleton

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#1773]
### Is your feature request related to a problem? Please describe.
I would like to import the zarf init components as skeletons so that I can bring them into a larger Zarf package.

### Describe the solution you'd like

- **Given** a desire to deploy IaC+Zarf
- **When** creating a zarf package
- **Then** I can easily import components to do it

### Describe alternatives you've considered
Something like this:
https://github.com/runyontr/zarf-package-k3d/blob/main/zarf.yaml#L31-L50

### Additional Context:
This should also swap the `zarf tools download-init` and `zarf init` prompts to pull the init package via `oci://`.
Init packages should still be published to GitHub releases though as before.

**Comment by corang** [comment]
bump, but for the purpose of being able to pull the init package via oci
