### ISSUE TITLE
`zarf tools download-init` should say where the file got downloaded to

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#1778]
### Is your feature request related to a problem? Please describe.

I can use `zarf tools download-init` but it doesn't tell me where the package was downloaded to

### Describe the solution you'd like

- **Given** a state
- **When** an action is taken
- **Then** something happens

Given I want to download the init package and I don't really care where it gets downloaded to as long as zarf can find it, but I do want to know where it went

When I run `zarf tools download-init`

Then Zarf downloads the init package and logs where it was downloaded to

### Additional context
![image](https://github.com/defenseunicorns/zarf/assets/16000938/922fcf69-bc29-485a-805d-12f77f86eb64)

Ideally it would say:

```
zarf tools download-init
  ✔  Downloaded https://github.com/defenseunicorns/zarf/releases/download/v0.26.4/zarf-init-amd64-v0.26.4.tar.zst to <the dest filename>
```

**Comment by dgershman** [comment]
I'm not sure how relevant this is anymore.  When you run this, it uses OCI to download the file.  You can specify a directory to download the init package, which kind of answers the question to this.

**Comment by Racer159** [comment]
Yeah I think we can close this - the behavior now matches `zarf package pull` so if we need to revisit we should globally print things across all commands that use this functionality
