### ISSUE TITLE
Re-evaluate Component Choice

### ISSUE THREAD

**Issue by Noxsios** [defenseunicorns/zarf#1792]
### Describe what should be investigated or refactored

The [component choice feature](https://github.com/defenseunicorns/zarf/tree/main/examples/component-choice) should be re-evaluated. We only use it for this singular example, and it adds some complexity + imperative nature to deploy time.  Additionally you cannot import a component choice group as component imports is a single 1:1 import.  Component choice also results in larger packages as you are required to package every choice's dependencies.  As the nature of zarf seems to be shifting to give package creators more opinionation, it stands to reason this feature should be re-factored / re-evaluated.

### Links to any relevant code

https://github.com/defenseunicorns/zarf/tree/main/examples/component-choice

### Additional context
Add any other context or screenshots about the technical debt here.

**Comment by Racer159** [comment]
Linking in onUpgrade (https://github.com/defenseunicorns/zarf/issues/1526) and wildcard components (https://github.com/defenseunicorns/zarf/issues/1794)

**Comment by Racer159** [comment]
Also adding the `ux` and `ux testing` labels since we should get a sense of how/if people are using this feature today.

**Comment by Racer159** [comment]
https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1687546311778579

**Comment by Racer159** [comment]
Given we haven't received much feedback of those using this feature will open a PR marking it as deprecated.
