### ISSUE TITLE
Improve `zarf package list` for versioned packages

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1797]
### Is your feature request related to a problem? Please describe.
As a deployer I want to be able to see the version of a package that is currently in a cluster so that I can have more confidence around updates or troubleshooting.

### Describe the solution you'd like

- **Given** I have a package in the cluster
- **When** I run `zarf package list`
- **Then** I see the table with the package version included (empty if it is not present)

### Describe alternatives you've considered
We could have versions on a flag but it is likely common enough to be a good default.

### Additional context
This is something people in the community have run into when managing more complex environments and more complex packages.

**Comment by AvineshTripathi** [comment]
Hey I would like to take on this issue can you assign this to me
