### ISSUE TITLE
When full cloning a private repo that falls back to host-git branches are not cloned as heads

### ISSUE THREAD

**Issue by corang** [defenseunicorns/zarf#1799]
similar to #1798 

### Environment
Device and OS: ubuntu 22 vm
App version: 0.27.0

### Steps to reproduce
1. full clone a private repo in zarf package
2. make sure it falls back to host git

### Expected result

all branches are available as heads

### Actual Result

only the main branch is cloned as a head, the rest are remotes

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by Racer159** [comment]
Related to #1799
