### ISSUE TITLE
Zarf init hangs when cluster has a pending pod

### ISSUE THREAD

**Issue by benmountjoy111** [defenseunicorns/zarf#1815]
### Environment
Device and OS: MacOS Ventura 13.2.1
App version: zarf v0.27.1
Kubernetes distro being used: k3d version v5.4.9 (k3s version v1.25.7-k3s1)
Other:

### Steps to reproduce

```bash
# Create cluster
k3d cluster create test-123 \
    --agents 2 \
    --k3s-arg "--disable=traefik@server:*" \
    --k3s-arg "--disable=servicelb@server:*" \
    --port 80:80@loadbalancer \
    --port 443:443@loadbalancer

# Set kube context
export KUBECONFIG=$(k3d kubeconfig write test-123)

# Apply pod that will not schedule (will stay pending)
kubectl apply -f https://raw.githubusercontent.com/kubernetes/website/main/content/en/examples/pods/pod-with-node-affinity.yaml

# Download zarf init package (note this is arm64 not amd64, change accordingly depending on your OS)
wget https://github.com/defenseunicorns/zarf/releases/download/v0.27.1/zarf-init-arm64-v0.27.1.tar.zst

# Init zarf
zarf init --confirm
```

### Expected result
zarf initializes successfully on the cluster

### Actual Result
zarf init (ZARF-INJECTOR COMPONENT) hangs on "Getting the list of existing cluster images" and times out after 5m with:  "ERROR:  Unable to generate a list of candidate images to perform the registry injection"

### Visual Proof (screenshots, videos, text, etc)
![Screenshot 2023-06-13 at 1 30 58 PM](https://github.com/defenseunicorns/zarf/assets/118748385/a3dec8db-1f55-4b64-a671-b6e12d0d6e2d)

followed by:

![Screenshot 2023-06-13 at 1 55 46 PM](https://github.com/defenseunicorns/zarf/assets/118748385/07d9a543-dba6-4b02-909b-f678ba7a8384)

### Additional Context
This issue was also replicated and observed on:
Ubuntu 22.04 (baremetal)
zarf v0.27.1
rke2 v1.26.3+rke2r1

**Comment by Noxsios** [comment]
@benmountjoy111 Thanks for the issue!

Quick tidbit: you can use the command [`zarf tools download-init`](https://docs.zarf.dev/docs/the-zarf-cli/cli-commands/zarf_tools_download-init) to do the same as that cURL
