### ISSUE TITLE
Progress bar not rewriting line in nested zarf process

### ISSUE THREAD

**Issue by timblaktu** [defenseunicorns/zarf#1823]
### Environment
Device and OS: Thinkpad P1 Gen5 - ArchLinux 6.3.6-arch1-1
App version: v0.27.0
Kubernetes distro being used: k3d / n/A
Other: kitty + tmux (TERM=screen-256color) + zsh, but I've confirmed the same happens outside tmux in kitty where TERM=xterm-kitty) 
My Terminal width = 226.

I've also confirmed basic cursor moving / line rewriting works fine in my terminal environment, using the following fun `tput` snippet:

```
echo; tput sc; for i in $(seq 20); do tput ed; date +"%T.%N" | tr -d '\n'; sleep 0.1; tput rc; done
```

### Steps to reproduce
1. `git clone -b 119-document-local-dev-env-setup-and-uds-iac-quick-start-as-an-onboarding-resource git@github.com:defenseunicorns/uds-package-dubbd.git`
2. `cd uds-package-dubbd/k3d/zarf-package-k3d`
3. `zarf package create --confirm`

#### Update: Important Hint!

I believe the problems reported above have to do with the environment in which `zarf` runs `cmd:`s, something must be missing there, bc...

The "Downloading" behavior in question in the above zarf package is spawned recursively (zarf is calling zarf) via the `cmd: ./zarf tools download-init`.

I noticed in another test in the same terminal environment that the Downloading progress bar behaves correctly in my terminal when calling `zarf tools download-init` directly in my terminal, i.e. *_non-recursively_*.

Also, when not running zarf recursively, the problem of `--no-progress` not being respected also goes away.

### Expected result

When `zarf tools download-init -o init` runs in `init` component, the "Downloading" progress bar will re-write the same line each update like a normal progress bar.

### Actual Result

```
    Downloading zarf-init-amd64-v0.27.0.tar.zst  0% | 0s                                                         
    Downloading zarf-init-amd64-v0.27.0.tar.zst  0% | 0s                                                         
    Downloading zarf-init-amd64-v0.27.0.tar.zst  0% | 0s                                                         
    Downloading zarf-init-amd64-v0.27.0.tar.zst  0% | 0s                                                         
    Downloading zarf-init-amd64-v0.27.0.tar.zst  0% | 0s
    .
    .
    .
```

### Visual Proof (screenshots, videos, text, etc)

See "Actual Result" above.

### Severity/Priority

Low

### Additional Context

- Using `--no-progress` has no effect on this behavior. It still shows Downloading progress, and each update on a new line.
- I scanned the [pterm repo/code](https://github.com/pterm/pterm/blob/master/progressbar_printer.go) but found no related issues. 
- I did find something curious in our code [where we're setting the Termwidth to 100](https://github.com/defenseunicorns/zarf/blob/ee62b2903f21eb5d3c6748bca2ebcff62c7d6304/src/pkg/message/message.go#L36) apparently a constant - I couldn't find the place where that would be set dynamically. In any case, my terminal has plenty of width:

```
[0]tim@thinky:~/src/du/uds-package-dubbd/k3d/zarf-package-k3d > echo $COLUMNS                                           zarf-package-k3d (119-document-local-dev-env-setup-and-uds-iac-quick-start-as-an-onboarding-resource *) % 
227
```

**Comment by timblaktu** [comment]
The [pterm progress bar example](https://github.com/pterm/pterm/tree/master/_examples/progressbar/demo) runs as expected (updates re-writing a single line) in my same terminal environment.

**Comment by timblaktu** [comment]
@runyontr probably wouldn't have noticed the progress bar misbehavior when he `zarf package create`s his [`zarf-package-k3d` bc his zarf.yaml isn't downloading the init pkg](https://github.com/runyontr/zarf-package-k3d/blob/main/zarf.yaml).

**Comment by Racer159** [comment]
Marking this as an enhancement - `--no-progess` works for this command now and the issue shows because the inner output is treated as straight standard out / standard err without the additional control characters (Zarf itself keeps the spinner up to date that is running below the command output so we'd need to deconflict that)
