### ISSUE TITLE
Zarf read-only Gitea user

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#183]
As a user of Zarf's Utility Cluster mode, I want the ability to utilize a read-only Gitea user, so that I'm not required to hand out read/write access to services that don't need it.

Notes:

1. Current discussions right now are centered on modifying Zarf to create a Gitea organization, and creating 2 users (the usual `zarf-git-user` plus a read-only user that are both part of the org). This would lock us into Gitea because it requires using their API to do it, but we're okay with that.

**Comment by neoakris** [comment]
Here's a working example of how to do it using bash copy paste commands to trigger the REST API

https://repo1.dso.mil/platform-one/big-bang/apps/sandbox/near-edge-deployment/-/blob/84229baebaac9031dbec8bee8d07777b5fd628e6/deploy_and_populate_zarf.md#create-gitea-read-only-service-account-for-use-by-argocdflux

**Comment by RothAndrew** [comment]
@jeff-mccoy will this be resolved when #237 merges?

**Comment by jeff-mccoy** [comment]
Related but not resolved.  That just lays the groundwork for the solution.
