### ISSUE TITLE
Component Imports example does not exist

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/zarf#1831]
[Component Imports](https://docs.zarf.dev/docs/create-a-zarf-package/zarf-components?chart-examples=localPath&manifest-examples=Local&git-repo-examples=Full+Mirror&import-examples=Local+Path#component-imports) docs section has tabs for `Local Path | OCI URL` neither has an example included.

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/defenseunicorns/zarf/assets/46836330/700b0cc8-673f-4660-a1ec-6e83970f695c)

**Comment by Noxsios** [comment]
Looks like `docs/3-create-a-zarf-package/2-zarf-components.md` just needs the below fix

```
<Tabs queryString="import-examples">
<TabItem value="Local Path">
<ExampleYAML example="composable-packages" component="local-games-path" />
</TabItem>
<TabItem value="OCI URL">
<ExampleYAML example="composable-packages" component="oci-wordpress-url" />
</TabItem>
</Tabs>
```
