### ISSUE TITLE
`zarf tools download-init` does not honor architecture flag

### ISSUE THREAD

**Issue by mjnagel** [defenseunicorns/zarf#1837]
### Environment
Device and OS: MBP, macOS, arm64
Zarf version: 0.27.1
Kubernetes distro being used: N/A

### Steps to reproduce
1. From an `arm64` machine run `zarf tools download-init -a amd64` (or vice-versa, from amd64 run with `-a arm64`)
2. Confirm that the downloaded init package matches the system architecture rather than the user provided flag.

### Expected result

`-a` architecture global flag should be honored, and the matching init package downloaded.

### Actual Result

Incorrect architecture init package is downloaded, matching the system.

### Visual Proof (screenshots, videos, text, etc)

```
❯ zarf tools download-init -a amd64
  ✔  Downloaded https://github.com/defenseunicorns/zarf/releases/download/v0.27.1/zarf-init-arm64-v0.27.1.tar.zst
```

### Severity/Priority

Low, there are workarounds by curl/wget the init package, etc.

**Comment by timblaktu** [comment]
Linking to [slack thread about this](https://defense-unicorns.slack.com/archives/C029NJU2S4B/p1687358636791269) for future reference and visibility.
