### ISSUE TITLE
Zarf read-only docker registry user

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#184]
As a user of Zarf's Utility Cluster mode, I want the ability to utilize a read-only user for the docker registry, so that I don't need to hand read/write access to services that don't need it

**Comment by RothAndrew** [comment]
@jeff-mccoy will this be resolved when #237 merges?

**Comment by jeff-mccoy** [comment]
Related but not resolved.  That just lays the groundwork for the solution.

**Comment by Racer159** [comment]
Marking as completed since `GenerateRegistryPullCreds` uses the `PullPassword` and `PullUsername`
