### ISSUE TITLE
gRPC Transformation service to synchronized code between Zarf Agent and Pepr  (Transform)

### ISSUE THREAD

**Issue by cmwylie19** [defenseunicorns/zarf#1862]
### Is your feature request related to a problem? Please describe.
We need a way to synchronize the typescript and Go code in the transform package of Zarf. The transform package will grow organically as zarf supports more objects, for now it supports images, git, and artifact, but this could be Argo, Flux and more in the future. We do not want to duplicate code across languages as it would lead to drift.  After deliberation, it seems as though using gRPC's protobufs to generate structs (classes) in both languages and use client stubs to call the functions on the gRPC server, which will use the pre-existing transform library.

This code would go into the Zarf Repo but would have a separate `main.go`.

### Describe the solution you'd like

- **Given** you are init'ing zarf
- **When** when it comes to the agent-hook you choose, whether that be a Pepr-Zarf-Agent hook or the native zarf-agent hook,
- **Then** they will use the exact same library and functions to do transformations 

### Describe alternatives you've considered
 Alternatives considered were using [v8go](https://github.com/rogchap/v8go) and executing JavaScript in a sandbox, but this is the inverse of what we need -- we need to execute the go commands on the JavaScript side. There are also c-dependencies associated with v8go.

**Comment by Noxsios** [comment]
Closing in favor of using `zarf internal gen-types-schema | npx quicktype -s schema -o zarf-types.ts`
