### ISSUE TITLE
Zarf Checksum failure

### ISSUE THREAD

**Issue by joelcomp1** [defenseunicorns/zarf#1867]
### Environment
Device and OS: x86 64 Rocky 8.7
App version: 2.6.2
Kubernetes distro being used: k3s
Other:

### Steps to reproduce
1. zarf package deploy

### Expected result
Deploy package 

### Actual Result

Fails with checksum failure

### Visual Proof (screenshots, videos, text, etc)

Saving log file to /tmp/zarf-2023-06-29-14-39-40-3238093318.log

  ⠴  Loading the zarf package config (17s)                                                                                                                                                                         
     ERROR:  Failed to deploy package: unable to load the Zarf Package: unable to validate the package checksums:
             mismatch on the checksum of the
             images/blobs/sha256/e543d039704a927686af50ee12c85b8e8fff304c933b202624bbc705cf60161a file (expected:
             e543d039704a927686af50ee12c85b8e8fff304c933b202624bbc705cf60161a, actual:
             7e5431874d03da45bc2ee4e5245724b6c3a86eba8ae448ce749ebc79ec16029e)

### Additional Context
I see this randomly and I don't know why. I originally thought it was related to a bad package checksum from my copy to the HDD but then i found sometimes it would fail on the exact same file I ran previously that had work (no change on disk at all).

the log file it referenced had this in it

^[[90m^[[0m^[[101;30m^[[101;30m     ERROR: ^[[0m^[[0m ^[[91m^[[91mFailed to deploy package: unable to load the Zarf Package: unable to validate the package checksums:^[[0m^[[0m
^[[101;30m^[[101;30m            ^[[0m^[[0m ^[[91m^[[91mmismatch on the checksum of the^[[0m^[[0m
^[[101;30m^[[101;30m            ^[[0m^[[0m ^[[91m^[[91mimages/blobs/sha256/e543d039704a927686af50ee12c85b8e8fff304c933b202624bbc705cf60161a file (expected:^[[0m^[[0m
^[[101;30m^[[101;30m            ^[[0m^[[0m ^[[91m^[[91me543d039704a927686af50ee12c85b8e8fff304c933b202624bbc705cf60161a, actual:^[[0m^[[0m
^[[101;30m^[[101;30m            ^[[0m^[[0m ^[[91m^[[91m7e5431874d03da45bc2ee4e5245724b6c3a86eba8ae448ce749ebc79ec16029e)^[[0m^[[0m
^[[30;100m^[[30;100m  DEBUG  ^[[0m^[[0m ^[[90m^[[90m2023-06-29T14:39:58-04:00  -  goroutine 1 [running]:^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90mruntime/debug.Stack()^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90m    /opt/hostedtoolcache/go/1.19.8/x64/src/runtime/debug/stack.go:24 +0x65^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90mgithub.com/defenseunicorns/zarf/src/pkg/message.Fatal({0x35f2360?, 0xc000c39880?}, {0xc000472a80, 0x175})^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90m    /home/runner/work/zarf/zarf/src/pkg/message/message.go:150 +0x18a^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90mgithub.com/defenseunicorns/zarf/src/pkg/message.Fatalf({0x35f2360, 0xc000c39880}, {0x3bc0140?, 0x0?}, {0xc002d17d28?, 0x0?, 0x0?})^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90m    /home/runner/work/zarf/zarf/src/pkg/message/message.go:157 +0x51^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90mgithub.com/defenseunicorns/zarf/src/cmd.glob..func15(0x7532fa0?, {0xc000891300?, 0x4?, 0x4?})^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90m    /home/runner/work/zarf/zarf/src/cmd/package.go:96 +0x19f^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90mgithub.com/spf13/cobra.(*Command).execute(0x7532fa0, {0xc0008912c0, 0x4, 0x4})^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90m    /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:944 +0x847^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90mgithub.com/spf13/cobra.(*Command).ExecuteC(0x7533b20)^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90m    /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90mgithub.com/spf13/cobra.(*Command).Execute(...)^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90m    /home/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90mgithub.com/defenseunicorns/zarf/src/cmd.Execute()^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90m    /home/runner/work/zarf/zarf/src/cmd/root.go:68 +0x25^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90mmain.main()^[[0m^[[0m
^[[30;100m^[[30;100m         ^[[0m^[[0m ^[[90m^[[90m    /home/runner/work/zarf/zarf/main.go:23 +0x6f^[[0m^[[0m^[[90m^[[0m
^[[90m└ (/home/runner/work/zarf/zarf/src/pkg/message/message.go:150)^[[0m
^[[90m^[[0m

**Comment by Racer159** [comment]
Interesting... The checksums are stored at the root of a zarf package and should always match the image layer SHA (hence the filename `images/blobs/sha256/e543d039704a927686af50ee12c85b8e8fff304c933b202624bbc705cf60161a` and the expected SHA `e543d039704a927686af50ee12c85b8e8fff304c933b202624bbc705cf60161a` matching each other).  Have you observed flakiness where it starts working again? Or does it always fail once it starts to fail?

Also just to check, are you using the same Zarf version between package create and deploy?

Also if you really need to and want to push past this error you _could_ run with `--insecure` though I would recommend only doing that on a test instance since there is a chance of there being a corrupted layer.  Under the hood Zarf unpacks the package to the temporary directory of the system and afterwards checks the package checksums before proceeding - something could be going wrong during this unarchive/copy process.  When Zarf fails it leaves these files behind for inspection and you could use `zarf prepare sha256sum <filepath>` to investigate the files more directly.

**Comment by joelcomp1** [comment]
Interesting you say that. I have seen it to be that it will eventually work if you either do it enough times or I was also seeing I rebooted the machine it would work after reboot the first time.  We actually tried to use - -insecure but that didn't seem to help.  I will verify but I'm fairly certain our zarf versions matched as I was worried that could be a potential issue.

**Comment by joelcomp1** [comment]
I did verify we are running Zarf 0.26.2 in all locations so should have all matched

**Comment by Racer159** [comment]
Rebooting the machine is an interesting symptom...  Are you specifying `--tmpdir` at all or just using `/tmp`?  If you run `rm -rf /tmp/zarf-*` does that have the same effect as rebooting?

**Comment by Racer159** [comment]
(also looking at the code the `--insecure` flag help text is wrong (or at least misleading) we do disable the validation of signatures (and thus you can modify the checksums to match) but we wstill always look at the checksums if they are present - will make a note to update that)

**Comment by joelcomp1** [comment]
No I am not specifying --tmpdir, so it would just be /tmp, I actually didn't realize until recently how much stuff was dumped into /tmp on failures, but I don't believe I ever tried to clear that out during a checksum failure.  I know I did `rm -rf /tmp/zarf-*' at one point but I can't 100% recall if it was around the checksum time.  Next time I see it though I will give that a try.  I know we are a few releases behind, is there anything on the newer releases since 0.26.2 that would have fixed anything in regards to this?

**Comment by Racer159** [comment]
There have been some minor refactors done to checksum handling in the intervening versions but there shouldn't have been any behavioral changes

**Comment by Noxsios** [comment]
Closing as stale.

If you are still seeing this issue @joelcomp1, feel free to re-open and provide the team w/ more info!
