### ISSUE TITLE
Injector fails to select a pod when using images other than `library/registry`

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#1895]
### Environment
Device and OS: Dell T1700 - Arch Linux 
App version: v0.28.0
Kubernetes distro being used: k3d
Other:

### Steps to reproduce
1. Create an init package with the registry v2 image from Iron Bank: https://registry1.dso.mil/harbor/projects/3/repositories/opensource%2Fdocker%2Fregistry-v2/artifacts-tab
2. Run `zarf package init`

### Expected result
Zarf successfully initializes

### Actual Result
Zarf fails to select a pod to initialize from

### Additional Context
This is due to an issue with how the injector handles serving images that it loads from configmaps

**Comment by fallenpixel** [comment]
This issue occurred for me, using RKE2, I'm sorry I didn't save logs, though I can reproduce if needed.

**Comment by Noxsios** [comment]
This is due to the way the injector was written. Currently the injector will only handle a `docker pull` to route `library/registry`
