### ISSUE TITLE
Diffing system: create zarf package update process

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#19]
Though the underlying components of zarf packaging won't change with diffing, zarf should have a command that a user or pipeline can run that either prompts (or accepts as input) a last commit/tag/amount of time to diff changes to determine what to include in the package.  `zarf package update` should only include those images/repos/files that have changed references since the last defined interval.  For many types of data in zarf this is natural as we can treat some things as immutable such as repo and image tags.  Although some systems (Iron Bank) do not abide by this convention, it's still the most reliable way to track using just a zarf.yaml via git diffs without more complex logic.  Some components though, such as manifests probably are best always packaging as they are very lightweight and declarative.

---

Migrated from https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/33

**Comment by RothAndrew** [comment]
I think this will become important again in the future, but for now I don't believe it is a priority. Closing this issue for now. It can be reopened when it needs to be.

**Comment by Racer159** [comment]
https://github.com/defenseunicorns/zarf/issues/1426 - closing in favor of differential updates and the discussion around it
