### ISSUE TITLE
Feature List - with status Label

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#1904]
## Current Zarf Features
Definitions of each label can be found in [Roadmap ADR
](https://github.com/defenseunicorns/zarf/blob/49d41eea4c513fc2b38d4926120d9445c7c20da5/docs/9-roadmap.md?plain=1#L25)

### Stable 
- Automate [Software Bill of Materials (SBOM)](https://docs.zarf.dev/docs/create-a-zarf-package/package-sboms) generation
- Build and [publish packages as OCI image artifacts](https://docs.zarf.dev/docs/zarf-tutorials/publish-and-deploy)
- Provide a [web dashboard](https://docs.zarf.dev/docs/deploy-a-zarf-package/view-sboms) for viewing SBOM output
- Create and verify package signatures with [cosign](https://github.com/sigstore/cosign)
- [Publish](https://docs.zarf.dev/docs/the-zarf-cli/cli-commands/zarf_package_publish), [pull](https://docs.zarf.dev/docs/the-zarf-cli/cli-commands/zarf_package_pull), and [deploy](https://docs.zarf.dev/docs/the-zarf-cli/cli-commands/zarf_package_deploy) packages from an [OCI registry](https://opencontainers.org/)
- Powerful component lifecycle [actions](https://docs.zarf.dev/docs/create-a-zarf-package/component-actions)
- Deploy a new cluster while fully disconnected with [K3s](https://k3s.io/) or into any existing cluster using a [kube config](https://kubernetes.io/docs/concepts/configuration/organize-cluster-access-kubeconfig/)
- Builtin logging stack with [Loki](https://grafana.com/oss/loki/)
- Builtin Git server with [Gitea](https://gitea.com/)
- Builtin Docker registry
- Builtin [K9s Dashboard](https://k9scli.io/) for managing a cluster from the terminal
- [Mutating Webhook](https://docs.zarf.dev/adr/mutating-webhook) to automatically update Kubernetes pod's image path and pull secrets as well as [Flux Git Repository](https://fluxcd.io/docs/components/source/gitrepositories/) URLs and secret references
- Builtin [command to find images](https://docs.zarf.dev/docs/the-zarf-cli/cli-commands/zarf_prepare_find-images) and resources from a Helm chart
- Tunneling capability to [connect to Kuberenetes resources](https://docs.zarf.dev/docs/the-zarf-cli/cli-commands/zarf_connect) without network routing, DNS, TLS or Ingress configuration required

### Beta
- Web UI

### Alpha
- bundles

### Deprecated
- component choice

**Comment by Noxsios** [comment]
> @YrrepNoj @Racer159 @Noxsios - Requesting the team adds features into the appropriate sections of this list or if there is a better place for this to live then let me know :)

Currently most of this info lives in src/config/english.go

**Comment by Madeline-UX** [comment]
Should we differentiate between stable binary features and stable Init package features?

**Comment by schristoff-du** [comment]
We are going to be switching from Alpha/Beta to Deprecated or Experimental - we will be making a new issue for 1.0 planning to see what to deprecate based off the current state of the world in Zarf today
