### ISSUE TITLE
When zarf package publish is used as library, no additional cli commands should be printed

### ISSUE THREAD

**Issue by alita1991** [defenseunicorns/zarf#1908]
### Is your feature request related to a problem? Please describe.
During the utilization of the zarf package as a library, I noticed some CLI commands that are printed at the end of the PublishPackage function call. 

```
To inspect/deploy/pull:   
$ zarf package inspect oci://registry.com/docker/zarf-package-wordpress/wordpress:16.0.4-amd64 
$ zarf package deploy oci://registry.com/docker/zarf-package-wordpress/wordpress:16.0.4-amd64
$ zarf package pull oci://registry.com/docker/zarf-package-wordpress/wordpress:16.0.4-amd64
```

**src/oci/pkg/push.go**
`func (o *OrasRemote) PublishPackage(pkg *types.ZarfPackage, sourceDir string, concurrency int) error {}`

```
message.Title("To inspect/deploy/pull:", "")
message.ZarfCommand("package inspect oci://%s %s", o.repo.Reference, flags)
message.ZarfCommand("package deploy oci://%s %s", o.repo.Reference, flags)
message.ZarfCommand("package pull oci://%s %s", o.repo.Reference, flags)
```

To mitigate potential confusion for end-users caused by the discrepancy between the name of my CLI tool and the CLI commands generated by the zarf package, I seek to disable the display of those messages.

### Describe the solution you'd like
Move the log section outside of the OCI pkg to a CLI pkg (ex: publish action main logic)

### Describe alternatives you've considered
An alternative way is to disable the print messages inside the function using log levels or a similar mechanism.

**Comment by Noxsios** [comment]
@alita1991 I believe this is possible using `pterm.DisableOutput()`, can you let me know if this works for you?

**Comment by alita1991** [comment]
Hi @Noxsios,

I tested the solution you provided before I opened the ticket, the only problem I found is that it is disabling logs that I want to keep, like the progress made when pushing the blobs.

**Comment by Noxsios** [comment]
@alita1991 Agreed. I have a PR in progress that will be touching the OCI library a bit. In a release or two this functionality will be available. I'll keep this issue updated on when exactly that will be.
