### ISSUE TITLE
Zarf prepare findImages method should return the string of images not only printing them to stdout.

### ISSUE THREAD

**Issue by alinalex1392** [defenseunicorns/zarf#1918]
### Is your feature request related to a problem? Please describe.
We are consuming Zarf a library, especially the FindImages method from the pkgClient *packager.Packager object. This method computes the list of images that are found inside a ZarfConfig. 
The problem is that the method only prints in a structured yaml format the list of images to stdout but does not return them using the function return variables.

### Describe the solution you'd like

Solutions 1:

The FindImages function should change the signature to:
func (p *Packager) FindImages(baseDir, repoHelmChartPath string, kubeVersionOverride string) (string, error) {}

The returned string should be the list of images

Solutions 2:

The FindImages function should change the signature to:
func (p *Packager) FindImages(baseDir, repoHelmChartPath string, kubeVersionOverride string) (*ZarfConfiguration, error) {}

type ZarfComponent struct {
	Name   string   `yaml:"name"`
	Images []string `yaml:"images"`
}

type ZarfConfiguration struct {
	Components []IndigoZarfComponent `yaml:"components"`
}

The return should represent a domain model and not a simple string.

**Comment by cmwylie19** [comment]
Hi @alinalex1392 , im going to chat with the team around this. I see your point why it would be helpful to get a string of the raw images for pre-caching or disconnected installs when consuming Zarf as a lib.
