### ISSUE TITLE
zarf package push to ECR EOF error during zarf package create command

### ISSUE THREAD

**Issue by gscallon** [defenseunicorns/zarf#1938]
### Environment
Device and OS: M2 Mac Ventura 13.2, Linux AMD64 (GL Runner)
App version: 0.28.0, 0.28.2, 0.28.3
Kubernetes distro being used: N/A (locally), same results when running these operations within a GitLab Runner on EKS
Other:

### Steps to reproduce
1. Create an ECR repo that has appropriate IAM permissions for the local machine / GitLab Runner to push to
2. Log into the ECR registry `aws ecr get-login-password --region us-east-1 | zarf tools  registry login --username AWS --password-stdin <account>.dkr.ecr.us-east-1.amazonaws.com`
3. Ensure that there is a version included in the zarf.yaml metadata section for OCI compatibility.
4. Create a Zarf package (the manifests example in the upstream Zarf example was used here) and utilize the ECR URL as the OCI endpoint to publish to

### Expected result

I expect to be able to push a Zarf package OCI artifact to ECR registry in the same way I can do with GitLab Container Registry, ttl.sh, etc. 

### Actual Result

The publish operation will fail with a POST EOF error to ECR when done in the way the doc examples show. Cannot publish Zarf packages like I can publish a helm chart archive to the repository.

### Visual Proof (screenshots, videos, text, etc)

Unsuccessful package publish to ECR from local Mac:

```
gavinscallon@Gavins-MacBook-Pro-2 manifests % zarf package create . --confirm --max-package-size=0 --output oci://950698127059.dkr.ecr.us-east-1.amazonaws.com

 NOTE  Saving log file to
       /var/folders/37/qqg82c0x2hx43pczwp305f0r0000gn/T/zarf-2023-07-31-18-17-08-14088666.log

 NOTE  Using build directory .



  📦 PACKAGE DEFINITION



kind: ZarfPackageConfig

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
metadata:  information about this package

  name: manifests
  version: 0.0.1
  
  
  ...
  
  
    ✔  Loading 1 K8s manifests


  📦 PACKAGE IMAGES


  ✔  Loading metadata for 3 images.
  ✔  Pulling 3 images (86.67 MBs)
  ✔  Creating SBOMs for 3 images and 0 components with files.
  •  Publishing package to 950698127059.dkr.ecr.us-east-1.amazonaws.com/manifests:0.0.1-arm64
  ✔  Prepared 30 layers
     ERROR:  Failed to create package: unable to publish package: Post
             "https://950698127059.dkr.ecr.us-east-1.amazonaws.com/v2/manifests/blobs/uploads/": EOF
  
  
```

Successful package publish to ttl.sh:

```
gavinscallon@Gavins-MacBook-Pro-2 manifests % zarf package create . --max-package-size=0 --output oci://ttl.sh/gavin-test

 NOTE  Saving log file to
       /var/folders/37/qqg82c0x2hx43pczwp305f0r0000gn/T/zarf-2023-07-31-17-38-13-2118475158.log

 NOTE  Using build directory .

  📦 PACKAGE DEFINITION

kind: ZarfPackageConfig

...


  ✔  7bbc8783b8ec images/blobs/sha256/7bbc878...16cbb907c8ab1b8685732d50a4
  ✔  a1bf0361e142 components/podinfo-kustomize.tar
  ✔  8c6d1654570f images/blobs/sha256/8c6d165...1324913009d92a19132cbf1ac0
  ✔  898d1cc4a25d images/blobs/sha256/898d1cc...344587e76de26c1b5b23153311
  ✔  925342e1fcde images/blobs/sha256/925342e...a5562fd1f8a2adec59e5d34655
  ✔  a1791d48ea11 images/blobs/sha256/a1791d4...92c33f47b5a8d48c276c6e36c6
  ✔  a718ad892946 images/blobs/sha256/a718ad8...e309b8661a4b025bfbd7627394
  ✔  ab18e6ab797f images/blobs/sha256/ab18e6a...8b2304e3356cbd70e95794453d
  ✔  ae7a741c67fe images/blobs/sha256/ae7a741...f0ab6b00e27324499aefc4b22e
  ✔  bcb7c7df920e images/blobs/sha256/bcb7c7d...02dcf71eb3ae7cc1b90827b34e
  ✔  d032c98662a8 images/blobs/sha256/d032c98...8ff1473feaf51769ae3f5790da
  ✔  d58b3e481b85 images/blobs/sha256/d58b3e4...bf9194f06e2adce641822e282a
  ✔  e087052915d8 images/blobs/sha256/e087052...16edae02165461dc894f708625
  ✔  edb6bdbacee9 images/blobs/sha256/edb6bdb...676aa342a70e2221361fd1914d
  ✔  f7b90c5086f6 images/blobs/sha256/f7b90c5...e358a0d61c3d58b3acebab1149
  ✔  26e02913f946 images/index.json
  ✔  b66dbb27a733 images/oci-layout
  ✔  4b6385b2bb76 zarf.yaml
  ✔  078f282b4e5c sboms.tar
  ✔  d46002273236 [application/vnd.oci.image.manifest.v1+json]
  ✔  Published ttl.sh/gavin-test/manifests:0.0.1-arm64 [application/vnd.oci.image.manifest.v1+json]

━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
 To inspect/deploy/pull:
$ zarf package inspect oci://ttl.sh/gavin-test/manifests:0.0.1-arm64
$ zarf package deploy oci://ttl.sh/gavin-test/manifests:0.0.1-arm64
$ zarf package pull oci://ttl.sh/gavin-test/manifests:0.0.1-arm64
```

### Severity/Priority

It would be great to be able to publish Zarf packages using OCI format to ECR. There are a number of potential applications for this. It would be great to publish Zarf packages to ECR at the conclusion of pipeline runs. One of our larger customers would utilize a pipeline that could do this, for example.

### Additional Context
Have ensured this is not a path/IAM permissions/etc issue with regards to the ECR repository.

Have attempted this with both commercial and GovCloud ECR registries. 

I was able to confirm that I can helm push chart archives to the ECR registry. I am also able to push individual container images.

I tried a range of different endpoints, naming conventions, tags, etc. 

I followed this (AWS ECR documentation)[https://docs.aws.amazon.com/AmazonECR/latest/userguide/push-oci-artifact.html] for the Helm chart uploads.

**Comment by Noxsios** [comment]
@gscallon Unlike other registries (GHCR, Dockerhub, distribution/distribution) ECR does not support push to create or nested repositories. As such, each repo name must be fully qualified in order for you to publish properly.

```
zarf package create examples/helm-charts/ -o oci://950698127059.dkr.ecr.us-east-1.amazonaws.com
```

This package name is `helm-charts`, so it is looking to push to a repository at 

![Screenshot 2023-08-01 at 11 24 32 AM](https://github.com/defenseunicorns/zarf/assets/50058333/6805b3f5-b872-42c2-969e-e2b4bab784f2)

The example shown in a private ECR registry, and has also been verified on public ECR.

**Comment by Racer159** [comment]
Definitely make sure that the ecr repository `manifests` exists - we do test ECR nightly (had been failing for unrelated issues that are now fixed and we have a PR to be better notified of those failures) https://github.com/defenseunicorns/zarf/actions/workflows/nightly-ecr.yml

**Comment by gscallon** [comment]
Done in by a permissions issue. The functionality is working as expected. I'll close this issue. Thanks for the support!!
