### ISSUE TITLE
Add `gojq` as a `zarf tools gojq` or `zarf tools jq` command

### ISSUE THREAD

**Issue by gerred** [defenseunicorns/zarf#1952]
### Is your feature request related to a problem? Please describe.
dubbd's k3d currently requires jq as part of the metallb.sh, an external dependency. Including it in zarf tools would make the deployment only require zarf.

### Describe the solution you'd like

- **Given** I run the DUBBD k3d Zarf package
- **When** jq is used to parse responses while bootstrapping metallb
- **Then** it should work when edited to be `zarf tools jq` (or `zarf tools gojq`)

### Describe alternatives you've considered
Main alternative would be to require users to still install jq, or have it in an existing environment. Also considered the primary version of jq everyone thinks of - but it is written in C and would require a CGo build and binding.

**Comment by Racer159** [comment]
This could be an interesting alternative as well: https://fx.wtf/
