### ISSUE TITLE
Zarf does not support deploying Flux HelmReleases with OCI Helm chart sources

### ISSUE THREAD

**Issue by bburky** [defenseunicorns/zarf#1974]
### Is your feature request related to a problem? Please describe.

Zarf does not support deploying Flux HelmReleases with OCI Helm chart sources

_[Related issue](https://github.com/defenseunicorns/zarf/issues/2021)_

### Describe the solution you'd like

- **Given**
    * A `zarf.yaml` with `manifests:` including a Flux HelmRepository referencing an `oci://` chart and a HelmRelease referencing it.
    * And including the OCI helm chart in `images:` in `zarf.yaml`.
- **When** creating the package
- **Then**
   - The package cannot be created because `images:` does not support arbitrary (non-container) OCI images
      ```
      ERROR:  Failed to create package: unable to pull images after 3 attempts: error when trying to save the img                                                                   
              (ghcr.io/stefanprodan/charts/podinfo:6.4.1): mismatched fs layers (1) and diff ids (0)
      ```
   - Additionally, Zarf's mutating admission webhooks do not support mutating HelmRepository and HelmRelease resources to reference the Zarf registry

Example Flux manifests referencing an OCI Helm chart: https://fluxcd.io/flux/cheatsheets/oci-artifacts/#helm-oci

A potential issue: Zarf uses an insecure registry and Flux source-controller may not support insecure OCI registries with Helm: https://github.com/fluxcd/source-controller/issues/807

   * A little unclear on what's affected and if this issue is still current
   * OCIRepository (consumed by kustomize-controller, not helm-controller) _does_ support [`.spec.insecure`](https://fluxcd.io/flux/components/source/ocirepositories/#insecure)
   * Need to check the current status of HelmRepository and HelmReleases with an insecure localhost registry (sometimes localhost is special cased and allowed)

### Describe alternatives you've considered

Zarf's built in Helm support does allow OCI, see `demo-helm-oci-chart` in this example: https://docs.zarf.dev/examples/helm-charts/

However, this does not support using Flux.

### Additional context

The scenario prompting this is a vendor only provides OCI packaged Helm charts. We do not need to modify the upstream vendor charts, and would like to copy them unmodified, and deploy them using Flux.

Additionally, Big Bang now distributes Helm charts in OCI format. If Zarf supported this, the dependency on a Gitea git repository could be dropped in many cases.

Support for generic OCI artifacts may be generally useful for other non-Flux use cases too.

**Comment by joelcomp1** [comment]
+1 this, I would also love to have this exact feature for our Flux Releases

**Comment by cmwylie19** [comment]
Just starting to investigate this and wanted to circle back to update the issue:

In terms of the admission controller (Zarf Agent), this development looks like it would touch:
**HelmRepository**
```yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m
  type: oci
  url: oci://ghcr.io/stefanprodan/charts # <- HERE
  ```
  **OCIRepository**
  ```yaml
  apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: OCIRepository
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 10m
  url: oci://ghcr.io/stefanprodan/manifests/podinfo # <- Here 
  ref:
    tag: latest
```


  
  In term's of Zarf's transform library, we should already be capable of transforming the URL as long as we emit the oci:// protocol internally.  [Example here](https://github.com/defenseunicorns/zarf/blob/89b6848b1ebf4e51022a2fd165342811a9321bfb/src/pkg/transform/image_test.go#L14)
  
  The biggest complexity that I am aware based on the issue of seems like it would be around the insecure registry which needs more investigation. I think worst case we would look at securing the Zarf internal registry possibly

**Comment by bburky** [comment]
There are at least 3 tasks:
1. Rewrite HelmRepository and OCIRepository in admission webhook.
2. Add support for packaging arbitrary OCI artifacts, one option is just telling people to add them to `images:`. However there is an issue that (crane?) throws the `mismatched fs layers (1) and diff ids (0)` error mentioned above.
3. Test if HelmRepository supports an insecure localhost registry.

**Comment by cmwylie19** [comment]
> There are at least 3 tasks:
> 
> 1. Admission webhook update to rewrite HelmRepository and OCIRepository with Zarf registry
> 2. Add support for packaging arbitrary OCI artifacts, one option is just telling people to add them to `images:`. However there is an issue that (crane?) throws the `mismatched fs layers (1) and diff ids (0)` error mentioned above.
> 3. Test if HelmRepository supports an insecure localhost registry.


FWIW, for #(2), i think we have to assume they are bringing their images ready to go. So they basically make a scratch container with their manifests. However, there are other blockers in terms of our internal registry before getting to point 3. I'll leave a comment about it for the future when this can be fixed.

**Comment by bburky** [comment]
> So they basically make a scratch container with their manifests

Not quite. These are OCI artifacts (not quite, that specific term can mean something else), not actual "images". These aren't "Docker images" at all (the layers are not `application/vnd.oci.image.layer.v1.tar+gzip` tarball layers with a `application/vnd.oci.image.index.v1+json` config). This is packaging non-Docker images as into "OCI images" something still compatible enough with registries to work, but storing different types of data (Helm charts in this case). You'd use something like `helm push` to create these OCI images.

@Noxsios would be familiar and probably help explain. It's also how Zarf's own OCI support works (Zarf uses ORAS, Helm does something [slightly different](https://helm.sh/docs/topics/registries/#helm-chart-manifest), but it's the same concept).

In theory these generic OCI images can be copied around the same way as Docker images, which is why I suggested listing them in `images:`, but it seems something throws an error while downloading them.

**Comment by cmwylie19** [comment]
@bburky thank you for the clarity!!

**Comment by mjnagel** [comment]
Just to clarify on flux support - OCIRepository cannot be used as a source for a HelmRelease. So I believe to fully support OCI sourced Flux HelmReleases with Zarf we'll need to solve the insecure registry issue either by Flux adding support or by securing the Zarf registry.

**Comment by cmwylie19** [comment]
Unassigned as this will be likely 2 PRs, one for OCIRepo and another that needs more discussion between Zarf team. OCIRepo should be ready soon but is pending one PR

**Comment by jeff-mccoy** [comment]
The challenge with tls on the registry is their is no safe k8s-native way to tell the CRIs to use a given CA like you can with admission controllers. The most generic k8-way is to use a privileged daemonset to modify your CRI config (which is as awful as it sounds). Many platforms will modify the CRI out-of-band to accommodate this during cluster init or node image building.

**Comment by cmwylie19** [comment]
re-assigning myself after chatting with @Racer159 , we will support `HelmRepo` as long as the type is OCI

```yaml
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: podinfo
  namespace: default
spec:
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/stefanprodan/charts
  ```

**Comment by cmwylie19** [comment]
- In terms of the `HelmRepo`,  I ultimately ended up getting blocked by [Flux not supporting insecure registry](https://github.com/fluxcd/source-controller/issues/807) as @bburky eluded to in the initial message. However, the logic mutate the admission controller is there in this [draft PR](https://github.com/defenseunicorns/zarf/pull/2005), so once Flux adds support, we can revisit this and merge it into Zarf.

- The logic for OCIRepo is done and will close [this issue ](https://github.com/defenseunicorns/zarf/issues/2021) and will live on another branch.

**Comment by bburky** [comment]
Flux added a `.spec.insecure` to `type: oci` `HelmRepository` resources, the flux issue linked above was closed. 🎉 

In addition to mutating the source of an OCI HelmRepository/OCIRepository, zarf could add the insecure flag automatically if a localhost registry is used.

**Comment by koolay** [comment]
For now, git server is required in local cluster if deploy using flux.  Just require the local registry if oci is supported.

**Comment by Shane-UE** [comment]
I see that this has been unblocked now, what is the latest update on this feature?
