### ISSUE TITLE
zarf init fails on multi-node minikube cluster

### ISSUE THREAD

**Issue by vanakema** [defenseunicorns/zarf#1998]
### Environment
Device and OS: MacBook Pro M2 Pro, MacOS
App version: v0.29.1
Kubernetes distro being used: MiniKube (Docker driver) v1.31.1, k8s v1.24.7
Other:

### Steps to reproduce
1. `minikube start --kubernetes-version 1.24.7 --nodes 3`
2. `zarf init --confirm`

### Expected result
It works

### Actual Result
The registry fails to deploy

Pod Logs (zarf-docker-registry):
```shell
Configuration error: error parsing /etc/docker/registry/config.yml: no storage configuration provided
Usage: 
  registry serve <config> [flags]
Flags:
  -h, --help=false: help for serve
Additional help topics:
```

### Visual Proof (screenshots, videos, text, etc)
It just never deploys, and the Helm deploy just keeps trying till it times out, spitting out essentially the same error as above.

### Severity/Priority
High: needed for our developer environment for testing HA application deployments. Not affecting prod (yet)

### Additional Information
We tried this as well, which resulted in 1 registry pod deploying, but the 2nd pod had the same error as listed above
`zarf init --storage-class=standard --set REGISTRY_PVC_ENABLED=false --confirm`

**Comment by vanakema** [comment]
This go around of tearing down minikube and bringing it up, it did successfully deploy the registry pod, but the rest of the zarf deploy fails with this error:

```
     ERROR:  unable to deploy all components in this Zarf Package: unable to deploy component zarf-registry: unable to deploy component zarf-registry: unable to push images to the registry: POST http://127.0.0.1:59435/v2/library/registry/blobs/uploads/: UNKNOWN: unknown error; map[DriverName:filesystem Enclosed:map[Err:13 Op:mkdir Path:/var/lib/registry/docker]]
```

**Comment by Noxsios** [comment]
@vanakema

Following: https://minikube.sigs.k8s.io/docs/tutorials/volume_snapshots_and_csi/ w/ a fix as noted in https://github.com/kubernetes/minikube/issues/12360

This worked for me:

```bash
minikube start --kubernetes-version 1.24.7 --nodes 3
minikube addons enable volumesnapshots
minikube addons enable csi-hostpath-driver
kubectl patch storageclass csi-hostpath-sc -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'

zarf init --storage-class=csi-hostpath-sc --log-level=trace --confirm
```

Let me know if this works for you!

**Comment by vanakema** [comment]
Thanks! We went in a different direction where we don't need a cluster locally anymore, but if we do, I'll try it out

**Comment by Racer159** [comment]
Going to close this issue for now - Zarf does require a storage class for its registry by default (though you can turn this off and back it by something like S3 if you prefer) - also worth noting that we are working on a zarf-init-longhorn package that should be ready soon that will include a storage class of its own.

https://github.com/defenseunicorns/zarf-init-longhorn

**Comment by Racer159** [comment]
We can reopen if we need to @vanakema
