### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#2]
**Will need to break this out into an epic**

Although the Iron Bank lacks significant ARM support at the moment, we only need two images for shift pack's cluster to function (registry and gitea) that could be targeted for Iron Bank ARM support as a priority.  

Reference on where to begin:
https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/shift/pack/-/blob/master/Earthfile#L112

---

Migrated from https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/2

**Comment by RothAndrew** [comment]
@jeff-mccoy will #237 close this?

**Comment by jeff-mccoy** [comment]
yes multi-arch support is in now, though IB does not support ARM at all and they are saying several months
