### ISSUE TITLE
Use cosign V2 in Zarf

### ISSUE THREAD

**Issue by alinalex1392** [defenseunicorns/zarf#2019]
### Details
We use zarf as a lib in our project and we also have an automatic dependency update system running daily on our side. The dependency update broke because Zarf relies on the github.com/sigstore/cosign@v1.13.1 which depends on go-securesystemslib@v0.4.0.
The latest version for go-securesystemslib is v0.7.0. The latest version of github.com/sigstore/cosign that is v2.2.0, depend on the go-securesystemslib@v0.7.0.

### Expected result
I wat from Zarf to upgrade cosign from v1.13.1 to v.2.2.0.

**Comment by Racer159** [comment]
Thanks for the issue - we are tracking this but haven't completed the migration (yet) - there are still some examples and docs that need to be updated (despite `sget` being deprecated for a few Zarf versions now).  I'll keep this issue open though as we work toward its full removal.
