### ISSUE TITLE
Basic composability, starting with Flux

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#208]
Add support for "composable zarf packages".  This will require syntax change to the zarf package definitions as well as code changes to support.

Tasks:
- [x] Define zarf.yaml specification change, should be agreed upon by the team overall
- [ ] Require component-to-component mapping to keep things sane
- [x] Syntax on the producer side (package authors) should clearly state this is an import/inclusion of other package component data
- [x] Should be completely transparent on the consumer (package deployer) side.  The component tree should be flattened during `zarf package create` so that no changes are needed for `zarf package deploy`.  
- [x] There should be no makefile or other dependencies for package producers or consumers, it should all be done natively through the zarf cli
- [x] This feature can be limited in scope to local packages/components only for now and a new issue added for remote package/component support
- [x] E2E tests should be created to demonstrate a basic composite package

**Comment by mike-winberry** [comment]
Need to discuss the initial hosting of composable packages such as flux. Right now it is working as an external package and I am going to create some examples and documentation on using it, but without a current way to host the package (external repo, s3 etc...) the package will have to be created locally.

**Comment by jeff-mccoy** [comment]
One thing I've been thinking about for that is we try to require shasums for other remote resources...until we have some type of singling or attestation, we may need to stick with local only.  Realize that's not ideal from UX, but I think we have a responsibility to protect producers/consumers too.

**Comment by RothAndrew** [comment]
Where do we want to put pre-built packages? I see this as the beginnings of the "Zarf Appstore". What do you guys think about either:
- A new repo just for this Flux package
    - Would be less DRY but easier to have separate release lifecycles for different pre-built packages
- A new repo that will have all pre-built packages
    - More DRY, but more "monorepo" which is a pattern I'm not a huge fan of

**Comment by mike-winberry** [comment]
Moved to https://github.com/defenseunicorns/zarf-package-flux

**Comment by mike-winberry** [comment]
TODO: 
- [ ] validate with team the confirm imported package behavior and types changes.
- [ ]  Handle duplicate imports from nested packages. 
- [ ] Integration tests.
- [ ] Clean up

**Comment by tukaanimhaka** [comment]
Maybe an example on the docs would be good to have...
