### ISSUE TITLE
`zarf package deploy` broken when using gitops with repos that use `@tag` notation

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#210]
When in when using gitops-service, repos with `@tag` notation fail to resolve when running `zarf package deploy`. This fixes it. I'm guessing what is going on is that the error that is being returned doesn't affect the functionality of the checkout, so it should just be ignored instead of acted on, but you guys are closer to this than I am so feel free to poke holes in it.

![image](https://user-images.githubusercontent.com/16000938/146108516-4cbe8433-5525-485c-9508-e81c693ca57b.png)

**Comment by jeff-mccoy** [comment]
Do you happen to know if this is a new issue post large merge or just one we'd been seeing?  I don't recall touching the git logic at all

**Comment by RothAndrew** [comment]
https://github.com/defenseunicorns/zarf/commit/92ff8c0cb457ccbcc88ef0a534d4dc2626278dfe#diff-39d8599779b869d99b8abf5260691a02ddb5b421b73b39231e369fd6a654fc09

**Comment by RothAndrew** [comment]
New issue post large merge
