### ISSUE TITLE
Cannot label namespace for zarf to ignore

### ISSUE THREAD

**Issue by SamStenton** [defenseunicorns/zarf#2100]
### Is your feature request related to a problem? Please describe.

We are unable to label a out-of-standard initial namespaces within our managed kubernetes service. This causes `zarf init` to hang and eventually time out on the following:

```
  Copying 1 files
  Waiting for cluster connection (5m0s timeout) (0s)
  Waiting for cluster connection (5m0s timeout)
  Gathering cluster information
  Attempting to bootstrap with the <edacted>/cnabu-docker-local.artifactory.eng.<redacted>/<redacted>/metric-controller:c2d883656e9ff780asdasdasd32423414fdb95a1407132 (1m20s)
```

It would be ideal to be able to pass in a command line argument to ignore some namespaces within `zarf init`.

### Describe the solution you'd like

- **Given** when an initial namespace falls outside of normal naming, and the user cannot update namespace labels
- **When** Running `zarf init`
- **Then** The user can provide namespaces to ignore

**Comment by Shane-UE** [comment]
This issue can be closed, I work with Sam and it turns out we went down a wrong route for this issue. The actual problem I have raised a new issue for:
https://github.com/defenseunicorns/zarf/issues/2110
