### ISSUE TITLE
Variable default value merge issue with v0.31.0

### ISSUE THREAD

**Issue by MxNxPx** [defenseunicorns/zarf#2125]
### Environment
Device and OS: Ubuntu
App version: v0.31.0
Kubernetes distro being used: K3d
Other:

### Steps to reproduce
```bash
mkdir -p reproduce-zarf-issue/{base,overlay}

cat << EOF > reproduce-zarf-issue/base/zarf.yaml
kind: ZarfPackageConfig
metadata:
  name: base

variables:
  - name: VAR
    default: foo
    prompt: false

components:
  - name: test
    required: true
    actions:
      onDeploy:
        before:
          - cmd: |
              echo "\${ZARF_VAR_VAR}"
EOF

cat << EOF > reproduce-zarf-issue/overlay/zarf.yaml
kind: ZarfPackageConfig
metadata:
  name: overlay

variables:
  - name: VAR
    default: bar
    prompt: false

components:
  - name: test
    required: true
    import:
      path: ../base
EOF

zarf package create reproduce-zarf-issue/overlay --confirm
zarf package deploy zarf-package-*.tar.zst --confirm
```

### Expected result

`bar`

### Actual Result

`foo`

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by Noxsios** [comment]
when I wrote the vars + consts merges looks like I had the order wrong for the merge functions:

I had `helpers.MergeSlices(node.XYZ, merged, exists), when it needs to be `helpers.MergeSlices(merged, node.XYZ, exists)`

But I cannot recall what the merge strat is for Vars and Consts, when I re-wrote composition I operated under the assumption it was IfNotExist and would not do deep merging.

cc: @Racer159
