### ISSUE TITLE
Use Iron Bank images for K3s

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#213]
Currently we use images for K3s from GitHub. Our goal is to be all Iron Bank for compliance reasons. The K3s images that we get from `https://github.com/k3s-io/k3s/releases/download/<InsertVersionHere>/k3s-airgap-images-amd64.tar.zst` should be added to Iron Bank and pulled from there instead.

**Comment by jeff-mccoy** [comment]
Closing this for now, will re-evaluate all Iron Bank requirements for the main init package later.
