### ISSUE TITLE
unit tests inconsistent in src/pkg/packager

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/zarf#2136]
### Describe what should be investigated or refactored
unit tests in src/pkg/packager run inconsistently. Running on ubuntu linux go1.21.3 
Sometimes when running go test in src/pkg/packager you tests pass. 
Other times you get. Seemingly around 50/50
```bash
--- FAIL: TestValidateLastNonBreakingVersion (0.00s)
    --- FAIL: TestValidateLastNonBreakingVersion/invalid_semantic_version_(CLI_version) (0.00s)
        common_test.go:231: 
                Error Trace:    /home/austin/code/zarf/src/pkg/packager/common_test.go:231
                Error:          []string{"CLIVersion is set to 'this shouldn't get evaluated when the lastNonBreakingVersion is empty' which can cause issues with package creation and deployment. To avoid such issues, please set the value to the valid semantic version for this version of Zarf."} does not contain "CLIVersion is set to 'invalidSemanticVersion' which can cause issues with package creation and deployment. To avoid such issues, please set the value to the valid semantic version for this version of Zarf."
                Test:           TestValidateLastNonBreakingVersion/invalid_semantic_version_(CLI_version)
```

**Comment by lucasrod16** [comment]
This is a race condition bug. Each sub-test updates the value of the package-level, global variable `config.CLIVersion` concurrently, resulting in this race condtion. Fix for this is to not run the sub-tests (test cases) in parallel. Will have a PR up  to fix this here soon

![Screenshot 2023-11-13 at 12 56 13 PM](https://github.com/defenseunicorns/zarf/assets/87675701/4ae59bec-a7f9-48ed-b57e-ef91c89db7f9)
