### ISSUE TITLE
Make docs-and-schema has different results locally and in CI

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/zarf#2141]
### Environment
Device and OS: Ubuntu linux 
App version: zarf v0.31.1

### Steps to reproduce
1. Run `make docs-and-schema` locally. It creates the docs/2-the-zarf-cli/100-cli-commands/zarf_tools_helm_cm-push.md file
2. Run the Validate Docs and Schema / validate action. It fails because it does not create the docs/2-the-zarf-cli/100-cli-commands/zarf_tools_helm_cm-push.md file file and that shows up in the git diff

### Expected result
I would expect docs/2-the-zarf-cli/100-cli-commands/zarf_tools_helm_cm-push.md file to be created both locally and in CI as `zarf tools helm cm-push` does work.

### Actual Result
docs/2-the-zarf-cli/100-cli-commands/zarf_tools_helm_cm-push.md file is not created in CI

### Visual Proof (screenshots, videos, text, etc)
https://github.com/defenseunicorns/zarf/actions/runs/6854684504/job/18638127926?pr=2075

### Severity/Priority
low

**Comment by Racer159** [comment]
Determined this was due to helm plugins being detected by the Zarf CLI
