### ISSUE TITLE
Make sure node has enough resources available for scheduling injector pod

### ISSUE THREAD

**Issue by corang** [defenseunicorns/zarf#2144]
### Is your feature request related to a problem? Please describe.
When zarf attempts to run the injector since it's tied to a specific node it should check if the node has sufficient resources available, it does not and can end up in a stuck state where the pod is never scheduled if the node doesn't have enough resources available.

### Describe the solution you'd like

- **Given** a cluster with workloads
- **When** zarf is picking a node for the injector pod
- **Then** zarf checks the resource availability on nodes before picking one

**Comment by Racer159** [comment]
The relevant code for this is here:

https://github.com/defenseunicorns/zarf/blob/8763b6b2bf47ded67fb33130161b46c85086ce32/src/pkg/k8s/images.go#L22

And a check that allocatable CPU and Memory `nodeDetails.Status.Allocatable` is higher that the requests for the Pod (`.5` / `64Mi` respectively) would solve this.

https://github.com/defenseunicorns/zarf/blob/8763b6b2bf47ded67fb33130161b46c85086ce32/src/internal/cluster/injector.go#L357

**Comment by chrishorton** [comment]
@Racer159 I added some code to images.go to fix this issue. Semantically - should the Allocatable amount be exclusively higher or greater than/equal to? I'm leaning towards higher for a fudge factor but would appreciate your thoughts.

**Comment by chrishorton** [comment]
Opened https://github.com/defenseunicorns/zarf/pull/2220 for you to check out.

**Comment by Racer159** [comment]
Thanks for the PR! Added some comments / feedback over there.
