### ISSUE TITLE
🕛 👥 - Join the Zarf community meetups - (yes you!)!

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#2202]
**Edit:
--**

We hold our community meetups on the fourth Monday of the month at 1200 MST in the linked gather space!

 https://app.gather.town/invite?token=i5DrbM-WQhO792nXUR7m

**Original:
--**

We would like to restart community meetups in the new year targeting the end of January - if folks have time-preferences please emoji react on the slack thread!

https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1702528750088229

**Comment by dgershman** [comment]
I'm excited about this!  I submitted my response on Slack.

**Comment by Racer159** [comment]
The Zarf community meetup timing has been set! (thanks to those who provided input! Monday won with a split between morning / afternoon)

Please join us on Monday January 22nd at 1200 MST to discuss upcoming changes to Zarf (required -> optional :eyes:), our plans for the future and to meet fellow Zarf users!

This event will take place in our community gather.town space accessible here: https://app.gather.town/invite?token=i5DrbM-WQhO792nXUR7m - feel free to join it at any time to get acquainted with the space - we'll kickoff in the large central room on the Zarf rug.

https://kubernetes.slack.com/archives/C03B6BJAUJ3/p1705447722692329
