### ISSUE TITLE
Refactor Get Images Functions and Clarify `k8s` vs `cluster`

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#2222]
### Describe what should be investigated or refactored
We should move the `GetImagesWithNodes` and `GetAllImages` functions from the `k8s` package into the `cluster` package and consolidate their function signatures into a single public function (such as `cluster.GetImagesFromAvailableNodes`) that can get the images from nodes with available resources.

We should also remove unused receiver functions from the `k8s` package to slim down it's API surface given those functions are not tested by Zarf.

### Links to any relevant code
https://github.com/defenseunicorns/zarf/blob/main/src/pkg/k8s/images.go#L22
https://github.com/defenseunicorns/zarf/blob/main/src/pkg/k8s/images.go#L49

### Additional context
This came out of discussions from https://github.com/defenseunicorns/zarf/pull/2220

**Comment by chrishorton** [comment]
@Racer159 Just had some time to look at this. There's a couple of calls to `k8s.BuildImageMap` in `src/pkg/packager/prepare.go`. Should that and `sortImages`, which is also called in `prepare.go` be moved to the `cluster` package?

**Comment by chrishorton** [comment]
Based off of feedback from @Racer159, moving `sortImages` and `BuildImageMap` into `prepare.go` as they don't depend on anything from the `k8s` package.
