### ISSUE TITLE
Add architecture as a required arg to NewOrasRemote

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/zarf#2240]
### Description
When using Zarf as a library, calling [NewOrasRemote](https://github.com/defenseunicorns/zarf/blob/cf9acb50e5a2240e6bd2af994e5904cd0f73fd55/src/pkg/oci/common.go#L104) requires passing in a [WithArch](https://github.com/defenseunicorns/zarf/blob/cf9acb50e5a2240e6bd2af994e5904cd0f73fd55/src/pkg/oci/common.go#L93) modifer to set the architecture and the underlying `index.json`'s Platform. Since passing in the mod is effectively "required" for interacting with OCI artifacts that have an `index.json` with a Platform (ie. multi-arch OCI artifacts), recommend we make the ocispec's Platform a required arg to `NewOrasRemote`. With the Platform as an arg, Zarf lib users no longer have to remember to pass in the `WithArch` mod because the compiler will catch the error

**Comment by UncleGedd** [comment]
Noting that this may not belong in Zarf but rather in a new common OCI lib

**Comment by Racer159** [comment]
This was completed in #2241
