### ISSUE TITLE
Package Create with Skeleton Image Shows Inaccurate Progress

### ISSUE THREAD

**Issue by dgershman** [defenseunicorns/zarf#2246]
### Environment
Device and OS: MacOS
App version: v0.32.1
Kubernetes distro being used: N/A
Other:

### Steps to reproduce
1. Have a component that uses the OCI skeleton in a zarf.yaml (example: https://github.com/radiusmethod/zarf-init-bigbang/blob/main/zarf.yaml)
2. Run `zarf package create`
3. Observe the progress bar while pulling images show a progress bar that doesn't really make sense 

### Expected result

The progress bar shows something that mathematically makes sense.

### Actual Result

The progress bar shows a progress that is greater than the target.

### Visual Proof (screenshots, videos, text, etc)

![Screenshot 2024-01-23 at 5 34 33 PM](https://github.com/defenseunicorns/zarf/assets/1850811/96706ea4-21a3-4ac6-b93d-57e8592ede13)

### Severity/Priority

Low

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by Noxsios** [comment]
Fixed by @AustinAbro321 in #2235
