### ISSUE TITLE
[Design] Refactor OCI to move it to common library

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/zarf#2251]
### Describe what should be investigated or refactored

Some of the code in `src/pkg/oci` should be refactored to be more generally usable by other projects. The functions will need to be generalized to work with generic OCI packages. The Zarf specific logic will need to be pulled out. The refactored generic OCI code will move to https://github.com/defenseunicorns/pkg.

To start this refactor we will need to create a design doc outlining the structure / goals of the changes.  This should be done in a discussion outlined here: https://github.com/defenseunicorns/zarf/discussions/2286

**Comment by Racer159** [comment]
We should ensure we add unit tests during this migration: https://github.com/defenseunicorns/zarf/issues/1750
