### ISSUE TITLE
Move helpers to common library

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/zarf#2252]
### Describe what should be investigated or refactored

The code in src/pkg/utis/helpers will move to https://github.com/defenseunicorns/pkg. This should be simple as this package has no dependencies on anything in zarf.

**Comment by Racer159** [comment]
Tying this issue to this issue since they might be handleable together: https://github.com/defenseunicorns/zarf/issues/2152

**Comment by Racer159** [comment]
We should ensure we add unit tests during this migration: https://github.com/defenseunicorns/zarf/issues/1750
