### ISSUE TITLE
Refactor K8s / cluster code to move it to common library

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/zarf#2254]
### Describe what should be investigated or refactored

The code in src/pkg/cluster and src/pkg/k8s should be refactored to used by projects generically. The functions will need to be generalized to be useful for projects interacting with kubernetes. The zarf specific logic will need to be pulled out. The refactored code will move to https://github.com/defenseunicorns/pkg.

**Comment by Racer159** [comment]
We should ensure we add unit tests during this migration: https://github.com/defenseunicorns/zarf/issues/1750

**Comment by AustinAbro321** [comment]
After discussions with team, we do not want to move this to a separate common library as both are thin wrappers over more generic widely used packages
