### ISSUE TITLE
Manifest w/Symlink Failures

### ISSUE THREAD

**Issue by dgershman** [defenseunicorns/zarf#2255]
### Environment
Device and OS: N/A
App version: v0.32.1
Kubernetes distro being used: N/A
Other: N/A

### Steps to reproduce
1. Have a manifest (or chart), that has a symlink in it.  For example P1 Big Bang Keycloak.
2. `zarf package create ...`

### Expected result

That the package builds.

### Actual Result

The package build fails.

### Visual Proof (screenshots, videos, text, etc)

![Screenshot 2024-01-24 at 2 25 30 PM](https://github.com/defenseunicorns/zarf/assets/1850811/d080b54c-729c-4e00-9353-b10c2612faf9)

### Severity/Priority

High (there isn't a known way to work around this).

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by vvarga007** [comment]
I have the exact same problem. Any known workaround?

**Comment by dgershman** [comment]
> I have the exact same problem. Any known workaround?

There is an open PR that is close to resolution.  https://github.com/defenseunicorns/zarf/pull/2256
