### ISSUE TITLE
Intro/Outro video content for Zarf Doom Deployment video

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#229]
Outcome: We want to produce a high-quality/professional intro and outro that bookend the Doom deployment YouTube tutorial video. Basic premise is "Hi, I'm Mallory Grim with Defense Unicorns. Welcome to our Zarf Tutorial video series. In this video we are going to use Zarf to deploy the hit 1993 game Doom to a 'bring your own' Kubernetes cluster"

Background: We want to try to maximize reusability by having the content that won't change be separate from the content that will change as changes are made to the Zarf product. If everything were all one video it would all need to be reshot whenever a user-facing change is made to Zarf in order to keep it up to date.

Acceptance Criteria:
- @mgrim2 / @edengebrezgi to fill in more details

Notes:
- We like [this video by Confluent](https://www.youtube.com/watch?v=B5j3uNBH8X4&t=4s) as an example of kinda like what "feel" we are looking for
- Target finish date: January 18

**Comment by mgrim2** [comment]
Have the links to the recorded intro/outro. Would like feedback/review from @Madeline-UX and @RothAndrew 
https://drive.google.com/drive/folders/1HbLjCsvh0rxrUAKlDXmUozOTTK_ODztk?usp=sharing

**Comment by RothAndrew** [comment]
Looking at this now
