### ISSUE TITLE
Implement cryptographic validation of all payload and metadata in a zarf package

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#23]
Implement hashing/signing for all elements of the package to ensure authenticity and integrity of the artifacts.

---

Migrated from https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/36

**Comment by JasonvanBrackel** [comment]
@Racer159 Are you actively working on this?  If so could you please move it to doing now on the project board?  I may get rid of thing if we don't fine value in it long term, but I like the visual nature of it.

**Comment by JasonvanBrackel** [comment]
https://github.com/defenseunicorns/zarf/issues/23 May be related / be a subtask of this.

**Comment by Racer159** [comment]
Dropped myself as an assignee, this is still a backlog task, I just added myself to not forget about it at the time
