### ISSUE TITLE
Create Zarf Product Website 

### ISSUE THREAD

**Issue by mgrim2** [defenseunicorns/zarf#230]
Outcome: We want to have a website dedicated solely to the open-source project Zarf. This website will contain all the details about Zarf functionality, how to contribute, contributors, partners, etc. DU website will have a high-level overview of Zarf and a link to the Zarf website. 

Background: 
Since Zarf is an open-source project, we know its ownership may change. Therefore, we would like a dedicated product website that is separate from the DU website. 

Acceptance Criteria:
- A single resource for developers to discover, learn, and contribute to Zarf. 
- A published website with a push goal of SEO landing us at the top of Google.  

Notes:
- Examples of great open-source websites (Flux, Argo)

Timeline: Mid May

**Comment by RothAndrew** [comment]
Notes from last refinement session on high-level desired outcomes for the Zarf website:

- Technical docs site
- Training videos
- Making it pretty
- Good tutorials
- Tie-in with Zarf UI

**Comment by jeff-mccoy** [comment]
Closing this, future work will be tracked in that project: https://github.com/defenseunicorns/zarf-website/issues
