### ISSUE TITLE
Feat: Better error messaging when a component is not found by a flavored component exists

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/zarf#2325]
### Is your feature request related to a problem? Please describe.
As Ezra when I try to create a package that is importing components, but I don't set the flavor or the architecture required by the component I find the error message zarf gives confusing.
`Failed to create package: component "istio-controlplane" not found in "../../src/istio"`

You can see an example of this by running `zarf package create` with no parameters on this package https://github.com/defenseunicorns/uds-core/tree/main/packages/standard

### Describe the solution you'd like

- **Given** I have a zarf package importing flavored components
- **When** I run `zarf package create` with no parameters
- **Then** I get an error message signalling that it's possible a component exists it, but it is not compatible.

**Comment by chrishorton** [comment]
Found the relevant code here: [https://github.com/defenseunicorns/zarf/blob/1ec88490121cf8ec1ae0ce402691fc3c8f663681/src/pkg/packager/composer/list.go#L205](composer/list.go)
Are you suggesting changing the error message itself or adding new code to track if an incompatible component might be missing?

**Comment by chrishorton** [comment]
Came up with this message: 
`componentNotFound := "Component %q not found in %q satisfying %q. It's possible a component exists but it is not compatible with the current architecture or flavor."`

If this sounds good, I'll create a PR for it.

**Comment by AustinAbro321** [comment]
Sorry @chrishorton on second thought the brevity of the first message is probably better, going to close this.
