### ISSUE TITLE
`--max-package-size` Flag fails to split zarf package, Impacts package integrity

### ISSUE THREAD

**Issue by tmnolkemper** [defenseunicorns/zarf#2326]
### Environment
Device and OS: Apple Macbook Pro, MacOS Sonoma 14.3.1 
App version: 0.32.3
Kubernetes distro being used: k3s
Other:

### Steps to reproduce
1. Run `zarf package create --confirm --max-package-size=4500 --log-level=info`

### Expected result
Package compiles and separates into equal parts at/below set size limit, package can be inspected and deployed with `zarf package inspect` and `zarf package deploy` commands. Package recompiles into single part when said commands are run. 

### Actual Result
Package compiles into inequal parts (one large `part.000` and several smaller parts). Package cannot be inspected or deployed because package integrity check fails. Package does not recompile into single `tar.zst` when `zarf package inspect` or `zarf package deploy` are ran against it. 

### Visual Proof (screenshots, videos, text, etc)
<img width="903" alt="Screenshot 2024-02-22 at 11 26 09 AM" src="https://github.com/defenseunicorns/zarf/assets/107516657/dbc28e73-b2fb-4ce5-aca3-88b21eae18cb">
<img width="1065" alt="Screenshot 2024-02-22 at 11 26 35 AM" src="https://github.com/defenseunicorns/zarf/assets/107516657/8b198250-6e89-4ab9-9863-1d5709acc8a6">
<img width="1065" alt="Screenshot 2024-02-22 at 11 27 38 AM" src="https://github.com/defenseunicorns/zarf/assets/107516657/91aa60b5-0f8d-430c-b390-1f7c6b1898d9">

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by Noxsios** [comment]
Closing as this should be fixed now in Zarf v0.32.4+
