### ISSUE TITLE
Explore adding configurable http timeouts

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#2331]
### Is your feature request related to a problem? Please describe.

We should explore adding configurable timeouts to Zarf's operations so that operations can be optimized for different environments that may be more austere.

### Describe the solution you'd like

Ideally there would be a way to configure the default Transport timeouts that are used across Zarf - we should likely construct a version of Transport that we can use throughout the application and let these be configured through env vars or other configuration.

### Describe alternatives you've considered
We could leave the timeouts as is, but this may reduce some of Zarf's applicability to very austere environments.

### Additional context
This came out of discussions on #2319 when adding an http request header timeout.

**Comment by Noxsios** [comment]
Closed by #2345
