### ISSUE TITLE
Upgrade Big Bang Example to latest version

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#235]
As a new user of Zarf, I would like to have a newer version of Big Bang as the default example.

Current version is 1.17.0. 

https://github.com/defenseunicorns/zarf/blob/master/examples/big-bang/zarf.yaml#L38

**Comment by RothAndrew** [comment]
@matt-strong are you still actively working on this?

**Comment by matt-strong** [comment]
@RothAndrew I just pushed my attempt at it to the upgrade_bb branch, but it looked like the mega-PR changed some of those files, so I halted on it.

**Comment by RothAndrew** [comment]
Next time please push up a Draft PR rather than leaving it local-only.

If you want to keep working on it that is fine. If this work gets merged before the mega PR we can merge those changes in.

**Comment by matt-strong** [comment]
Sure thing

**Comment by RothAndrew** [comment]
@matt-strong is this something you're currently working on? If not that's fine, I just want to make sure the kanban board reflects reality. If you aren't, I'll move it back to "Planned".
