### ISSUE TITLE
OCI Image Index for Zarf packages doesn't include the mediaType attribute

### ISSUE THREAD

**Issue by mdaizcorbe** [defenseunicorns/zarf#2351]
### Describe what should be investigated or refactored
Currently the OCI Image Index for Zarf packages doesn't include the mediaType attribute.  While not technically required the OCI spec says it "SHOULD" be used (https://github.com/opencontainers/image-spec/blob/main/image-index.md).

### Links to any relevant code
None.

### Additional context
Currently the Sonatype Nexus Repository cleanup script expects the mediaType to be present in the OCI Image Index.  When isn't present, the cleanup doesn't iterate through the listed manifests in the image index and thus treats the actual manifest for the Zarf package as orphaned and deletes it.  Sonatype accepts this is a bug and has an issue for it but doesn't have an ETA for a fix.  This is preventing us from using the latest Zarf to publish.  While this is a fix to work around someone else's bug, since the spec says it should be set it feels like a good addition regardless.

**Comment by AustinAbro321** [comment]
Great catch, this will be fixed by #2235 which will likely be included in the next release

**Comment by AustinAbro321** [comment]
Ah I see you opened a PR, even better. Thanks!
