### ISSUE TITLE
Prompt for password during zarf registry login

### ISSUE THREAD

**Issue by grubjack** [defenseunicorns/zarf#2377]
### Is your feature request related to a problem? Please describe.
Add possibility to enter a password for registry from stdin with prompt
### Describe the solution you'd like

- **Given** Username and password for some registry
- **When** `zarf tools registry login -u username -p`
- **Then** Prompt to enter password ( `Password: ******` )

### Describe alternatives you've considered
```
zarf tools registry login -u username --password-stdin
Password: *******

echo -n "password" | zarf tools registry login -u username --password-stdin
```

**Comment by Noxsios** [comment]
Hi @grubjack, `zarf tools registry login` is the [`crane auth login` command](https://github.com/google/go-containerregistry/blob/main/cmd/crane/README.md) embedded into Zarf. As such we don't focus on features on an upstream project unless it is breaking current and required functionality.

Please open this issue there!
