### ISSUE TITLE
Add `zarf tools yq` (or similar) for easily parsing yaml files

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#2384]
### Is your feature request related to a problem? Please describe.
**As** Ezra **I want** to be able to use `yq` with Zarf **so that** I can quickly pull information out of YAML files / Kubernetes Manifests within actions.

### Describe the solution you'd like

- **Given** I have a manifest I want to pull information from
- **When** I run `zarf tools yq` 
- **Then** I have access to the `yq` CLI: https://github.com/mikefarah/yq

### Describe alternatives you've considered
We could explore other libraries but the main `yq` cli is already written in go - it could also be put behind another layer rather than at the root of `tools` (to pave the way for potentially more tools like `jq`)

### Additional context
This comes from us wanting to reduce dependencies within Software Factory and open up more options when using UDS Run.

**Comment by Noxsios** [comment]
Some notes:

```go
// SPDX-License-Identifier: Apache-2.0
// SPDX-FileCopyrightText: 2021-Present The Zarf Authors

// Package tools contains the CLI commands for Zarf.
package tools

import (
	yqCLI "github.com/mikefarah/yq/v4/cmd"
)

func init() {
	yqCmd := yqCLI.New()
	yqCmd.Use = "yq"

	toolsCmd.AddCommand(yqCmd)
}

```

Successfully embeds yq under `zarf tools yq`. `zarf tools yq --version` works properly.

Some things I wasn't able to grok about https://github.com/mikefarah/yq/blob/master/yq.go that may cause issues w/ usage. More research required.

**Comment by zachariahmiller** [comment]
Thanks! I had already gotten that far locally and then sidetracked trying to track down why it made the package so much larger (tldr I wasn't building on Linux). Back to trying to put in doc generation and test things. Will need to try to account for making sure per your note that there aren't issues with certain commands running.

**Comment by fallenpixel** [comment]
Super interested in this hitting main. Happy to test once ready.
