### ISSUE TITLE
Design Research for Zarf Website

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#240]
- [x] Competitive analysis
- [x] Content wireframes
- [x] Mood board
- [x] Pick UI component library (MUI proposed)

**Comment by Madeline-UX** [comment]
@RothAndrew  I recommend the two remaining tasks on this card be turned into individual stories. I will create those stories and add them to the backlog

**Comment by jeff-mccoy** [comment]
Closing now, all Zarf website issues are in their repo:  https://github.com/defenseunicorns/zarf-website
