### ISSUE TITLE
How to handle helm charts in a flux deployment

### ISSUE THREAD

**Issue by shanewhite97** [defenseunicorns/zarf#2401]
### Is your feature request related to a problem? Please describe.
No

### Describe the solution you'd like
I am sorry if this is not the place for this, but I am wondering how people are handling flux deployments that contain helm charts? I've been looking through the documentation and it looks like zarf can deploy a helm chart which works great, but that's not what I'd like to do, please see the scenario below:

Given I have a flux deployment that is being managed by zarf
When the flux deployment has a requirement to reach out to a HelmRepository for a chart
Then I would expect zarf to have those helm charts added to maybe the internal registry and consumed from then on

I am just wondering how people are handling this at the moment? Or is this a selection of FR waiting to be implemented? Below are some other links I have considered...
https://github.com/defenseunicorns/zarf/issues/2114

https://github.com/defenseunicorns/zarf/issues/1974

https://github.com/defenseunicorns/zarf/issues/1337

**Comment by AustinAbro321** [comment]
This is still blocked on the flux side as trying to connect to the internal registry for login is still going over https when repo.spec.insecure is set to true. 

 We have created a PR on the flux side and are awaiting a response from them https://github.com/fluxcd/source-controller/pull/1412

**Comment by Shane-UE** [comment]
Yh that's fine, I am happy to wait for that to be unblocked, was just curious if anyone had a creative solution around it for the time being?

**Comment by joelcomp1** [comment]
what I have done to get around the issue (and I kind of hate but it works) is do make a custom zarf init package with Chart Museum, then load my helm charts in my zarf packages via custom onCreate jobs to basically package and curl into Chart Museum then point Zarf to Chart Museum....works great but has a lot of extra steps...

**Comment by shanewhite97** [comment]
Okay interesting, so the way we have got around it for the time being is to download all the helm charts we want, push them to a GitRepository, and then use a Kustomize Patch to change all "HelmRepository" references to "GitRepository" references with the correct path.

Just wondered if there were any better ways to achieve this, thanks for the input!
