### ISSUE TITLE
Remove bigbang "private" key from git history

### ISSUE THREAD

**Issue by blancharda** [defenseunicorns/zarf#2417]
### Overview
A legacy Zarf Big Bang example included a private key for configuring Istio TLS.
Bigbang intentionally checks [these keys in publicly](https://repo1.dso.mil/big-bang/bigbang/-/blob/master/chart/ingress-certs.yaml?ref_type=heads) for use in local dev and examples.

The key (from ~2022) is certainly expired, but can still flag in history scans when teams look into adopting Zarf.

We should consider scrubbing it from the history to reduce potential confusion and concern.

### Details
The commit SHAs (listed below) can be identified with:
`git log --all --full-history -- "**/bigbangdev.key*"`

* b051061a72374894562d21b77d54bbf065b384af
* 80c4ed1986b3d40f587e8f915a1e9bba5931d7e2

> NOTE: There may be other similar commits that are worth tracking down, these are obviously specific to this particular file/example

**Comment by lucasrod16** [comment]
Closing this because this is not a security concern. The private key was for localhost and is long expired
