### ISSUE TITLE
Handling SIGINT and sequential deployments

### ISSUE THREAD

**Issue by andrewg-xyz** [defenseunicorns/zarf#2520]
### Environment
Device and OS: M2 Max, OSX Sonoma 14.4.1
App version: v0.33.0
Kubernetes distro being used: k3d (uds deploy k3d-core-slim-dev:0.21.1)
Other:

### Steps to reproduce
1. `zarf package deploy ...` My app has an error that fails deployment "0 out of 1 expected pods are ready"
2. SIGINT (ctrl+c) to stop the `zarf package deploy`
3. (make updates, rebuild zarf package) and run `zarf package deploy`

### Expected result
The interruption is handled and future `zarf package deploy` function.

### Actual Result
My cluster has a helm CR with a status of `pending-install` Which prevents sequential `zarf package deploy`-ments of my package (once I've fixed the error)

Sequential deploys fail/retry with `WARNING  Retrying (1/3) in 5s: unable to complete the helm chart install/upgrade: another operation                                                               (install/upgrade/rollback) is in progress`  

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/defenseunicorns/zarf/assets/46836330/c9563610-1259-47a8-96fa-bce917d6b1ce)
![image](https://github.com/defenseunicorns/zarf/assets/46836330/64b92feb-8d00-483c-9bc1-b8e0103aefd6)
![image](https://github.com/defenseunicorns/zarf/assets/46836330/07c54d1c-9fb8-4f82-aaf9-1944a8502921)

### Additional Context
workaround is to manually remove the helm CR and clean up the failed deployment.

**Comment by phillebaba** [comment]
This should be covered by #2505. It is good however to have a specific example of why this is needed.

**Comment by lucasrod16** [comment]
@andrewg-xyz I am not sure there is a way Zarf can reliably guarantee cleanup of resources when a deployment is canceled with a SIGINT. Zarf uses the Helm SDK to cleanup resources on a best effort basis for failed upgrades and rollbacks, but it is risky for Zarf to start removing resources from the cluster outside of the Helm SDK on a failed deployment in my opinion.

I would recommend running `zarf package remove` to cleanup the failed deployment before attempting re-deployment

**Comment by andrewg-xyz** [comment]
Thanks - I'm good to close with the context. I'll keep in mind as I interact with similar situations.
