### ISSUE TITLE
Zarf deployments loading images from incorrect location

### ISSUE THREAD

**Issue by robmcelvenny** [defenseunicorns/zarf#2539]
### Environment
Device and OS: VM Ware Horizon Client, RHEL8
App version: v0.33.0
Kubernetes distro being used: v1.28.8+rke2r1

### Steps to reproduce
1. zarf init --storage-class local-path --confirm
2. Find app helm chart, create zarf file, zarf.yaml should point to registry `myregistry.x.com/image:x`
3. zarf package create
4. zarf package deploy <zarf_package>

### Expected result
zarf deploys package and image is downloaded and sent to 127.0.0.1:31999/my_image, zarf registry is available and zarf should have no issue assign / locating the image

### Actual Result
zarf deploys package and image to 127.0.0.1:31999 but the registry is somehow attaching 127.0.0.1:31999/library/my_image:latest-zarf-3128432784

### Visual Proof (screenshots, videos, text, etc)
![image](https://github.com/defenseunicorns/zarf/assets/831191/2d1b4a68-0236-4fae-a3d3-7d451e107efd)

### Severity/Priority
High

### Additional Context

Behind corporate proxy.
Have to specify the image by editing the pod itself e.g. Image: <127.0.0.1:31999/my_image:latest> to correct the issue, which finds the correct image inside of the zarf registry.

**Comment by lucasrod16** [comment]
Hi @robmcelvenny, thanks for reporting this issue. Could you please share a basic `zarf.yaml` file that will allow us to reproduce the error? This will help us understand and fix the problem. Thanks!

**Comment by robmcelvenny** [comment]
Sure, this is what the zarf looks like, the image is located originally in a nexus repository, it downloads the image from the nexus repo first, then creates the zarf package. I suspect this might be why the issue is occurring.

# yaml-language-server: $schema=https://raw.githubusercontent.com/defenseunicorns/zarf/v0.33.0/zarf.schema.json
kind: ZarfPackageConfig

metadata:
  name: omitted
  description: auto-generated using `zarf dev generate`
  version: <omitted_version>

components:
  - name: <omitted>
    required: true
    charts:
      - name: <omitted>
        version: <omitted_version>
        localPath: chart/
        namespace: raptor
    images:
      - nexus.myregistry.com/myapp:<version>

**Comment by lucasrod16** [comment]
> Sure, this is what the zarf looks like, the image is located originally in a nexus repository, it downloads the image from the nexus repo first, then creates the zarf package. I suspect this might be why the issue is occurring.
> 
> ```
> kind: ZarfPackageConfig
> 
> metadata:
>   name: omitted
>   description: auto-generated using `zarf dev generate`
>   version: <omitted_version>
> 
> components:
>   - name: <omitted>
>     required: true
>     charts:
>       - name: <omitted>
>         version: <omitted_version>
>         localPath: chart/
>         namespace: raptor
>     images:
>       - nexus.myregistry.com/myapp:<version>
> ```

It is expected behavior that Zarf pulls any images defined in the `zarf.yaml` and includes them in the final `zarf-package-*.tar.zst`. When you run `zarf p deploy` to deploy the package, those images are then pushed to the Zarf registry, and the Zarf agent mutates the Pod specs in your manifests to pull from the internal Zarf registry.

Are you only seeing this issue with images stored in Nexus?

**Comment by AustinAbro321** [comment]
@robmcelvenny Interesting issue, "library" is added to images when they are pulled from docker.io. docker.io is the default place for images to be pulled from if a registry is not specified. If you have an image `my_image:latest` in a manifest / helm cahrt when the image is mutated it becomes -> `127.0.0.1:31999/library/my_image:latest-zarf-_checksum_`.

Can you double check that the image in your helmchart points to the nexus registry and not dockerhub / doesn't have a registry?

**Comment by robmcelvenny** [comment]
@AustinAbro321 @lucasrod16 ok I think I am starting to grok what is occurring, hypothetically or theoretically what might be happening is this:

Kubernetes RKE2 is being deployed via an Ansible playbook and I believe the registries are being changed up, so when docker.io is detected it would point to something like nexus.blah.com/registry, maybe zarf is somehow getting this mixed up and mutating it.

**Comment by AustinAbro321** [comment]
Issue was that the registry was not specified and was defaulting to dockerhub

**Comment by robmcelvenny** [comment]
Solution is to modify your deployment within helm chart values.yaml and update the image to point to the correct image repository.

e.g. 

```
image:
  repository: nexus.myrepo.com/image_name
  tag: image_tag
```

deployments should no longer automatically append the `/library/` to your images.

**Comment by lucasrod16** [comment]
@robmcelvenny you may want to consider using `zarf dev deploy` when developing Zarf packages to get quick feedback on your package. `zarf dev deploy` deploys your package using the upstream images defined in your manifests/charts, so there is no pulling/pushing/mutating of images by Zarf. In this case, you likely would have got an error because the image defined in your manifest does not exist since the registry was not defined. Could help make debugging easier for situations like this

https://docs.zarf.dev/commands/zarf_dev_deploy

**Comment by lucasrod16** [comment]
This is also a good reference on image names:

https://kubernetes.io/docs/concepts/containers/images/#image-names

Worth noting:

> If you don't specify a registry hostname, Kubernetes assumes that you mean the [Docker public registry](https://hub.docker.com/).
