### ISSUE TITLE
Zarf dev lint warns that cosign signatures are not pinned with a digest 

### ISSUE THREAD

**Issue by AustinAbro321** [defenseunicorns/zarf#2577]
Currently running `zarf dev lint` against a `zarf.yaml` with a cosign signature will give a warning like below. It's redundant as cosign signatures are unique to an image sha, and you will not have two cosign signatures at the same image
```
Image not pinned with digest - ghcr.io/stefanprodan/podinfo:sha256-57a654ace69ec02ba8973093b6a786faa15640575fbf0dbb603db55aca2ccec8.sig
```

If an image has ".sig" at the end, it should simply be ignored from lint

**Comment by jasonwashburn** [comment]
I'd like to take this one

**Comment by jasonwashburn** [comment]
@AustinAbro321 Would the preference for this to treat signatures effectively as pinned (`isPinnedImage`)  or rather to add separate handling i.e. `isSignedImage` ?
