### ISSUE TITLE
Remove PLG logging stack from init package

### ISSUE THREAD

**Issue by lucasrod16** [defenseunicorns/zarf#2582]
### Describe what should be investigated or refactored
Hi everyone,

We're currently considering some changes to the Zarf init package, specifically regarding the Promtail, Loki, and Grafana (PLG) logging stack. Our team believes that this logging stack isn't widely used in production by our users. However, before making any decisions, we want to hear from you to understand its actual usage and importance.

### Links to any relevant code
https://github.com/defenseunicorns/zarf/tree/main/packages/logging-pgl
https://github.com/defenseunicorns/zarf/blob/e6ac3d5fc65797d1d2872ece3fde69968553b294/zarf.yaml#L35-L38

### How You Can Help
Your feedback is essential for us to decide whether to continue supporting the PLG logging stack. If we find that it's not being used much, we intend to remove it to focus our resources on other areas that provide more value. On the other hand, if many of you rely on this stack, we want to make sure we continue to support and improve it.

1. Comment Below: Please share your experiences using the PLG logging stack. Specifically:
    - Have you ever used it?
    - Do you use it in production? If so, how critical is it to your operations?
    - What do you like or dislike about it?
    - Are there any alternatives you prefer or recommend?
    
1. Vote: If you see comments that reflect your thoughts, give them a 👍 to help us gauge consensus.

### Timeline

We're looking to gather feedback over the next few weeks. Your thoughts would be super helpful to us! Thanks in advance for taking the time to share.

**Comment by andrewg-xyz** [comment]
I have only used it for demo purposes, showcasing the power of zarf packages. My preferred alternative would be a dedicated purpose built package that would include monitoring stack among other tools.

**Comment by docandrew** [comment]
In our deployments we use the PLG stack from other packages and do not rely on the one bundled with Zarf init. We'd prefer a smaller init package without these bundled utilities.

**Comment by RothAndrew** [comment]
Have never used it. I always want something as small as possible, or if I want a logging stack I'm using BB / DUBBD / UDS Core

**Comment by beholdenkey** [comment]
I have rarely used it. Typically package internal logging and monitoring stack and use that.

**Comment by WeaponX314** [comment]
Yeah, I don't use it either. Not because it doesn't work, just that it didn't fit our needs. Was fine for testing so maybe keep it around as an example package recipe?
