### ISSUE TITLE
lib: Remove mandatory PublicKeyPath from OCISource

### ISSUE THREAD

**Issue by UncleGedd** [defenseunicorns/zarf#2583]
### Is your feature request related to a problem? Please describe.

When calling `LoadPackageMetadata` on an `OCISource` I have to populate the `PublicKeyPath` even if I don't have a public key. For example:

```
	source := zarfSources.OCISource{
		ZarfPackageOptions: &zarfTypes.ZarfPackageOptions{
			PublicKeyPath: "",
		},
		Remote: remote,
	}

	tmpDir, err := zarfUtils.MakeTempDir(config.CommonOptions.TempDirectory)
	if err != nil {
		return nil, err
	}
	pkgPaths := layout.New(tmpDir)
	zarfPkg, _, err := source.LoadPackageMetadata(pkgPaths, false, true)
	if err != nil {
		return nil, err
	}
```

If I don't provide a `PublicKeyPath` in the options I end up with a nil pointer error when `s.PublicKeyPath` gets referenced [here](https://github.com/defenseunicorns/zarf/blob/e6ac3d5fc65797d1d2872ece3fde69968553b294/src/pkg/packager/sources/oci.go#L148-L149).

### Describe the solution you'd like

Referring to [this](https://github.com/defenseunicorns/zarf/blob/e6ac3d5fc65797d1d2872ece3fde69968553b294/src/pkg/packager/sources/oci.go#L148-L149) block of code in Zarf

- **Given** I pass `skipValidation` as "true" into the `LoadPackageMetadata` fn
- **Then** the `ValidatePackageSignature` functions isn't called

I think this is as easy as moving `skipValidation` in the referenced block of code up

**Comment by UncleGedd** [comment]
Happy to implement if you all are ok with the proposed solution

**Comment by AustinAbro321** [comment]
Yup technically it will change behavior a bit, but IMO it will make things read better so I think it's a good change.
Also you would only actually have to initialize it like below since ZarfPackageOptions is the pointer. I think that probably should have been a value, but we can change that at a different time. 
```
	source := zarfSources.OCISource{
		ZarfPackageOptions: &zarfTypes.ZarfPackageOptions{},
		Remote: remote,
	}
```

**Comment by UncleGedd** [comment]
> if you wanted to keep current behavior you could initialize an empty ZarfPackageOptions{}

That's super easy, we'll just do it that way
