### ISSUE TITLE
clean up ctx.TODO -> ctx.Background 

### ISSUE THREAD

**Issue by schristoff-du** [defenseunicorns/zarf#2592]
### Describe what should be investigated or refactored
We currently have a `context.TODO()` in 26 places in the code, these should be looked at to see if they should be a `context.Background()` or if we can update these functions to take in contexts and use existing context.

**Comment by phillebaba** [comment]
Related to #2594

**Comment by ujjwal405** [comment]
can i work on this issue?

**Comment by sshiv5768** [comment]
HI @phillebaba I want to work on this issue, can you asign me this issue.

**Comment by phillebaba** [comment]
Closing in favor of #2365
