### ISSUE TITLE
docs(site): bad link in zarf tutorial - Creating a Zarf Package

### ISSUE THREAD

**Issue by joelmccoy** [defenseunicorns/zarf#2643]
Link on this [site](https://docs.zarf.dev/tutorials/0-creating-a-zarf-package/) is broken

![image](https://github.com/defenseunicorns/zarf/assets/14078350/57750520-89ff-4913-be0e-373e3a1f5e7b)
[what happens to resources that exist before Zarf init](https://docs.zarf.dev/faq#what-happens-to-resources-that-exist-in-the-cluster-before-zarf-init)

Takes you to an invalid FAQ.  As a new user I was trying to figure out what happens to preexisting resources and there doesn't seem to be an FAQ for this.

Potential Fixes:
1. Add in an FAQ and fix this link
2. Or point to another page for this info (but I couldn't directly find this, the best I found was [here](https://docs.zarf.dev/tutorials/9-resource-adoption/#_top) and it doesn't really answer what happens to preexisting resources directly)
3. Remove this note all together so there is less confusion

PS: I've been going through some Zarf documentation and tutorials as a new member of Defense Unicorns.  I am finding some broken links/things that could be cleaned up as I go along.  If there is a better feedback mechanism other than opening a github issue let me know.

**Comment by AustinAbro321** [comment]
Really appreciate you looking through. Issues are good, we should also have a link checker in CI to ensure we're not using any broken links. Made an issue for that #2649
