### ISSUE TITLE
Zarf silently fails to overwrite tagged images in the Zarf Registry

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#2646]
### Environment
App version: Zarf v0.35.0 (latest)
Kubernetes distro being used: k3d

It appears that the image push logic in Zarf is taking a shortcut by checking for a matching image ref/tag to determine if an image already exists in the Zarf registry.  Instead, Zarf should be checking the image's manifest/layer checksums. This results in images not getting pushed to the Zarf registry as a user might expect.

### Steps to reproduce
1. Build a container image and reference that image in a Zarf package
2. Deploy the Zarf package to a cluster
3. Notice the pod does whatever you think it should be doing
4. Modify your Dockerfile so that it is distinctly different BUT build it with the EXACT same tag
5. Rebuild the Zarf package
6. Deploy the new Zarf package to the same cluster
7. Notice that the container within the pod is not showing the changes that you made in step 4

NOTE: If I redo steps 4-6 but change the tag of the image built to something unique, then I get the result I expect and see the modifications I made to my Dockerfile. This tells me that it is not my image that is broken, but something with Zarfs push logic when an image is reusing a tag.

### Expected result
- I expected the pod deployed in step 6 to show signs that it was running the image built in step 4

### Actual Result
- It appears the pod deployed in step 6 is running the image built in step 1

### Visual Proof (screenshots, videos, text, etc)
https://www.loom.com/share/778b91ec25534e2f80d97afa9492edce

### Severity/Priority
High-ish ???. This will hopefully only happen during local package development since it is uncommon for people to reuse tags. That said, while it's uncommon, it's not impossible 😢 

### Additional Context
Add any other context or screenshots about the technical debt here.

**Comment by lucasrod16** [comment]
@YrrepNoj and I chatted about this more in slack. The issue here is that the kubelet is not re-pulling the new image from the registry because of it's default behavior. The fix is to either use no tag at all for the image, or a `:latest` tag

https://kubernetes.io/docs/concepts/containers/images/#updating-images
https://kubernetes.io/docs/concepts/containers/images/#imagepullpolicy-defaulting

> When you (or a controller) submit a new Pod to the API server, your cluster sets the imagePullPolicy field when specific conditions are met:

>  if you omit the imagePullPolicy field, and you specify the digest for the container image, the imagePullPolicy is automatically set to IfNotPresent.

> if you omit the imagePullPolicy field, and the tag for the container image is :latest, imagePullPolicy is automatically set to Always;

>  if you omit the imagePullPolicy field, and you don't specify the tag for the container image, imagePullPolicy is automatically set to Always;

> if you omit the imagePullPolicy field, and you specify the tag for the container image that isn't :latest, the imagePullPolicy is automatically set to IfNotPresent.

https://kubernetes.io/docs/concepts/containers/images/#required-image-pull

> If you would like to always force a pull, you can do one of the following:

> Set the imagePullPolicy of the container to Always.

> Omit the imagePullPolicy and use :latest as the tag for the image to use; Kubernetes will set the policy to Always when you submit the Pod.

> Omit the imagePullPolicy and the tag for the image to use; Kubernetes will set the policy to Always when you submit the Pod.

> Enable the [AlwaysPullImages](https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#alwayspullimages) admission controller.
