### ISSUE TITLE
Update the Big Bang example to do GitOps "correctly"

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#268]
After #237 merges the Big Bang example will once again be functionally equivalent to `kustomize build | kubectl apply -f -` which uses Flux to deploy all the things but doesn't tell Flux to watch a Git repo for changes. We should update the example to have Flux watch a Git repo for changes, so that I can open up a Git repo in Gitea, commit a change, and watch that change be automatically picked up and deployed by Flux.

**Comment by RothAndrew** [comment]
Blocked by #237

**Comment by jeff-mccoy** [comment]
Is this still valid @RothAndrew ?

**Comment by RothAndrew** [comment]
yes

**Comment by jeff-mccoy** [comment]
@RothAndrew what's the status of this, I thought we updated the BB examples already?

**Comment by RothAndrew** [comment]
The BB Core example has not been updated yet to satisfy this issue. Now that the software factory package (a.k.a. DI2-ME) does do it in a way that a git repo is watched by Flux I feel less strongly about it needing to be done in the BB Core example too. It does add a decent amount of complexity.

I would be fine with not doing this work to the BB Core example, as long as we update the readme in that example to add “to see an example of setting up Flux to watch a git repo, see this other repo”

**Comment by jeff-mccoy** [comment]
Closing now, future users searching for this complete example should use https://github.com/defenseunicorns/zarf-package-software-factory.
