### ISSUE TITLE
New E2E test - Debian OS compatibility

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#293]
Outcome:
We want the E2E test suite to include one or more tests that run on Debian so we can test Zarf's compatibility with Debian.

Acceptance Criteria:
* The E2E test suite includes at least one test that runs on Debian
* `zarf init` and `zarf package deploy` are tested on Debian
* Deployment package features to be tested include
    * an image to be pushed to the registry
    * a repo to be pushed to Gitea
    * A deployment that can be tested

**Comment by jeff-mccoy** [comment]
Simplified the AC as a `zarf init` is a `zarf package deploy` and there is nothing gained by testing beyond the initial init phase in each iinux distro.

**Comment by jeff-mccoy** [comment]
Going to close this for now, we already test on Ubuntu (which is debian-based), we will be better-suitded testing major nix distro flavors at this point.
