### ISSUE TITLE
New E2E test - RHEL OS compatibility

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#294]
Outcome:
We want the E2E test suite to include one or more tests that run on RHEL so we can test Zarf's compatibility with RHEL.

Acceptance Criteria:
* The E2E test suite includes at least one test that runs on RHEL
* `zarf init` is tested on RHEL

**Comment by jeff-mccoy** [comment]
Simplified the AC as a `zarf init` is a `zarf package deploy` and there is nothing gained by testing beyond the initial init phase in each iinux distro.

**Comment by jeff-mccoy** [comment]
Work will now be tracked under #559
