### ISSUE TITLE
ASDF plugin for Zarf

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#295]
As a user of Zarf who uses [ASDF](http://asdf-vm.com/) for version management I want the ability to install and manage the version of Zarf using ASDF, so that it is easier to install and switch versions as needed.

**Comment by JasonvanBrackel** [comment]
@RothAndrew @jeff-mccoy Tell me if I'm wrong, but this seems out of the scope of things that Zarf / the Zarf team works on directly.  I'd support making this its own effort/repo if that's something @RothAndrew has cycles to work on, but I don't think it belongs here.  

I'm closing reopen I just have this wrong, and this is critical-path functionality for the future.

**Comment by RothAndrew** [comment]
Doing the ASDF plugin in a different repo is fine, and looks to be the way the vast majority of ASDF plugins are done. Would need to keep the issue here I think until that repo exists though.

ASDF gives 2 big advantages over the already existing Zarf support for Homebrew:

1. I'm able to pick whichever version I want to install and use very easily
2. I can have multiple versions installed at once and pick between them by using a `.tool-versions` file.

I have personal motivation for this as I use ASDF heavily as my package manager of choice whenever it is available, and I have a strong dislike for Homebrew.

Additionally, I do not believe the way we do Zarf in Homebrew is "production-grade" since the user only has the option of installing the latest version. IMO it is great for people getting started with Zarf but when it comes time to use it in production it will fall short.

There is lots of precedent for offering a tool in multiple different package managers, and I'm strongly recommending we make ASDF one of them that gets 1st party support from Defense Unicorns.
