### ISSUE TITLE
Unable to inject seed image on RHEL host.

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#296]
This is likely because RHEL $PATH doesn't include /usr/local/bin by default and that's where we currently put the k3s executable. 

```
WARNING  Unable to inject the seed image from the /tmp/zarf-1741909834/seed-images.tar archive
  DEBUG   exec: "k3s": executable file not found in $PATH
└ (/Users/jon/projects/du/zarf/cli/internal/packager/seed.go:179)
```

This can be resolved by moving the binary to `/sbin` or `/usr/bin`. Additionally, moving where the binary gets placed would mean updating the cleanup script, service, and zarf.yaml to reference the new path.

**Comment by RothAndrew** [comment]
Let me know if there's anything I can do to help with this. It sounds like we want to get this fixed before we release v0.15.0 which we want to do as soon as possible.
