### ISSUE TITLE
Internal io.RecursiveFileList() utility function doesn't handle symbolic links

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#302]
The function `RecursiveFileList( ... )` is supposed to look through a directory and all of its subdirectories to find any files that match a pattern. When given a directory that is a symbolic link to another directory, our utility function fails to return any files, even if there are files that match the regex expression in the linked directory.

----
Simplified Ex)

`/sbin` -> `/usr/sbin`

`$ mv file1 file2 file3 /sbin`

```
$ ls -la /usr/sbin
/usr/sbin
/usr/sbin/file1
/usr/sbin/file2
/usr/sbin/file3
```

`client.RecursiveFileList( '/sbin', 'any file' ) ` -> `empty return` 
`client.RecursiveFileList('/usr/sbin', 'any file')` -> `file1, file2, file3`

For both function calls we expect both to return `file1, file2, file3`.

**Comment by jeff-mccoy** [comment]
Are we using that with symlinks somewhere? We mainly just use that for moving files and and out of the package, which definitely shouldn't have symlinks.

**Comment by YrrepNoj** [comment]
When I was moving the k3s binary from /usr/local/bin to /sbin I was running issues when trying to `zarf destroy` since it wasn't able to find the `zarf-clean-k3s.sh` script.

**Comment by mikevanhemert** [comment]
I am looking at Symwalk from Facebook: https://pkg.go.dev/github.com/facebookgo/symwalk

It works the same as filepath.Walk and should be an easy replacement. Trying it out now.

**Comment by jeff-mccoy** [comment]
Closing as stale, can re-open if users start to encounter this issue.
