### ISSUE TITLE
Zarf v0.14.0 requires deployments to happen from the same directory as init

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#304]
### Environment
* Big beefy EC2 instance running Ubuntu 20.04
* Zarf v0.14.0

### Expected Result

I can run `zarf init` in one folder and run `zarf package deploy` in a different folder

### Actual Result

I have to run `zarf init` and `zarf package deploy` in the same folder (I suspect because of `.zarf-state.yml`)

### Visual Proof

From folder `/root/zarf-package-software-factory/build`

![image](https://user-images.githubusercontent.com/16000938/153101805-ad90f0ea-3565-4f95-bca0-ce4a7f32e03b.png)

From folder `/root` (where `zarf init` was run) after moving the same package over to the `/root` folder

![image](https://user-images.githubusercontent.com/16000938/153101902-8f28d8c8-e195-4931-9f4e-fa9911ca8fe3.png)

### Severity/Priority
Low. This same issue should not occur in v0.15.0, and we aren't supporting older versions until after we have a v1.0 release of Zarf.

**Comment by RothAndrew** [comment]
Note: This is mainly being written up for purposes of being able to find it later in the future if needed. I expect that this issue will be closed with the `wontfix` label attached, since we are still sub-v1.0 and not supporting versions other than the latest one until we are post-v1.0.

**Comment by jeff-mccoy** [comment]
Yeah the zarf state file is now gone thankfully v0.15.0+

**Comment by RothAndrew** [comment]
Not spending any more brain power on this right now. If it still appears to be the case in v0.15.0 we can reopen.
