### ISSUE TITLE
The CI pipeline should run `pre-commit run -a` to verify a clean codebase

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#309]
As a maintainer of Zarf, I want the CI pipeline to run `pre-commit run -a` and fail if any of the checks come back "dirty", so that we can continue to keep a clean codebase by requiring linting and formatting rules.

**Comment by JasonvanBrackel** [comment]
@jeff-mccoy What's the impact here?  Would the codebase as it sits now pass this?  If so, let's push this up the backlog seems like a quick win.

**Comment by jeff-mccoy** [comment]
We have linting in the pipeline now, closing
