### ISSUE TITLE
Collect hashes of local and remote resources

### ISSUE THREAD

**Issue by mikhailswift** [defenseunicorns/zarf#32]
Currently hashes are being collected for some resources but not all.  This should be expanded to include all images, helm charts, files, etc.  When resources are fetched from a remote hashes should be confirmed with the remote registry after pull.  These hashes should then be verified prior to deploying a zarf package.

This likely will be a sub-task of https://github.com/defenseunicorns/zarf/issues/22

**Comment by JasonvanBrackel** [comment]
Possibly a subtask of https://github.com/defenseunicorns/zarf/issues/23

**Comment by jeff-mccoy** [comment]
Stale issue, closing.
