### ISSUE TITLE
Error: Unable to build the kustomization for kustomizations/bigbang

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#326]
### Steps to reproduce

```sh
# Checkout master
git checkout master && git pull

# Move to examples dir
cd examples

# make sure we're fresh
make clean

# build 'zarf' and 'zarf-init.tar.zst'
make build-release

# Try to build the big-bang example
make package-example-big-bang
```

### What I saw

![image](https://user-images.githubusercontent.com/16000938/153947723-945cf45e-3b70-4dbf-af18-f5cdbb059e9e.png)

When I set `-l debug`:

![image](https://user-images.githubusercontent.com/16000938/153947780-55446580-1404-4420-b2dd-ed6a26179593.png)

### What I expect

The big-bang example builds successfully

### Environment

* MacOS (Intel), Zarf master branch

**Comment by RothAndrew** [comment]
I'm dropping what I'm doing to look at this right now. Would love input from @jeff-mccoy or @YrrepNoj  as well

**Comment by RothAndrew** [comment]
IIRC Zarf was building its own `kustomization.yaml` out of raw manifest files. It doesn't seem to be doing that any more. It looks like it now expects a `kustomization.yaml`.

**Comment by jeff-mccoy** [comment]
I'm tied up for the next couple of hours, can you verify a regular zarf zarf.yaml from the correct directory is the same?  This feels like some sort of relative path issue.

**Comment by RothAndrew** [comment]
Is this what you mean?

```sh
cd examples/big-bang
../sync/zarf-mac-intel package create --confirm -l debug
```

![image](https://user-images.githubusercontent.com/16000938/153948816-e02a1c59-235f-4662-90cb-e2f93f8592d1.png)

**Comment by YrrepNoj** [comment]
I'm seeing the same thing on my end. It looks like the Kustomization was removed in [this commit](https://github.com/defenseunicorns/zarf/commit/088e0996a2662895a9af8ed656b941b8d72c63bc). Looking back through the commits now to try to piece together what happened.
