### ISSUE TITLE
Collect and record attestations during package creation

### ISSUE THREAD

**Issue by mikhailswift** [defenseunicorns/zarf#33]
When a zarf package is created we should record some attestations about the package's creation.  Some attestations could include

- Environment details such as set variables, user, cloud metadata if applicable
- Time of package creation, provided by a trusted timestamp authority
- Any vulnerability or antivirus scans run on the package's contents

We could use some of the features of [in-toto](https://github.com/in-toto/in-toto-golang) as a library.  [ITE-6](https://github.com/in-toto/ITE/tree/master/ITE/6) would allow us to create a specific attestation type to zarf packages if required.

Attestations should be displayed to a user deploying the package in a user friendly manner.

**Comment by jeff-mccoy** [comment]
This has been replaced by a number of other now-present Zarf features and release pipeline features.
