### ISSUE TITLE
Support Image Discovery in Helm Charts

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#337]
**Is your feature request related to a problem? Please describe.**
As a Zarf package developer, I want Zarf to be able to discover the images needed by a helm chart automagically.  

**Describe the solution you'd like**
Now that https://github.com/helm/community/pull/215 is merged, having Zarf be able to discover and include the images needed for the helm chart via the Annotations defined would enable Helm packages to be built more easily.

**Describe alternatives you've considered**
Rendering the chart and other value file searching.  See the HIP for considerations of these approaches.

**Additional context**

**Comment by jeff-mccoy** [comment]
@runyontr that looks like it will be part of Helm 4 as it stands currently.  Are there any plans to have ppl adopt in Helm 3 or should we block this on Helm 4 release?

**Comment by runyontr** [comment]
The annotation was accepted as is, but the top level Chart property won't be available until Helm 4.

Proposal is to add support for the annotation now, and add support for the property when helm 4 is supported by Zarf

**Comment by jeff-mccoy** [comment]
I guess my concern/confusion is we use the Helm SDK, so won't we be blocked until those fields are identified in the Helm version we are using or am I missing something?

**Comment by JasonvanBrackel** [comment]
@runyontr @jeff-mccoy Helm uses milestones for their roadmap https://github.com/helm/helm/milestones

I don't see anything around 4 here.

@runyontr It sounds like you want us to write code to support the annotation and do what Helm 4 will do?  Or am I like @jeff-mccoy missing something?
