### ISSUE TITLE
Don't use /usr/sbin for big bang examples.

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#340]
I think this was just a quick-fix pre-15 release, but we shouldn't require root/sbin for any zarf packages outside of the init packages when install k3s.  Really absolute paths for packages are fraught with issue so we should try to use relative ones whenever possible.

https://github.com/defenseunicorns/zarf/blob/7636dd048ed4a582e90884240cc0334a7fdfe213/examples/big-bang/zarf.yaml#L29

**Comment by RothAndrew** [comment]
I would actually be amenable to just removing Kubescape from that example. We were experimenting with it a few months ago and it made sense at the time but it doesn't really make sense to me to add it as part of the package any more.

**Comment by jeff-mccoy** [comment]
Copy, I bring it up because I think BB peeps are going to either do a PR or request to add their bbctl to the bb packages (which I think is a fantastic idea).

**Comment by YrrepNoj** [comment]
Handled by #362
