### ISSUE TITLE
Support Kustomizations

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#35]
As a user of Zarf, I want the ability to provide Kustomizations to be applied, so that I don't have to build the manifests myself using `kustomize build`

**Comment by jeff-mccoy** [comment]
can you clarify where you see this occurring?  During `package deploy`, `package create`, `prepare kustomize`, all of those or something else?

**Comment by RothAndrew** [comment]
Definitely `package create`

**Comment by RothAndrew** [comment]
Right now in `zarf.yaml` I can pass a directory to `manifests:`, I'd like the same thing for `kustomizations:`... or something to that effect. Right now I am running `kustomize build` on a kustomization and putting the output in the `manifests` directory

**Comment by jeff-mccoy** [comment]
Ah yes, that's totally a good issue and agree with the way-ahead.

**Comment by RothAndrew** [comment]
This is implemented in #237
