### ISSUE TITLE
Use automation to prevent merge when certain expectations are unmet in a PR

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#352]
Currently we have a need on non-trivial pull requests to also require an Architectural Decision Records (ADRs) be generated to help inform future us what we chose, why we chose it and what else we considered.  Using a label when a PR is generated is a transparent/powerful way to clearly note that this is required prior to merging.  

Adding automation around a "block list" of PR tags will allow us to cleanly do this for ADRs now, but also additional tag rules the team may establish in the future.  

An example article that discusses this: https://www.jessesquires.com/blog/2021/08/24/useful-label-based-github-actions-workflows/

**Comment by jeff-mccoy** [comment]
Updated labels with manual use-cases until we add automation.  There is now a "needs-adr" and "needs-docs" to flag PRs that lack these items to merge to help prevent reviewers forgetting about them and for submitters to quickly understand what is missing to merge.

**Comment by jeff-mccoy** [comment]
@RothAndrew would be good to get your thoughts on this since you've done the majority of our github actions work.

**Comment by RothAndrew** [comment]
Okay if I make it my top priority for tomorrow morning? Time flew by today. Guess I was having fun 😄

**Comment by jeff-mccoy** [comment]
Sure, no problem
