### ISSUE TITLE
Migrate example containers to github (or dockerhub) from gitlab

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#36]
The [game example](https://github.com/defenseunicorns/zarf/tree/master/examples/game) has an image it needs to run the demo that we need to move off of Repo1 container registry to turn off that feature in the project mirror.  

https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/container_registry

**Comment by RothAndrew** [comment]
This is done in #237
