### ISSUE TITLE
How should we document UX/UI work (ex. interviews, notes, wireframes, prototypes)

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#360]
Decisions as of 9/22

##Tool Usages##

**User Research**: Tracked in Userbit
**Personas**: Userbit
**Notes**: Userbit
**Userflows:** [Miro board](https://miro.com/app/board/uXjVOUJ4f2s=/?share_link_id=117795700641)
**Wireframes:** Userbit/Figma 
**Prototypes** [Figma](https://www.figma.com/file/MUItIzpzLBLuIyt225Bwgl/Zarf-UI?node-id=3%3A9054)
**Component Library** [Unicorn UI](https://unicorn-ui.netlify.app/)

**Comment by Madeline-UX** [comment]
@jeff-mccoy I am still working to figure out this solution.

**Comment by JasonvanBrackel** [comment]
@Madeline-UX @jeff-mccoy Has there been any movement here?

**Comment by Madeline-UX** [comment]
Currently exploring a tool called UserBit for open source work - Personas, user flows, interview planning/tracking, insights etc. Also using Miro for some larger group collaboration sessions. Would like @jeff-mccoy thoughts on the security of the tool.  Could not find an open source option - @jeff-mccoy wanna build one.

**Comment by JasonvanBrackel** [comment]
Sounds good, moving to Doing Now on the Project Board.

**Comment by Madeline-UX** [comment]
I think this is enough information for now - unless @jvb you thing this information need and ADR?  Another alternative is add these links and resources to the docs/contrubutor guides
