### ISSUE TITLE
Add External Community Events/Forums for Contributors and Consumers

### ISSUE THREAD

**Issue by unicornbunny182** [defenseunicorns/zarf#365]
Would like to add Zarf community chat channel (slack), community meet up, and contributor office hours added to repository and/or created and then added to the repository.

**Comment by unicornbunny182** [comment]
@Madeline-UX thoughts?

**Comment by Madeline-UX** [comment]
My research supports having a Zarf open source channel on slack ( I have plans to link it on the Zarf.dev website.
The team is in the process of discussing office hours (both internal and external)
