### ISSUE TITLE
K3s Alternative Example

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#378]
An example package to demonstrate how to standup a K8s cluster that isn't K3s would very helpful in demonstrating how Zarf supports cloud-native technologies below the K8s layer as well.  An easy example would be RKE2 due to it's small footprint, relatively similar technologies and out of the box air gap support.

**Comment by jeff-mccoy** [comment]
@saintskeeper this is the issue we discussed today

**Comment by saintskeeper** [comment]
Starting on this today. will work on getting a branch cut.

**Comment by jeff-mccoy** [comment]
Closing now that we have the EKS package in the repo
