### ISSUE TITLE
Rust Injector System Should Use SHA256

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#380]
Once #335 is merged, we will need to add the ability to use the SHASUM verification of the injected payload.  Even though the actual risk is incredibly small, it will give auditors of this approach more confidence in the injector system.

- [ ] Verify functionality of the actual rust SHASUM code
- [ ] Recompile the rust binary with MUSL
- [ ] Re-commit to the repo 
- [ ] Re-upload using the injector README instructions
- [ ] Update the packager injector code to pass the SHA256SUM to the rust binary in the ephemeral pod

**Comment by YrrepNoj** [comment]
Closed with #449
