### ISSUE TITLE
Zarf nerd notes documentation error

### ISSUE THREAD

**Issue by bandrea83** [defenseunicorns/zarf#390]
I think there's an error bere

In order to avoid TLS issues, Zarf binds to 127.0.0.1:319999 on each node as a NodePort to allow all nodes to access the pod(s) in the cluster

Probably Port Is 31999

**Comment by jeff-mccoy** [comment]
🤦‍♂️ there is.  My goal was to make that a bit more user-configurable in a future version, but yes 31999 would be the correct (and actually real) port.  Great find, feel free to PR a fix or I'll do it this afternoon. Thanks!
