### ISSUE TITLE
Find an elegant way to determine the ARCH in the Makefile.

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#399]
We'll need to add an issue to find an elegant way to determine the ARCH in the Makefile.

The current way doesn't break local e2e testing on arm architectures, but it will be slower because they will always build all the packages as part of the `make test-e2e`

_Originally posted by @YrrepNoj in https://github.com/defenseunicorns/zarf/pull/392#pullrequestreview-910416749_

**Comment by anoncam** [comment]
An alternate to `uname` on mac is the `arch` command.  So after your initial `ifeq` ... `Darwin` ... you can use a single arch command to get the processor architecture arm, arm64 or amd64/i386...


 The outputs here kinda illustrate what I'm trying to relay:
 
 ```zsh
➜  zsh-z git:(develop) uname -s
Darwin
➜  zsh-z git:(develop) uname -p
arm
➜  zsh-z git:(develop) # arm may be too generic
➜  zsh-z git:(develop) arch
arm64
```

**Comment by anoncam** [comment]
roger that. i'll take a look at the pipelines

**Comment by jeff-mccoy** [comment]
I think this was reasonable handled in #428 by allowing default + overrides for the arch coming into the makefile.
