### ISSUE TITLE
Create Auto MR if Merge Conflict Exists

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#4]
As an air gap engineer, I would like to personally review the code changes if there is a merge conflict upon a Big Bang upgrade. 

When upgrading Big Bang versions we would like to see a merge request created IF and WHEN a merge conflict is detected. This will allow the user to manually review the conflict and merge in the updates themselves.

_Possible solution:_  when performing the `repo.Push()` within [git.Push](https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/shift/pack/-/blob/master/cli/internal/git/push.go#L17), handle the failed push if it is a merge conflict by warning the user, pushing to a new branch in gitea and linking to that branch on the CLI.

---

MIgrated from https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/6

**Comment by RothAndrew** [comment]
Old, stale. Closing. Can reopen if needed.

**Comment by jeff-mccoy** [comment]
Closing this again due to the complexity of external git servers.
