### ISSUE TITLE
Tiny-Kafka example doesn't work

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#41]
The Tiny-Kafka example doesn't work. `zarf package create` works fine, but when running `zarf package deploy` I get the error message:

```
INFO[0008] Copying file                                  Destination=/var/lib/rancher/k3s/server/static/charts/strimzi-kafka-operator-0.24.0.tgz Source=/tmp/zarf-019814346/charts/strimzi-kafka-operator-0.24.0.tgz
FATA[0008] Unable to copy the contents of the asset      Destination=/var/lib/rancher/k3s/server/static/charts/strimzi-kafka-operator-0.24.0.tgz Source=/tmp/zarf-019814346/charts/strimzi-kafka-operator-0.24.0.tgz
```

Digging deeper, it looks to be because the .tgz file that Strimzi publishes is actually named `strimzi-kafka-operator-helm-3-chart-0.24.0.tgz`, and that's what gets saved in the tarball, but Zarf expects the chart files to be named `<ChartName>-<Version>.tgz`

![image](https://user-images.githubusercontent.com/16000938/133478558-443d7531-7675-4d27-8507-c6dd78f8b13c.png)

I'm submitting a PR to fix the example by pulling it down under `files:` instead of `charts:` but it's just a bandaid fix and deserves to be looked at more closely.

**Comment by jeff-mccoy** [comment]
Thanks I saw that too recently, it's (ironically) an inconsistency in how helm creates the tarball name now that we've switched to helm generating / pulling vs us manually pulling them.  This will actually be resolved more completely by #16 and the [native-k8s-apply](https://github.com/defenseunicorns/zarf/tree/native-k8s-apply) branch.
