### ISSUE TITLE
CLI command to detect what K8s distro is being used

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#412]
This might be a good new issue to expose the distro detect stuff on the CLI.  It would be really clean for a `zarf tools what-distro` or something command to tell the user about their kubecontext + detected distro.

_Originally posted by @jeff-mccoy in https://github.com/defenseunicorns/zarf/pull/407#discussion_r831416638_

**Comment by JasonvanBrackel** [comment]
@RothAndrew @jeff-mccoy Help me understand why this is important in the context of Zarf.   Also, we're talking K8s distro not OS distro correct?

**Comment by jeff-mccoy** [comment]
K8s distro, we do it internally, might be helpful to just expose it.
