### ISSUE TITLE
Zarf Community Channel

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#424]
**Is your feature request related to a problem? Please describe.**

Many open-source projects use tools to host community discussions (ex. slack, discord, discourse). Zarf needs an open-source platform to facilitate communication and collaboration among the community. This would be a good place to push out information on events and office hours. It should not however replace the conversations happening in the Github issues. 

**Questions**
Would this feature add value at this stage of the project?
What platform will best fit the long-term goals of the project?
Do we want to link GitHub issues to this channel or just make it for community engagement and communication?

**Describe the solution you'd like**
I would like to create an online community space for Zarf that is open to all users/contributors. 
Some considerations

- [x] Needs to scale with user growth
- [x] Ownership needs to be easily transferable 
- [x] Needs to be low or no cost

**Describe alternatives you've considered**

Slack
Discord
Discourse

**Additional context & Resources**

Argo uses the CNCF slack channel for questions and other communication https://argoproj.github.io/community/join-slack

https://orbit.love/blog/slack-vs-discord-vs-discourse

**Comment by jeff-mccoy** [comment]
I for one don't love the discussions feature in Github, it feels like an after thought.  I also don't love the idea of yet another slack login to maintain--getting into an existing foundation's slack would be great--maybe we can just go for the k8s one since we aren't _yet_ in a foundation?

**Comment by Madeline-UX** [comment]
This solution seems to address some of the concerns people have with Slack, even though it appears to be the preferred solution. Who would be a good person to run point reaching out the K8 for the collab?

**Comment by jeff-mccoy** [comment]
Looks like https://www.kubernetes.dev/docs/comms/slack/#requesting-a-channel is where we need to go if doing k8s.

**Comment by Madeline-UX** [comment]
@jeff-mccoy  Can you send us the link to these channels once they re up and running? For now the proposed solution is to link users to github discussions since it is linked to our internal slack https://github.com/defenseunicorns/zarf/discussions

**Comment by jeff-mccoy** [comment]
We haz Zarf channels in K8s slack now! 🎉 

http://slack.k8s.io/

Channels:
#zarf
#zarf-dev

<img width="487" alt="Screen Shot 2022-04-14 at 7 54 36 PM" src="https://user-images.githubusercontent.com/882485/163501073-fc61b31f-850d-453c-b932-2e56765e29c7.png">

**Comment by Madeline-UX** [comment]
New issue has been created on Zarf.dev GitHub to complete this work issue #26 https://github.com/defenseunicorns/zarf-website/issues/26
