### ISSUE TITLE
Make Windows Release for Zarf

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#426]
Need to create a release of the zarf binary for Windows users

- [ ] Update release to generate a windows Zarf binary
- [ ] Validate no unsafe file path issues, e.g. "/" (https://stackoverflow.com/questions/9371031/how-do-i-create-crossplatform-file-paths-in-go)

**Comment by JasonvanBrackel** [comment]
I'm speaking to Philly.NET on AirGap deployments in October, I'd love to get this done before then.  I'm bumping up the list.

**Comment by Noxsios** [comment]
Prev stuffs:

https://github.com/defenseunicorns/zarf/pull/833/files

https://github.com/defenseunicorns/zarf/pull/431
