### ISSUE TITLE
Local Docker Registry - SSL

### ISSUE THREAD

**Issue by ryansliceup** [defenseunicorns/zarf#433]
### Environment
Device and OS: Ubuntu 20.04
App version: v0.17.0
Kubernetes distro being used: kind
Other:

### Steps to reproduce
1. Install the self signed certificate to /etc/docker/certs.d/hostname:port/ca.crt. Once this is installed, restart docker. 
2. Setup a new package to include an image from a docker registry that is hosted on site with a self signed cert.

### Expected result
Make a tarball
### Actual Result
ryoung@zarf:~/zarf/examples/sliceup$ zarf package create --confirm

kind: ZarfPackageConfig
metadata:
  name: sliceup
  description: Sliceup Deployment
  architecture: amd64
build:
  terminal: zarf.local.sliceup.co
  user: ryoung
  architecture: amd64
  timestamp: Sat, 02 Apr 2022 13:26:19 +0000
  string:  v0.17.0
components:
- name: baseline
  required: true
  manifests:
  - name: sliceup
    files:
    - manifests/chserver.yml
    - manifests/clickhouseapi.yml
    - manifests/clickhouse_int.yml
    - manifests/jobmanager.yml
    - manifests/postgres.yml
    - manifests/slicef.yml
    - manifests/sqlcron.yml
    - manifests/taskmanager.yml
    - manifests/vector.yml
    - manifests/yandex-client.yml
  images:
  - defenseunicorns/zarf-game:multi-tile-dark
  - nexus.local.sliceup.co:443/chserver_master:8
  - nexus.local.sliceup.co:443/clickhouseapi_dev:9
  - nexus.local.sliceup.co:443/clickhouse_int_release-1.0.0:1
  - confluentinc/cp-enterprise-control-center:6.0.1
  - nexus.local.sliceup.co:443/flink_sliceup:latest
  - nexus.local.sliceup.co:443/flink-dev:working
  - nexus.local.sliceup.co:443/postgres_master:1
  - nexus.local.sliceup.co:443/sliceup-f:v3
  - nexus.local.sliceup.co:443/sqlcron_master:16
  - nexus.local.sliceup.co:443/flink-dev:working
  - hlebalbau/kafka-manager:stable
  - timberio/vector:0.15.1-debian
  - yandex/clickhouse-client
  •  Create Zarf package confirmed

                                                                                       
  📦 BASELINE COMPONENT                                                                
                                                                                       

  ✔  Copying manifests/chserver.yml                                                                              
  ✔  Copying manifests/clickhouseapi.yml                                                                         
  ✔  Copying manifests/clickhouse_int.yml                                                                        
  ✔  Copying manifests/jobmanager.yml                                                                            
  ✔  Copying manifests/postgres.yml                                                                              
  ✔  Copying manifests/slicef.yml                                                                                
  ✔  Copying manifests/sqlcron.yml                                                                               
  ✔  Copying manifests/taskmanager.yml                                                                           
  ✔  Copying manifests/vector.yml                                                                                
  ✔  Copying manifests/yandex-client.yml                                                                         
  ✔  Loading 1 manifests                                                                                         
     ERROR:  Unable to pull the image nexus.local.sliceup.co:443/flink_sliceup:latest                            
ryoung@zarf:~/zarf/examples/sliceup$ zarf -l debug package create --confirm

Log level set to debug
  DEBUG   Loading zarf config zarf.yaml
  DEBUG   Creating temp path /tmp/zarf-1106993399
  DEBUG   config.IsZarfInitConfig
  DEBUG   config.GetSeedImage()
  DEBUG   config.IsZarfInitConfig
  DEBUG   config.BuildConfig(/tmp/zarf-1106993399/zarf.yaml)

kind: ZarfPackageConfig
metadata:
  name: sliceup
  description: Sliceup Deployment
  architecture: amd64
build:
  terminal: zarf.local.sliceup.co
  user: ryoung
  architecture: amd64
  timestamp: Sat, 02 Apr 2022 13:26:24 +0000
  string:  v0.17.0
components:
- name: baseline
  required: true
  manifests:
  - name: sliceup
    files:
    - manifests/chserver.yml
    - manifests/clickhouseapi.yml
    - manifests/clickhouse_int.yml
    - manifests/jobmanager.yml
    - manifests/postgres.yml
    - manifests/slicef.yml
    - manifests/sqlcron.yml
    - manifests/taskmanager.yml
    - manifests/vector.yml
    - manifests/yandex-client.yml
  images:
  - defenseunicorns/zarf-game:multi-tile-dark
  - nexus.local.sliceup.co:443/chserver_master:8
  - nexus.local.sliceup.co:443/clickhouseapi_dev:9
  - nexus.local.sliceup.co:443/clickhouse_int_release-1.0.0:1
  - confluentinc/cp-enterprise-control-center:6.0.1
  - nexus.local.sliceup.co:443/flink_sliceup:latest
  - nexus.local.sliceup.co:443/flink-dev:working
  - nexus.local.sliceup.co:443/postgres_master:1
  - nexus.local.sliceup.co:443/sliceup-f:v3
  - nexus.local.sliceup.co:443/sqlcron_master:16
  - nexus.local.sliceup.co:443/flink-dev:working
  - hlebalbau/kafka-manager:stable
  - timberio/vector:0.15.1-debian
  - yandex/clickhouse-client
  •  Create Zarf package confirmed

                                                                                       
  📦 BASELINE COMPONENT                                                                
                                                                                       

  ✔  Copying manifests/chserver.yml                                                                              
  ✔  Copying manifests/clickhouseapi.yml                                                                         
  ✔  Copying manifests/clickhouse_int.yml                                                                        
  ✔  Copying manifests/jobmanager.yml                                                                            
  ✔  Copying manifests/postgres.yml                                                                              
  ✔  Copying manifests/slicef.yml                                                                                
  ✔  Copying manifests/sqlcron.yml                                                                               
  ✔  Copying manifests/taskmanager.yml                                                                           
  ✔  Copying manifests/vector.yml                                                                                
  ✔  Copying manifests/yandex-client.yml                                                                         
  ✔  Loading 1 manifests                                                                                         
  DEBUG   Get "https://nexus.local.sliceup.co:443/v2/": x509: certificate signed by unknown authority            
     ERROR:  Unable to pull the image nexus.local.sliceup.co:443/postgres_master:1

### Additional Context
I have performed a docker pull on all the images on my local workstation, and those images were pulled successfully. My question is where do we input the CA certificate when building the init container? I am assuming we put it there. Any information on how to install a CA.crt file in the environment so I can package up my application, would be most helpful.

**Comment by jeff-mccoy** [comment]
Thanks @ryansliceup, that's a good find. Under the hood we use [Crane](https://github.com/google/go-containerregistry/blob/main/cmd/crane/README.md), which [it seems does not support  the docker private CA](https://github.com/google/go-containerregistry/issues/211).  However, on Linux they seem to indicate you can use `SSL_CERT_FILE` to handle this.  Alternatively, if the private registry is trusted on your system, then it should work as well.  A related thread that discussed this is [here](https://github.com/google/go-containerregistry/issues/595).

We definitely need to add a note to the docs about this once we settle on the right solution.  Since you're facing the issue right now, would welcome your recommendations on the best approach to take.

**Comment by ryansliceup** [comment]
Thanks for the information! I was able to get past this issue. When you mean a private registry is trusted, do you mean from the operating system perspective, or docker? For instance if you put the certificate in /etc/docker/certs.d/hostname:port/ca.crt, then only docker will trust it. I figured I would be okay here, but that was not the case. 

I should have tried to put the cert in /usr/local/share/ca-certificates and then ran update-ca-certificates.

**Comment by jeff-mccoy** [comment]
Yeah that's the issue, zarf doesn't use docker itself (which is some ways is good because it means it's not a dependency), and the tool we use doesn't support the docker cert path. So you have to do an online override or update the OS cert list.
