### ISSUE TITLE
Unable to use "short" version of docker repo in "remote:" section of zarf.yaml

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#44]
If I put a "short" version of a docker image in the `remote:` section, it throws an error when running ~~`zarf package create`~~ `zarf package deploy`:

![image](https://user-images.githubusercontent.com/16000938/133516501-52733b47-602e-4464-bb19-86afde1f0c38.png)

Changing it to fully qualified e.g. `docker.io/rancher/coredns-coredns:1.8.3` works fine.

**Comment by jeff-mccoy** [comment]
That looks like you're running with modified hosts.  Are you sure that's a valid bug?  index.docker.io is trying to talk to the zarf cluster.

**Comment by RothAndrew** [comment]
oops, I meant it throws an error when running `zarf package deploy`. It is running on the vagrant VM with the modified /etc/hosts
