### ISSUE TITLE
How do we want to document user/stakeholder insights

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#450]
**Is your feature request related to a problem? Please describe.**
It is important to document insights in a manner that is sharable to the team, I would like to keep user discovery and insights as transparent as possible, while also not filling up the board with comments and issues.

**Describe the solution you'd like**
I would like to find a tool to house all of the Zarf research and discovery 
The solution would need to offer some user permission to protect internal customer data
I recommend looking into dovetail as an option.
Having the option to send out user feedback forms and surveys through the same tool would be the icing on the cake

**Describe alternatives you've considered**
If there is a way to do this on GitHub I am open to that. 
or if there is a free and open-source tool

**Additional context**
I would like to use this tool to start aggregating all of the current user data, interviews, personas, insights, User cases, etc.

**Comment by JasonvanBrackel** [comment]
@Madeline-UX Any movement here?

**Comment by Madeline-UX** [comment]
Yes resolved and addressed in another issue.
