### ISSUE TITLE
Improve pre-reqs of the e2e tests readme

### ISSUE THREAD

**Issue by mahomedalid** [defenseunicorns/zarf#456]
While trying to run the e2e tests locally I am struggling to understand the pre-reqs. After some debugging I have found some preq-reqs that could be useful to add to the [README](https://github.com/defenseunicorns/zarf/tree/master/src/test/e2e#readme). At the moment I have:

- The scripts will try to get authentication from ~/.git-credentials, so store credentials there will be required, specifically for:

https://repo1.dso.mil/platform-one/big-bang/apps/security-tools/twistlock.git@0.0.9-bb.0authentication
https://github.com/defenseunicorns/zarf.git@v0.15.0

It would probably also be a good idea to either add a way to add verbosity to the e2e tests (debug flags) or add a more specific error message to src/internal/git/pull.go including git error and repo url.

I am planning to submit a PR after I got the e2e tests running successfully.

**Comment by jeff-mccoy** [comment]
@YrrepNoj this might be a good thing to start for the doc updates we discussed.

**Comment by jeff-mccoy** [comment]
Could also be related to https://github.com/defenseunicorns/zarf/issues/417 comments, having a way to fallback to host git seems like a nice solution to these situations.

**Comment by mahomedalid** [comment]
@jeff-mccoy yes! that could also alleviate the issues/confusion with running e2e testing locally.
