### ISSUE TITLE
Update the zarf registry to not use an env variable secret to satisfy pointless DoD STIG V-242415 😭

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#457]
A DoD STIG forbids the use of "env variable secrets" because they are "bad".  This issue focuses specifically on how we can address that concern for the Zarf Registry.   https://stigviewer.com/stig/kubernetes/2021-04-14/finding/V-242415

Also.. 😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭😭

**Comment by unicornbunny182** [comment]
👀

**Comment by jeff-mccoy** [comment]
@YrrepNoj  haSharedSecret here: https://github.com/defenseunicorns/docker-registry.helm#configuration

**Comment by jeff-mccoy** [comment]
REGISTRY_HTTP_SECRET

**Comment by jeff-mccoy** [comment]
https://github.com/defenseunicorns/docker-registry.helm/blob/main/templates/deployment.yaml#L92

**Comment by jeff-mccoy** [comment]
https://github.com/defenseunicorns/docker-registry.helm/blob/main/templates/secret.yaml#L16

**Comment by jeff-mccoy** [comment]
https://docs.docker.com/registry/configuration/#/http,   secret: asecretforlocaldevelopment
