### ISSUE TITLE
Anti-Template for values that need to be changed before building

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#464]
Zarf utilizes templates to hot-swap values when doing a `zarf package deploy`. We should add a way to have template/placeholder text that gets recognized and handled when doing a `zarf package create`.

For example, our eks package uses an [eks.yaml](https://github.com/defenseunicorns/zarf/blob/master/packages/distros/eks/eks.yaml) that has the name for the nodegroup and cluster commented out. This value is commented out because it needs to be unique each time the eks yaml is used which means before we create the package we need to remember to add/update the name field.

It would be very useful if we would check for an 'anti-template' (maybe ###ZARF_CHANGEME### ?) while creating packages to ensure things like this will get caught at build-time instead of running into errors during run-time.

Extra credit points if the `zarf package create` is able to prompt the user for what they want the value to be.

**Comment by jeff-mccoy** [comment]
@YrrepNoj this is the issue we discussed for allowing package create time variables that must be supplied for the zarf agent changes on release.

**Comment by jeff-mccoy** [comment]
Closing in favor #613
