### ISSUE TITLE
Documentation Site for Zarf

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#466]
**Is your feature request related to a problem? Please describe.**
Yes, we have outgrown the current way we do docs (using github) and need a more robust solution. Madeline has usability concerns, and current docs do not play well with new website. 

**Describe the solution you'd like**

We propose using a document generator 
We are looking into Hugo, Docusuarus, Read the Docs
Both Andy and John have experience using Hugo which makes it an easier shift

Open to other ideas as long as it meets the following criteria

- A tool that helps developers write and organize technical documentation
- The tool needs to be low code//no code to allow the designer to make changes to documents (without knowing java or react)
- Ability to customize theme if needed (colors, tables)
- Must be free and open source

**Describe alternatives you've considered**
We considered using github markdown with github pages, but themes and navigation is limited. 

**Additional context**
Want to get this established and hopefully finished before get GA

**Comment by Madeline-UX** [comment]
https://github.com/facebook/docusaurus/tree/main/website

**Comment by RothAndrew** [comment]
As I research different doc generators I'm becoming a big fan of Docusaurus. Definitely want to look into it more.

**Comment by Madeline-UX** [comment]
@YrrepNoj Can you link the PR you created to test out Docusaurus here?

**Comment by YrrepNoj** [comment]
@jeff-mccoy Any opinions on where the Docusaurus website contents should live? This repo? The zarf.dev repo? it's own repo?

**Comment by Noxsios** [comment]
For other (imo) good references, Cloudflare uses Hugo https://github.com/cloudflare/cloudflare-docs and K3D uses Mkdocs https://k3d.io/v5.4.1/.  For the Big Bang product, I wrote a docs assembler w/ Mkdocs as the final build tool - https://docs-bigbang.pages.dev/ .
