### ISSUE TITLE
k3s component doesn't check if k3s is already running

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#494]
If someone were to accidently `zarf init --components=k3s` twice (it doesn't have to be back-to-back, just before Zarf destroys the first cluster), weird stuff happens that Zarf doesn't handle in the best way.

One of the files that gets copied to the host during the installation of the k3s component is an 'empty-file' that gets placed in the `/root/.kube/config`. Since k3s/zarf is already running locally, the `init` command fails before a new config is able to be created and symlinked. Since an 'empty-file' was placed in `/root/.kube/config` we have now lost the kube-context that would let us interact with the original k3s cluster. 

@blancharda ran into this problem when accidently running `zarf init --components=k3s` twice when working late one night. He was lucky enough to have already copied the original `k3s.yaml` kubecontext somewhere else on his host so his non-root user can use it easier, but if he hadn't done this he would have been forced to destroy the cluster/ec2 instance and redeploy everything.

---
Desired Outcome:

There should be a script added to the `before` section of the k3s component that checks if a k3s cluster is already running on that host to help prevent accidents like this from happening in the future.

**Comment by jeff-mccoy** [comment]
Since we don't want to hard-code anything we don't have to, probably worth putting this solution in the before scripts

**Comment by JasonvanBrackel** [comment]
Keeping this in the New Requests on the Board until we solve #734

**Comment by Racer159** [comment]
Is this still an issue? https://github.com/defenseunicorns/zarf/blob/main/.github/workflows/test-upgrade.yml  I think that `empty-file` can be deleted now right?

**Comment by jeff-mccoy** [comment]
Confirmed. This can be closed now that we have the `only filter` and testing. The original issue no longer exists.
