### ISSUE TITLE
Make utility registry require credentials

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#5]
At the very least, the utility registry should require credentials to push images.  Ideally these creds would be dynamically handled similarly to [#3](https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/3).

---

Migrated from https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/9

**Comment by jeff-mccoy** [comment]
@RothAndrew this would be a good high value task you could do without code changes I think

**Comment by RothAndrew** [comment]
So Docker Registry uses `htpasswd` for password auth, which uses one-way hashes. Not as simple as just substituting `###ZARF_SECRET###` with the password that Zarf creates.

Right now I'm thinking of maybe adding functionality to add parsing of `###ZARF_HTPASSWD###` which would result in a proper `htpasswd` string like `zarf-git-user:$2y$05$1oC7e2fbDJaMx7YEHIuPre90KBg2WQRRR2Ag4aE49buP7SQTu9kMS` (that's the hash for the password `foobar`)
