### ISSUE TITLE
Getting started init script

### ISSUE THREAD

**Issue by mahomedalid** [defenseunicorns/zarf#512]
As a team we created a script that it is useful for new engineers to setup and try Zarf really quickly. Usage is similar to:

```
curl -sL https://raw.githubusercontent.com/defenseunicorns/zarf/installZarf.sh | bash
```

It helps to:

* Create a /home/<user>/.zarf directory or /tmp/zarfxxx temporary directory
* Detects and downloads the proper binary and package depending on the platform (mac, linux, x64, 32, arm, etc.)
* Do check on the downloaded checksum files hashes
* Optionally, zarf init into the current k8s context

I see this as a helpful maybe in the getting started section. **Do you think this is something the project will benefit from?** We would be eager to create the initial PR with the script code.

**Comment by jeff-mccoy** [comment]
Closed now that https://zarf.dev/install exists
