### ISSUE TITLE
Zarf destroy doesn't clean up zarf secrets in deployed services

### ISSUE THREAD

**Issue by olhakonst17** [defenseunicorns/zarf#520]
### Steps to reproduce
1. Deploy a package with Zarf into the cluster.
2. Run 'zarf destroy'

### Expected result
All zarf secrets are being cleaned up (including zarf secrets within deployed by zarf services).

### Actual Result
Zarf secrets within deployed by zarf services are still exists.

### Visual Proof (screenshots, videos, text, etc)
<img width="1085" alt="zarf-secrets-leftovers" src="https://user-images.githubusercontent.com/58791358/173925740-9cae51f9-d0c5-4a07-b0d5-df36729dce3d.png">

**Comment by jeff-mccoy** [comment]
Thanks @olhakonst17 this is a good find.  Did you happen to use the optional flag `--remove-components`?  I believe that would have removed these as well.
