### ISSUE TITLE
`Zarf Init` should warn when the binary is out of sync with a release

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/zarf#529]
**Is your feature request related to a problem? Please describe.**
If I `brew upgrade zarf`, I may forget to download the release associated with the updated binary.

**Describe the solution you'd like**
Warn / remind users that the binary is out of sync with the release.

**Describe alternatives you've considered**
Remember to download the associated release when I update the binary

**Additional context**
Blame @jeff-mccoy

**Comment by jeff-mccoy** [comment]
Due to the way that homebrew work, this should no longer be an issue as zarf is place in a new directory on upgrade, can you confirm this is still an issue @ntwkninja?

**Comment by ntwkninja** [comment]
If I am on the latest Zarf version the current workflow is good. If I am on an older version of the binary and did not execute a zarf init, or deleted the previous zarf init file I could run into parity issues because `zarf init` is built to download the `latest` init package.

Steps to Reproduce

1. Manually install Zarf v0.20.0 binary (aside from the $PATH, this would be the same as `brew install zarf` and failing to `brew upgrade` when a future version is released)
2. Check Zarf Version and Clone Repo
```
➜  tmp  `which zarf`
/usr/local/bin/zarf
➜  tmp  `zarf version`
v0.20.0
➜  tmp  `git clone https://github.com/defenseunicorns/zarf.git` && `cd zarf`
```
3. Run `zarf init`
```
➜  zarf `zarf init`
It seems the init package could not be found locally, but can be downloaded from
https://github.com/defenseunicorns/zarf/releases/download/v0.21.1/zarf-init-arm64.tar.zst

Note: This will require an internet connection.
? Do you want to download this init package? `Yes`

# downloads v0.21.1 init package to /usr/local/bin. 
```

Note: `brew install` currently only supports the current version of zarf so v0.20.0 had to be installed manually because the tap only contains the latest version.

```
➜  tmp `brew install zarf@v0.20.0`
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).

Warning: No available formula with the name "zarf@v0.20.0".
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching taps on GitHub...
Error: No formulae found in taps.
```

**Comment by ntwkninja** [comment]
Sounds like an edge case that could be covered by docs simply encouraging users to upgrade or manually download an init package that corresponds to their zarf version.

If the init packages will always be backwards compatible with zarf binaries then this issue can be closed.

**Comment by ntwkninja** [comment]
Also I worded the initial issue very poorly but this should capture this dialogue should capture the initial intent

**Comment by Racer159** [comment]
This happens because of this code: https://github.com/defenseunicorns/zarf/blob/b478dabe0395506d1668f6cbac04881b67c213de/src/cmd/initialize.go#L62 It tries to strictly parse the semver but semver does not expect the leading "v" in the version string and errors out.

**Comment by jeff-mccoy** [comment]
Are you sure about the v prefix? 
<img width="622" alt="Screen Shot 2022-08-08 at 12 23 13 PM" src="https://user-images.githubusercontent.com/882485/183476808-8c8bdbdc-d0d2-46e8-9f3f-6bd00d367243.png">

**Comment by jeff-mccoy** [comment]
https://semver.org/#is-v123-a-semantic-version

**Comment by Racer159** [comment]
Yes, `StrictNewVersion` does not use that regex:
```
// Parsing here does not use RegEx in order to increase performance and reduce
// allocations.
```

**Comment by jeff-mccoy** [comment]
Lol I seem to recall changing to strict, but don't remember why now 😑

**Comment by Racer159** [comment]
> Lol I seem to recall changing to strict, but don't remember why now expressionless

Yeah that whole block of code looks to have come from a single commit, but that may have been a squash and merge.

**Comment by Racer159** [comment]
Maybe worth a PR back to that project potentially too.  At least to fix their spelling mistakes:
```
// If you want to coerce a version, such as 1 or 1.2, and perse (sic) that as the 1.x
// releases of semver provided use the NewSemver() function.
```

**Comment by Racer159** [comment]
Per their README though that is the design of the StrictNewVersion.  It adheres to the spec precisely (so doesn't try to coerce the string into a semantic version)

**Comment by jeff-mccoy** [comment]
I only uses that library because helm already used it and that was a last-minute fix to get around some release issues for zarf init with homebrew.  Probably should just drop the library and use a simple string parsing or regex.

**Comment by Racer159** [comment]
Yeah that is the only thing it is used for. I can change that in the PR to just drop it entirely.
