### ISSUE TITLE
Sign old commits prior to enforcing commit signature

### ISSUE THREAD

**Issue by jeff-mccoy** [defenseunicorns/zarf#53]
We should scrub the commit history for old commits and verify their authenticity cryptographically to ensure a clean/validated git history.  One possible way to do it:  https://superuser.com/a/1123928

**Comment by RothAndrew** [comment]
@jeff-mccoy is this still something we need to do? If so is it something you have to do or can one of us do it with a little guidance?

**Comment by RothAndrew** [comment]
Assigning @jeff-mccoy since I believe he is specifically the person that needs to do this.

**Comment by jeff-mccoy** [comment]
I think you do too 😂, but thanks I'll do mine.

**Comment by RothAndrew** [comment]
Oh? I'm not aware of me needing to do anything. AFAIK I've been doing signed commits since I started in August since we turned on the requirement right around that time. I think this is to go back and sign old commits prior to August, which would have just been you and Josh

**Comment by jeff-mccoy** [comment]
there are 4 commits at the beginning from Josh, initially we had two separate repos working similar problems, pushed everything to his repo so we could work together, but they ended up moving to another project instead.  There's actually no code left from that initial work he pushed so not sure if we need to have him sign it or just squash it.  I have most of the missing sigs early on, but you have some too:  https://github.com/defenseunicorns/zarf/commits?after=acd5dc445c5131a7afd39ec7acbde8d308d27caa+34&author=RothAndrew

<img width="1375" alt="Screen Shot 2022-02-04 at 5 51 29 PM" src="https://user-images.githubusercontent.com/882485/152618345-8e2c45c9-d6d9-463b-94b0-d1c7846ef011.png">

**Comment by RothAndrew** [comment]
Gotcha. I'll go take a look at those. https://superuser.com/a/1123928 is still the right way to do it? We'll have to turn off the branch protection on master to force push to it.

**Comment by jeff-mccoy** [comment]
I think so but let's wait post-merge of the big pr because I don't want to know what a force push will do to the rebasing on that branch.

**Comment by RothAndrew** [comment]
We could, like, not do it at all 😜 . Force pushing to change history always gives me the willies.

**Comment by jeff-mccoy** [comment]
Nice...but no we need proper attribution of code in the repo.

**Comment by jeff-mccoy** [comment]
Okay now that we had to do a force-push tonight to get #237 merged without breaking it's signatures, I think this is the right time to also fix this issues to avoid another force-push in the future.  I’ve experimented with different ways to do this and think that using [git rebase --signoff](https://git-scm.com/docs/git-rebase#Documentation/git-rebase.txt---signoff).  Some more notes on this can be found at https://stackoverflow.com/a/1962112/467373.  

I used the command `git rebase --signoff --root --committer-date-is-author-date -s recursive -X ours` and then made a final commit to fix some small `README.MD` merge messiness (there were dozens of merge conflicts within that file for some reason on rebase).

You can see at the [master-signature-test](https://github.com/defenseunicorns/zarf/commits/master-signature-test?after=770fc6a8afc01161736dc20c5cc72e0117e7f101+524&branch=master-signature-test) that this actually annotated every commit all the way back to the first one so now all have a verified signature.  

I did see that some merge-ceptions that say partially verified, but I think we'd have to go and rewrite those old branches to fix that issue as the secondary PRs themselves have unverified commits somehow.

Before:
<img width="815" alt="Screen Shot 2022-02-08 at 2 03 21 AM" src="https://user-images.githubusercontent.com/882485/152958615-d0b6ca3c-163e-4c14-afc4-e802572a87ed.png">

After:
<img width="821" alt="Screen Shot 2022-02-08 at 2 03 24 AM" src="https://user-images.githubusercontent.com/882485/152958613-6f494fa9-204f-4703-ad8f-ca5ce0e19df3.png">

Github:
<img width="1295" alt="Screen Shot 2022-02-08 at 3 29 00 AM" src="https://user-images.githubusercontent.com/882485/152958747-8f63160d-20a7-4176-ae07-5b4eadd48160.png">

**Comment by jeff-mccoy** [comment]
I should also mention even though this will rewrite history and all hashes, moving in-progress branches isn't super hard, just need to use reset soft + stash to move the affected files. The hardest part would be if you had a lot of commits ahead and you wanted to preserve them with messages, you'd have to do the same process but one reset/stash per commit.

**Comment by jeff-mccoy** [comment]
That's a speculation on partially verified.  What I was trying to say is that issue exists now already and this change doesn't immediately fix that.  It has to do with how GitHub is evaluating PRs associated with a commit. This is not a git thing, this branch fixes the git signature issue properly.  But GitHub has some magic it does for PRs tagged in a commit, if you click on one you'll see that's what's breaking.

**Comment by RothAndrew** [comment]
LGTM

**Comment by jeff-mccoy** [comment]
Okay I think if @RothAndrew concurs we'll proceed.

**Comment by RothAndrew** [comment]
LGTM

**Comment by jeff-mccoy** [comment]
Confirmed with @RothAndrew @YrrepNoj and @mike-winberry, proceeding with the force-push

**Comment by mike-winberry** [comment]
LGTM too!

**Comment by jeff-mccoy** [comment]
Couple notes on updating master locally that I had to do (alternative could be just reclone or delete local master):
```
git config pull.rebase true
git pull --force  --allow-unrelated-histories
```

**Comment by RothAndrew** [comment]
Can we call this backlog item done?

**Comment by jeff-mccoy** [comment]
Yeah I guess GitHub didn't know how to auto-close the tagged issue on history rewrite 😂
