### ISSUE TITLE
Flux throwing error about deprecations and Seccomp

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#538]
Trying to update the version of Zarf in DI2-ME, and Flux is throwing an error and restarting, which is causing the booting up of Big Bang to fail

Zarf version: 0.19.4
Flux version: 3 different versions tried, all with the same errors (The Flux kustomization in Big Bang v1.28.0, 1.33.0, and 1.36.0)
K8s version: v1.23.6+k3s1 (from the zarf-builtin K3s)

<details>
<summary>Pod log</summary>

```
root@ip-172-31-87-202:~/zarf-package-software-factory/build# kubectl logs helm-controller-568967f974-xr8rn -n flux-system --previous
{"level":"info","ts":"2022-06-17T03:18:26.082Z","logger":"controller-runtime.metrics","msg":"Metrics server is starting to listen","addr":":8080"}
{"level":"info","ts":"2022-06-17T03:18:26.082Z","logger":"setup","msg":"starting manager"}
{"level":"info","ts":"2022-06-17T03:18:26.083Z","msg":"Starting server","kind":"health probe","addr":"[::]:9440"}
{"level":"info","ts":"2022-06-17T03:18:26.083Z","msg":"Starting server","path":"/metrics","kind":"metrics","addr":"[::]:8080"}
I0617 03:18:26.184212       7 leaderelection.go:248] attempting to acquire leader lease flux-system/helm-controller-leader-election...
I0617 03:18:26.189658       7 leaderelection.go:258] successfully acquired lease flux-system/helm-controller-leader-election
{"level":"info","ts":"2022-06-17T03:18:26.189Z","logger":"controller.helmrelease","msg":"Starting EventSource","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","source":"kind source: *v2beta1.HelmRelease"}
{"level":"info","ts":"2022-06-17T03:18:26.189Z","logger":"controller.helmrelease","msg":"Starting EventSource","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","source":"kind source: *v1beta2.HelmChart"}
{"level":"info","ts":"2022-06-17T03:18:26.189Z","logger":"controller.helmrelease","msg":"Starting Controller","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease"}
{"level":"info","ts":"2022-06-17T03:18:26.290Z","logger":"controller.helmrelease","msg":"Starting workers","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","worker count":4}
{"level":"info","ts":"2022-06-17T03:18:55.428Z","logger":"controller.helmrelease","msg":"HelmChart 'bigbang/bigbang-bigbang' is not ready","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"bigbang","namespace":"bigbang"}
{"level":"info","ts":"2022-06-17T03:18:55.431Z","logger":"controller.helmrelease","msg":"reconcilation finished in 14.405509ms, next run in 10m0s","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"bigbang","namespace":"bigbang"}
{"level":"info","ts":"2022-06-17T03:19:02.890Z","logger":"controller.helmrelease","msg":"could not find optional Secret 'bigbang/terraform'","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"bigbang","namespace":"bigbang"}
{"level":"info","ts":"2022-06-17T03:19:05.178Z","logger":"controller.helmrelease","msg":"HelmChart 'bigbang/bigbang-gatekeeper' is not ready","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"gatekeeper","namespace":"bigbang"}
{"level":"info","ts":"2022-06-17T03:19:05.183Z","logger":"controller.helmrelease","msg":"reconcilation finished in 72.448922ms, next run in 5m0s","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"gatekeeper","namespace":"bigbang"}
{"level":"info","ts":"2022-06-17T03:19:05.202Z","logger":"controller.helmrelease","msg":"reconcilation finished in 2.413942608s, next run in 10m0s","reconciler group":"helm.toolkit.fluxcd.io","reconciler kind":"HelmRelease","name":"bigbang","namespace":"bigbang"}
{"level":"info","ts":"2022-06-17T03:19:09.697Z","logger":"KubeAPIWarningLogger","msg":"policy/v1beta1 PodSecurityPolicy is deprecated in v1.21+, unavailable in v1.25+"}
{"level":"info","ts":"2022-06-17T03:19:16.336Z","logger":"KubeAPIWarningLogger","msg":"spec.template.metadata.annotations[container.seccomp.security.alpha.kubernetes.io/manager]: deprecated since v1.19, non-functional in v1.25+; use the \"seccompProfile\" field instead"}
E0617 03:19:57.615831       7 leaderelection.go:367] Failed to update lock: Put "https://10.43.0.1:443/apis/coordination.k8s.io/v1/namespaces/flux-system/leases/helm-controller-leader-election": context deadline exceeded
I0617 03:19:57.615893       7 leaderelection.go:283] failed to renew lease flux-system/helm-controller-leader-election: timed out waiting for the condition
{"level":"error","ts":"2022-06-17T03:20:27.624Z","logger":"setup","msg":"problem running manager","error":"leader election lost"}
```

</details>

The Big Bang Gatekeeper HelmRelease fails with error `Helm upgrade failed: another operation (install/upgrade/rollback) is in progress`. It happens right after the Flux pods restart after they throw the above error.

**Comment by RothAndrew** [comment]
![Screen Shot 2022-06-16 at 8 28 28 PM](https://user-images.githubusercontent.com/16000938/174219138-76ed9a52-460f-4bb2-b282-227aae29c46b.png)

**Comment by RothAndrew** [comment]
![image](https://user-images.githubusercontent.com/16000938/174219169-183071ad-6f05-49e5-bcc5-7fa1a6dfbc59.png)

**Comment by YrrepNoj** [comment]
@RothAndrew I ran into this when I wasn't giving my BB package enough resources on just a normal deployment. At first the gatekeeper helm-release simply errored out saying `max retries hit`, I tried increasing the number of retries and reconciling the gatekeeper helm-release but then eded up seeing the `Helm upgrade failed: another operation (install/upgrade/rollback) is in progress error` instead. 

If this is something that's blocking you at the moment I was told that removing the gatekeeper-system-gatkeeper.v1 secret and having flux reconcile the HR again will get it unstuck. Credits to @blancharda 


```bash
k delete secret -n bigbang sh.helm.release.v1.gatekeeper-system-gatekeeper.v1

flux reconcile hr -n bigbang gatekeeper
```

**Comment by RothAndrew** [comment]
Thanks 😄 Will need to figure out the root cause though if I want to get this zarf package working without manual intervention.

**Comment by RothAndrew** [comment]
Making my own K3s Zarf package using the [code from Zarf v0.17.0](https://github.com/defenseunicorns/zarf/tree/v0.17.0/packages/distros/k3s) and using that instead of the builtin k3s completely solved the issue. So I think that narrows it down to an incompatibility in the K3s version, the K8s version, or the configuration of K3s.

@jeff-mccoy how do you feel about rolling back the K3s version we're using? This is blocking me from upgrading the Zarf version in DI2-ME, unless I stick with my own K3s package

**Comment by RothAndrew** [comment]
![image](https://user-images.githubusercontent.com/16000938/174222002-ded82b77-567d-491e-a15f-d20e3d951711.png)

![image](https://user-images.githubusercontent.com/16000938/174222026-283d206c-f39b-49e7-b669-1cbc12e7bf34.png)

![image](https://user-images.githubusercontent.com/16000938/174222060-2345e85c-7832-46ba-a610-e65c381a4b62.png)

![image](https://user-images.githubusercontent.com/16000938/174222081-deb20343-e06c-40d3-ac78-bad48e6115a0.png)

**Comment by anoncam** [comment]
> @RothAndrew I ran into this when I wasn't giving my BB package enough resources on just a normal deployment. At first the gatekeeper helm-release simply errored out saying `max retries hit`, I tried increasing the number of retries and reconciling the gatekeeper helm-release but then eded up seeing the `Helm upgrade failed: another operation (install/upgrade/rollback) is in progress error` instead.
> 
> If this is something that's blocking you at the moment I was told that removing the gatekeeper-system-gatkeeper.v1 secret and having flux reconcile the HR again will get it unstuck. Credits to @blancharda
> 
> ```shell
> k delete secret -n bigbang sh.helm.release.v1.gatekeeper-system-gatekeeper.v1
> 
> flux reconcile hr -n bigbang gatekeeper
> ```

I also find flux can conflict with CRDs in Big Bang upstream and often the remedy is a reinstallation/upgrade of flux.

If you have the luxury on the cluster to do some troubleshooting, this is usually my order of operations.

```bash
flux suspend hr -n bigbang bigbang
flux uninstall hr gatekeeper -n gatekeeper-system
flux resume hr -n bigbang bigbang
```

If that continues to be unsuccessful take a look at some of the events inside namespaces (monitoring/istio-system/etc.

```bash
kubectl get events -n bigbang
# looking for helm release errors which often help pin down a breaking change item.
```

....this may or may not help.

[This script upgrades flux](https://repo1.dso.mil/platform-one/big-bang/bigbang/-/raw/master/scripts/install_flux.sh) is quite handy.

**Comment by RothAndrew** [comment]
@anoncam thanks, that's helpful.

Do you know what the resolution of this is so that the error won't happen in the first place? Is it to upgrade flux past where even Big Bang has it in the `base/flux` folder?

**Comment by RothAndrew** [comment]
My need is to be able to get the full deployment up and running with no human intervention. I'm able to do a lot in a Zarf package but adding kubectl commands as `after:` scripts is definitely not ideal

**Comment by anoncam** [comment]
I think an init container prior to reconciliation to remove all the CRDs from previous HRs would be an interesting way to clean the environment prior to reattempting.  For Big Bang Monitoring, for instance: `honorLabels: true` required a torching of all the monitoring CRDs and then re-reconciling BB with flux.

**Comment by RothAndrew** [comment]
Gathering more data now:

* Trying latest version of Kind (k8s v1.24.0)
* Will try a version of Kind that gets as close as possible to the version of K3s we're using (v1.23.6)
* Will try latest version of upstream k3s
* Will try latest version of upstream flux against current k3s

**Comment by jeff-mccoy** [comment]
@YrrepNoj didnt you deploy the latest zarf + bb core on eks today? What versions were those?

**Comment by RothAndrew** [comment]
Latest version of Kind that uses k8s v1.24.0 worked successfully. This issue did not occur

![image](https://user-images.githubusercontent.com/16000938/174357772-c12a2639-5192-469f-a0d4-f0cc385a4a76.png)

**Comment by YrrepNoj** [comment]
Zarf: `v0.19.4` 
k8s: `1.22`
BB: `1.33.0`

**Comment by RothAndrew** [comment]
`kind create cluster --image "kindest/v1.23.6` worked successfully. The issue did not occur.

![image](https://user-images.githubusercontent.com/16000938/174376738-63e358c0-ee20-45c0-9a84-560b65c46d8e.png)

**Comment by RothAndrew** [comment]
K3s v1.24.1+k3s1 using [this zarf package](https://github.com/defenseunicorns/zarf-package-software-factory/tree/e14fc6873a7a21bf80045f6c8829581b33bc2848/k3s) worked successfully. The issue did not occur.

![image](https://user-images.githubusercontent.com/16000938/174387814-6e4acbc7-c7eb-45c5-844e-c58b40014ef6.png)

Sounds like this is the winner? Just upgrade the version of K3s to latest? I'll test a couple more times to make sure it wasn't a fluke.

**Comment by RothAndrew** [comment]
Reconfirmed the issue still happens on the builtin k3s

![image](https://user-images.githubusercontent.com/16000938/174388847-915e9bd5-d881-421e-959f-7330a3717ed2.png)

**Comment by RothAndrew** [comment]
Reconfirmed the issue doesn't happen on the latest version of k3s

![image](https://user-images.githubusercontent.com/16000938/174390504-a225247c-036b-497b-b00e-b23d6c03cc4a.png)
