### ISSUE TITLE
"Unable to perform checkout" when creating zarf package for custom helm chart

### ISSUE THREAD

**Issue by acdop100** [defenseunicorns/zarf#551]
### Environment
Device and OS: 2019 MacBook Pro i9 16gb RAM
App version: 0.19.5
Kubernetes distro being used: minikube
Other: 

### Steps to reproduce
1.  `zarf package create`

### Expected result
A created Zarf package.

### Actual Result
```
zarf package create -l trace
...
DEBUG   Compressing objects: 100% (50/50), done.                                                                                                                                                              
└ (/home/runner/work/zarf/zarf/src/internal/message/spinner.go:29)
DEBUG   Total 1544 (delta 56), reused 80 (delta 45), pack-reused 1446                                                                                                                                         
└ (/home/runner/work/zarf/zarf/src/internal/message/spinner.go:29)
DEBUG   Git checkout /var/folders/q7/8gxmyqr11wdd0v1j0jktx8lmwx1zpl/T/zarf-3432438332                                                                                                                         
└ (/home/runner/work/zarf/zarf/src/internal/git/checkout.go:76)

DEBUG   reference not found                                                                                                                                                                                   
└ (/home/runner/work/zarf/zarf/src/internal/git/checkout.go:93)
   ERROR:  Unable to perform checkout                                                                                                                                                                         
└ (/home/runner/work/zarf/zarf/src/internal/git/checkout.go:93)
```

### Visual Proof (screenshots, videos, text, etc)
<img width="616" alt="Screen Shot 2022-06-21 at 12 46 00 PM" src="https://user-images.githubusercontent.com/11857861/174854023-f8be8fac-795d-4401-abcd-b554f09fffaa.png">

### Additional Context
This is for a custom chart for my project that is hosted on a private GitLab repo. It is just one component with the helm chart, with the url pointed to the repo. `gitPath` is set to the chart path. I can run all of the Zarf examples perfectly fine, so I'm not certain why this is not working for me. Additionally, I can physically go to the location Zarf is trying to go to and manually run `git checkout` fine as well. I also can add the repo as a standalone "repo" component and that gets packaged fine too.

**Comment by jeff-mccoy** [comment]
Thanks you for updating this, sorry we're at 2022 OSS NA right now and slow to reply. I think Zarf should still provide a cleaner validation for users when this happens, what do you think @YrrepNoj @RothAndrew?
