### ISSUE TITLE
Tiny-kafka example broken

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#56]
Tiny-kafka example throws error on `zarf package create`

```
FATA[0001] Bad HTTP status: 404 Not Found                destination=/var/folders/_d/70qj4sy15hv6tmp2vfpx1khh0000gn/T/zarf-316026052/files/0 url="https://ftp.wayne.edu/apache/kafka/2.8.0/kafka_2.13-2.8.0.tgz
```

It looks like it is an issue with the upstream at ftp.wayne.edu. Worth evaluating pointing at a different mirror if this one turns out to be flaky?

**Comment by RothAndrew** [comment]
sure, as long as they are run in parallel that should be good

**Comment by jeff-mccoy** [comment]
oh I see, this is no longer tracked in a mirror, but only in the archive now

<img width="613" alt="Screen Shot 2021-09-23 at 3 20 19 PM" src="https://user-images.githubusercontent.com/882485/134578158-c9588455-d457-4d2f-b03f-d4ee74716ad0.png">
