### ISSUE TITLE
Registry username output after init is incorrect 

### ISSUE THREAD

**Issue by rodneyxr** [defenseunicorns/zarf#577]
### Environment
Device and OS: Windows 11 / WSL (Ubuntu)
App version: v0.19.6
Kubernetes distro being used: rancher-desktop

### Steps to reproduce
1. `zarf init --confirm --components git-server`
2. Watch for credential output upon command completion

### Expected result
The output should show `zarf-push` as the username instead of `zarf-push-user`.

### Actual Result
Failure to authenticate to the registry with the incorrectly displayed `zarf-push-user`.
```
$ podman login --tls-verify=false registry.zarf.local --tls-verify=false -u zarf-push-user -p 70d0bd3d59b599e946032dc8bb06d0cbb66d8180ae8e2585
Error: error logging into "registry.zarf.local": invalid username/password
```

Success using `zarf-push` as the username which I had to dig through the source-code to find.
```
$ podman login --tls-verify=false registry.zarf.local --tls-verify=false -u zarf-push -p 70d0bd3d59b599e946032dc8bb06d0cbb66d8180ae8e2585
Login Succeeded!
```

### Visual Proof (screenshots, videos, text, etc)
Output after `zarf init`. Note: `zarf-push-user` is the incorrect username.
```
Application     | Username           | Password                                         | Connect
Registry        | zarf-push-user     | 70d0bd3d59b599e946032dc8bb06d0cbb66d8180ae8e2585 | zarf connect registry
Git             | zarf-git-user      | aec279731b6ce1c58fc8470a                         | zarf connect git
Git (read-only) | zarf-git-read-user | 1c2234fbce2130d4c2cdaf35                         | zarf connect git
```

### Severity/Priority
Fairly low since it doesn't break anything.

### Additional Context
```go
# config.go
ZarfRegistryPushUser    = "zarf-push"
```

When outputting credentials the code should reference `config.ZarfRegistryPushUser` instead of the hard-coded `zarf-push-user`.
```go
# deploy.go
{"     Registry", "zarf-push-user", config.GetSecret(config.StateRegistryPush), "zarf connect registry"},
```

**Comment by jeff-mccoy** [comment]
Great catch and excellent issue writeup, thanks for identifying/submitting a PR for this.
