### ISSUE TITLE
Cleanup docs and fix potential gotchas

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#602]
**Is your feature request related to a problem? Please describe.**
Some of the docs are missing information or have potential gotchas

**Describe the solution you'd like**
Fix these small issues in the markdown

**Describe alternatives you've considered**
None

**Additional context**
These were collected from running through the walkthroughs and docs

**Comment by Madeline-UX** [comment]
@Racer159 Can you provide examples of the missing info or Gotchas that you see?

**Comment by Racer159** [comment]
Yep was planning to start a corresponding PR but got distracted.  Will push what I have now.

**Comment by Racer159** [comment]
Added a draft PR (https://github.com/defenseunicorns/zarf/pull/605) that I haven't cleaned up yet.  The only workflow issue was the need to have the `zarf-registry` built before making the init package.  The rest is just adding links that might be useful or fixing links that 404 in the repo.
