### ISSUE TITLE
Generate docs from zarf.schema.json

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#606]
**Is your feature request related to a problem? Please describe.**
It is difficult to keep docs up to date with code changes at times and generating them in some fashion from the code itself is usually a cleaner way to handle updating them.

**Describe the solution you'd like**
We can use https://github.com/adobe/jsonschema2md to generate documentation for the Zarf package schema directly from the zarf.schema.json file.

**Describe alternatives you've considered**
There are other similar plugins like https://github.com/saibotsivad/json-schema-to-markdown but the adobe one seems to work and is the most well maintained of the options I had found.

**Additional context**
Zarf is cool!

**Comment by jeff-mccoy** [comment]
With some tweaking, https://github.com/coveooss/json-schema-for-humans might also be something worth looking at.  Here's an example output without any schema changes: https://codepen.io/minimind/full/LYdZyVM 

<img width="1706" alt="Screen Shot 2022-07-10 at 5 46 01 PM" src="https://user-images.githubusercontent.com/882485/178164918-c0387ec7-dd10-46c3-a4c6-61a78ed37b92.png">

<img width="1404" alt="Screen Shot 2022-07-10 at 5 46 22 PM" src="https://user-images.githubusercontent.com/882485/178164924-3b0234eb-8e9f-41d0-b0e5-0ff1646d53eb.png">

**Comment by Racer159** [comment]
Yeah that could work too.  I like with the .md files that we could have the docs use the same docusaurus tooling that the rest of the docs use. And I think some of the schema updates may not be bad (since it helps flesh out the information contained in it).
