### ISSUE TITLE
Unable to deploy big-bang-core demo

### ISSUE THREAD

**Issue by brandtkeller** [defenseunicorns/zarf#616]
### Environment
Device and OS: ubuntu ec2 
App version: zarf `v0.19.6` 
Kubernetes distro being used: k3d 1.21.7+k3s1
Other:

### Steps to reproduce
1.pulled v0.19.6 over to a ubuntu machine running k3d
2. Cloned the zarf repository
4. Ran a `zarf create package` under zarf/packages/big-bang-core
3. Ran `zarf init` and then `zarf package deploy zarf-package-big-bang-core-demo-amd64.tar.zst`

### Expected result
big bang core demo is deployed
### Actual Result
bigbang gitrepo is stuck due to failing during the mutating webhook call
### Visual Proof (screenshots, videos, text, etc)
zarf-agent logs
```
  DEBUG   http.Serve()(writer, /mutate/flux-gitrepository?timeout=10s)
└ (/home/runner/work/zarf/zarf/src/internal/agent/http/handlers.go:33)

  DEBUG   operations.Execute(*admission.AdmissionRequest) - source.toolkit.fluxcd.io/v1beta2, Kind=GitRepository , bigbang/bigbang: UPDATE
└ (/home/runner/work/zarf/zarf/src/internal/agent/operations/hook.go:30)

  DEBUG   operation UPDATE is not registered
└ (/home/runner/work/zarf/zarf/src/internal/agent/http/handlers.go:65)
 WARNING  Unable to bind the webhook handler
 ```

**Comment by brandtkeller** [comment]
The above works with `v0.19.5` of the zarf CLI and the associated zarf init package from the `v0.19.5` release.

**Comment by RothAndrew** [comment]
19.6 has a bug in the mutating we hook as you found. Stick with 19.5 for now.

@jeff-mccoy what was the reason for not reverting? I forget.

Anyway, the fix is being worked and should be released soon.

**Comment by jsburckhardt** [comment]
Cool, I'll give it shot.

**Comment by tworcester** [comment]
Dup of https://github.com/defenseunicorns/zarf/issues/610

**Comment by jeff-mccoy** [comment]
Closing as duplicate, I'll drop some more comments in #610, thanks!
