### ISSUE TITLE
data injection logic is flakey

### ISSUE THREAD

**Issue by YrrepNoj** [defenseunicorns/zarf#643]
As can be seen with a lot of our [recent workflow failures](https://github.com/defenseunicorns/zarf/actions?query=is%3Afailure+workflow%3Atest-k3s+workflow%3Atest-k3d+workflow%3Atest-kind) we are starting to consistently see failures due to the data-injection e2e test failing. 

This is most likely happening because the internal logic to handle injecting data into the pods is using a `kubectl` command through an `os/exec` call to the system. Since we are directly running the kubectl CLI we are passing off the execution to the host machine which can have inconsistent results due to the host runner having limited resources and trying to do its own thing to optimize process execution.

> deploy.go at line ~362
<img width="836" alt="Screen Shot 2022-07-25 at 10 45 29 AM" src="https://user-images.githubusercontent.com/18587823/180805079-35204dc6-fba5-4b38-a7b6-987568f29cc2.png">

Instead of executing the kubectl CLI we should switch over to handle the cp directly through the k8s api.

**Comment by jeff-mccoy** [comment]
Going to take a peak at this for a little bit, not rewrite yet, but just stability

**Comment by Racer159** [comment]
> Going to take a peak at this for a little bit, not rewrite yet, but just stability

🏔️
