### ISSUE TITLE
Update Zarf Repo - Social Preview Image

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#648]
##Current##

The current preview image is out of date with current Zarf marketing and branding.

##Updates##

Replace the preview image with this new one. 

![Zarf-DevSecOps-for-AirGap](https://user-images.githubusercontent.com/92826525/181809697-55b73201-be3b-41a8-b602-438b945ad1c6.png)

**Comment by YrrepNoj** [comment]
This has been updated :)
