### ISSUE TITLE
Example READMEs are out of date

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#676]
### Environment
Device and OS: System76 darp8, popOS
App version: v0.21.2
Kubernetes distro being used: N/A
Other: N/A

### Steps to reproduce
1. Navigate to the `examples/` sub directory in the repo

### Expected result
The examples list is complete and reflects valid information.

### Actual Result
The examples list is incomplete and reflects invalid information (i.e. the BB demo is not on v1.33).

**Comment by YrrepNoj** [comment]
Have you tried viewing them on a Mac or different linux OS?

**Comment by Racer159** [comment]
I'll take a screenshot from Haiku OS later tonight.

**Comment by jeff-mccoy** [comment]
Lol--yes we should kill these with fire and fold the ashes into the regular docs site.
