### ISSUE TITLE
Docs Zarf Init Page - Updates

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#715]
https://docs.zarf.dev/docs/user-guide/zarf-packages/the-zarf-init-package#mandatory-components
 
 - The current doc page does not include the Zarf Agent
 - K3s is marked as optional but a cluster is required, Need to figure out language around that

**Comment by Racer159** [comment]
Completed in https://github.com/defenseunicorns/zarf/pull/1574
