### ISSUE TITLE
Make Zarf More Resilient to Infrastructure and Kubernetes Related Issues

### ISSUE THREAD

**Issue by JasonvanBrackel** [defenseunicorns/zarf#752]
Recently a BigBang backed software factory had a failure due to Zarf's internal registry's Pod being evicted.  We need to make Zarf's internal infrastructure more resilient to Kubernetes issues. 

This is not in-lieu of https://github.com/defenseunicorns/zarf/issues/375 and https://github.com/defenseunicorns/zarf/issues/376 and other HA efforts, but smaller changes that can be made while those problems are solved

We should consider adding annotations like PodDisruptionBudgets or PriorityClass(es) to the various internal Zarf controllers so they are the last to be evicted by the Scheduler.

Make sure to check @RothAndrew notes on #768, that incident is the impetus for this issue.

**Comment by jeff-mccoy** [comment]
Fixed by #1039
