### ISSUE TITLE
Zarf Repair

### ISSUE THREAD

**Issue by JasonvanBrackel** [defenseunicorns/zarf#753]
We need self-healing for various Zarf components as well as troubleshooting guides for when known bad-states happen

Related to https://github.com/defenseunicorns/zarf/issues/752

Zarf agent and registry should be able to be quickly recovered in failure states either via controller / operator based algorithm or by administrative intervention in a simple and idempotent fashion.

This should include any tools and troubleshooting documentation to perform repairs when the system is in known failure states.

**Comment by jeff-mccoy** [comment]
Closing this issue now as #1039 and #751 primarily met these objectives and any documentation needs will be picked up under the current documentation reviews.
