### ISSUE TITLE
Require all Commits to be Signed

### ISSUE THREAD

**Issue by JasonvanBrackel** [defenseunicorns/zarf#772]
In order to support policies based on attestation and SBOM 
As a Zarf user
I want all code commits to be signed by the committing developer. 

We've had issues with unsigned commits. This causes rework. Let's figure out a way to fix this pre-commit.

**Comment by gscallon** [comment]
in GH's project settings, we can create a branch protection rule that applies as a wildcard for all branches and select "Require signed commits - Commits pushed to matching branches must have verified signatures." Is this along the lines of what you were thinking @JasonvanBrackel ?

**Comment by jeff-mccoy** [comment]
Yeah I thought that too--but we did that and thought it might fix internal users, the real pain is for 3rd party PRs and that won't apply to those. 😢

**Comment by Racer159** [comment]
Closing as not-fixable at this time
