### ISSUE TITLE
Zarf init package update strategy

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#774]
**Is your feature request related to a problem? Please describe.**
There will be the ability to init Zarf twice once https://github.com/defenseunicorns/zarf/pull/751 is merged, (and you can individually remove init components and redeploy them), but we should have a broader strategy for updating the init components.

**Describe the solution you'd like**
Ideally Zarf would detect the older version on init and then handle the upgrade on re-init with a new zarf init package.

**Describe alternatives you've considered**
We could add another update command as well, but re-init may be cleaner.

**Additional context**
While the init package is simple, and the registry and git servers will become optional, there is a need to still provide updates for core Zarf capabilities (namely the agent and state) in a clean way.

**Comment by jeff-mccoy** [comment]
That's how it should work. If you init a new version of the agent for example, it will update it like anything else. The only real issue is breaking changes to zarf state.

**Comment by Racer159** [comment]
Yeah we would need a way to handle that (and test for it ideally)

**Comment by jeff-mccoy** [comment]
Oooooh I like the idea of testing upgrade against prior release. Big Bang does a good job of this iirc.

**Comment by Racer159** [comment]
Also we should probably link to the changelogs for init package components and show any version updates we are doing behind the scenes...

**Comment by Racer159** [comment]
Tagging #679 and #19 as related

**Comment by Racer159** [comment]
Closing this because we have an upgrade test in CI now, and we have renovate PRs that will tell us to upgrade things like Gitea and PLG.
