### ISSUE TITLE
Registry Login Authentication Feedback

### ISSUE THREAD

**Issue by meganwolf0** [defenseunicorns/zarf#792]
**Is your feature request related to a problem? Please describe.**
Using the command `zarf tools registry login -u foo -p foo <registry>` returns the same result regardless of the successfulness of the login to the registry. This could lead to a user not knowing if they are logged in successfully until image pull is actuated during `zarf package create` command.

**Describe the solution you'd like**
Actual authentication status returned; i.e., if login was successful or not to <registry>

**Comment by jeff-mccoy** [comment]
Thanks @meganwolf0, we may need to check upstream in crane for that one as that's vendored code.  Do you have to know if https://github.com/google/go-containerregistry/blob/main/cmd/crane/doc/crane_auth_login.md behaves the same way?

**Comment by meganwolf0** [comment]
@jeff-mccoy just checked crane's response, yep it is the same regardless of the input. So I guess this could probably be shifted to that project if that's the auth library used. Or Zarf could switch to something else I suppose, I'm not sure this issue warrants that level of attention though.

**Comment by jeff-mccoy** [comment]
That is what we use, but it's a valid concern, worth keeping this issue open and seeing what we can do about it in zarf or upstream. Thanks!
