### ISSUE TITLE
Create Big Bang Core Standard Mode example

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#8]
Add an update config to the examples folder to demonstrate deploying Big Bang in standard mode to a utility cluster.

---

Migrated from https://repo1.dso.mil/platform-one/big-bang/apps/product-tools/zarf/-/issues/15

**Comment by jeff-mccoy** [comment]
@RothAndrew if it's helpful, here's the docs for the Big Bang "utility cluster" type-thing using [synker](https://repo1.dso.mil/platform-one/delivery/hagrid/sync).  I'll be updating these instructions in Big Bang as we flesh this example out.  

https://repo1.dso.mil/platform-one/big-bang/bigbang/-/raw/master/docs/airgap/README.md

**Comment by RothAndrew** [comment]
@jeff-mccoy thanks! I'll take a look.
