### ISSUE TITLE
Add SBOM Section to Configure page in deployment wizard

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#800]
**Acceptance Criteria**

- [x] Add SBOM Section to Configure page
- [x] Add SBOM section to Review page
- [x] Hyperlink .HTML link if possible

**As** Ashton, **I want** to be able to view the SBOMs for a deployment **so that** I can work with my Information Assurance peers and ensure that only approved software is being deployed.

**Given** I am on the deployment page for a package
**Then** I should see a button to View the SBOM for that package 
**And** the number of images and components that have SBOMs
**When** I click the View SBOM button
**Then** the existing SBOM viewer should open in a new browser tab

**Design File**

https://www.figma.com/file/MUItIzpzLBLuIyt225Bwgl/Zarf-UI?node-id=572%3A52442&t=YKB0Ww4ZedJdLPcj-1

<img width="1060" alt="SBOM section design" src="https://user-images.githubusercontent.com/92826525/235529610-214a2a5d-2eb4-42b6-b0fb-eee6304a0d7f.png">

**Comment by Racer159** [comment]
@Madeline-UX update the dang design!

**Comment by Madeline-UX** [comment]
> @Madeline-UX update the dang design!

Done
