### ISSUE TITLE
Utility cluster image loads always try to use `zarf.localhost`

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#83]
Still investigating, but want to get written down what I already have.

Helped a Zarf user just now that had his hostname set to `localhost.localdomain` and created a package with remote images to be loaded into the utility cluster's image registry, and Zarf was trying to hit the registry at `zarf.localhost` which didn't work. Here's the rough series of events:

1. He started out with specifying the host as an IP address in `zarf init`, and was hitting this issue of Zarf being unable to reach the utility cluster's registry
2. We destroyed the cluster and tried again with `zarf init --host=localhost`, still didn't work
3. We changed his `/etc/hosts` by adding `zarf.localhost` to his `127.0.0.1` line - worked great

Still investigating a minimally reproducible example using vagrant. Stay tuned.

**Comment by RothAndrew** [comment]
Do you want me to keep investigating a reproducible  example, or do you already feel like you have a handle on what is going on here?

**Comment by jeff-mccoy** [comment]
I have some family stuff going on, so more data would be useful.  I know that *.localhost can be inconsistent across distros and envs and that “localhost” is inconsistent for crane vs docker.  I was trying “127.0.0.1” but just ran into an interesting issue when using injected certs (like pipeline.zarf.dev), it messes with the localhost mirroring too so the init package mirrors need to be updated or we need to investigate some other tls magic.

**Comment by jeff-mccoy** [comment]
Can you confirm if this is still an issue since #82 was merged?
