### ISSUE TITLE
Issue installing Zarf Init - permission denied 

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#839]
### Environment
Device and OS: Debian 11
App version: 0.21.3
Kubernetes distro being used: Kind
Other:

### Steps to reproduce
When installing Zarf to /usr/local/bin on a linux box (Debian 11), and running as a user. It will try to write the zarf init pkg to /usr/local/bin/ and fail. with a permission denied.

### Expected result

Zarf place init pkg into the directory (I think)

### Actual Result

Fails with permission denied

### Severity/Priority

Low - CLI user was able to troubleshoot and fix without referencing docs

### Additional Context

Collected from user engagement

**Comment by jeff-mccoy** [comment]
That should be when also installing K3s, which the description for the component starts with `*** REQUIRES ROOT ***` before you confirm deployment.

**Comment by Madeline-UX** [comment]
In this situation the user did not install K3s

**Comment by Racer159** [comment]
`/usr/local/bin` is owned by `root` on most systems so yes it will fail here.

```
Note: This will require an internet connection.
? Do you want to download this init package? Yes
  DEBUG   open /usr/local/bin/zarf-init-amd64.tar.zst: permission denied
└ (/home/wayne/workspace/zarf/src/internal/utils/network.go:61)
     ERROR:  Unable to create the destination file
└ (/home/wayne/workspace/zarf/src/cmd/initialize.go:110)
```

**Comment by jeff-mccoy** [comment]
Yeah or their current working directory might make sense here.

**Comment by Madeline-UX** [comment]
@jeff-mccoy @Racer159 I can ask the user what behavior they would expect - will report back

**Comment by blancharda** [comment]
> 



> Yeah or their current working directory might make sense here.
Either would resolve the issue, but a home directory folder might be nice for users managing multiple packages (i.e. many working dirs). 

It also might come in handy for future use (like a cobra config or something).

**Comment by blancharda** [comment]
FWIW -- I ran into this on a fresh install of Ubuntu 22.04.

**Comment by jeff-mccoy** [comment]
We could also move the `--zarf-cache` flag to a global flag and then just drop the files in there?

![Screen Shot 2022-10-07 at 6 15 28 PM](https://user-images.githubusercontent.com/882485/194674304-6abbf5db-801f-4149-bd2a-5db0f3b791a4.png)

**Comment by Madeline-UX** [comment]
@jeff-mccoy We could try a poll on our K8 channel to see what users would expect the behavior to be?

Can you provide me a clear wording for the three options above?
