### ISSUE TITLE
Local dev environment

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#84]
As a developer of Zarf I want the ability to build and develop Zarf without having to install the dependencies on my workstation, so that I can manage versions and other dependencies separately from my other projects.

We already use Vagrant for doing demos/examples, let's also set up a Vagrant-based developer environment for developing and building Zarf

This also makes it a lot easier for new developers to get up and running with developing Zarf, by just having them spin up a Vagrant box rather than telling them to go install all these different tools and hope they have the right versions of things.

Co-authored with @btlghrants

**Comment by RothAndrew** [comment]
TODO: Re-evaluate the outcome of this issue after #237 merges. I believe it will significantly change this need since we'll be able to do local dev without vagrant

**Comment by jeff-mccoy** [comment]
I think we can close this too.  We are moving away from Vagrant for most things to pick-your-own-local-cluster.  As far as dependencies any developer is welcome to use any tool they want to manage the installation of go (the only real dev dependency) or to just run it in a container.  I don't want to make that a default thing we specify though as it's highly subjective.
