### ISSUE TITLE
"Getting Started" documentation does not work as written & unclear error

### ISSUE THREAD

**Issue by cskeen** [defenseunicorns/zarf#842]
### Environment
Device and OS: M1 / MacOS
App version: v0.21.3
Kubernetes distro being used: kind version 1.23
Other:

### Steps to reproduce
1. Start with a fresh setup.
2. [Go to this page in the documentation](https://docs.zarf.dev/docs/walkthroughs/creating-a-zarf-package)
3. Make sure all the prerequisites are met.
4. Follow the commands as written in the documentation.

### Expected result

When running `zarf package create .` as written in the getting started documentation, zarf will either use `defenseunicorns/zarf-agent:$GITHUB_REF_NAME` as the default agent image, or will include a sensible default value in the prompt. At the very least the getting started documentation should inform the user what to use as an AGENT_IMAGE string.

### Actual Result

1. When running `zarf package create .`, zarf will first request an AGENT_IMAGE from the user without providing any hint what that should be.

2. If a user leaves the AGENT_IMAGE blank, zarf will continue with a blank AGENT_IMAGE and return a cryptic "ERROR: Unable to pull the image " immediately after trying to process the helm chart for gitea even though the image failing to get pulled is the agent image, not the gitea image.

### Visual Proof (screenshots, videos, text, etc)

[AGENT_IMAGE prompt](https://imgur.com/bJcisWK)

[Unclear Error](https://imgur.com/QPL1PYS)

### Severity/Priority

Low, documentation issue

### Additional Context

**Comment by Racer159** [comment]
Added a small change to the error message to make it more clear that it is an empty string and created a PR for this to clear up the language (can be viewed in GitHub here: https://github.com/defenseunicorns/zarf/blob/f93592fa894b854616f92f67cf5fb1d87e346fa2/docs/13-walkthroughs/0-using-zarf-package-create.md)
