### ISSUE TITLE
Splitting zarf packages into multiple files

### ISSUE THREAD

**Issue by corang** [defenseunicorns/zarf#843]
**Is your feature request related to a problem? Please describe.**
Given that the military operates almost exclusively off of CDs and DVDs for data transfer between machines (especially to an air gapped machine) it would be a valuable feature of zarf to be able to split packages into multiple files to be able to fit on aforementioned storage mediums.

**Describe the solution you'd like**
Either/both a flag to `zarf package create` to specify splitting size or/and a separate utility command `zarf tools split` & `zarf tools combine` to manage splitting and combining packages.

**Additional context**
There is already a pattern for this relating to injector configmap creation

**Comment by RothAndrew** [comment]
+1 this would be great. As a follow on it might be nice to be able to run the deploy without having to do the combine first, if zarf is able to internally figure out that it is a split package and runs the combine internally

**Comment by jeff-mccoy** [comment]
So....something like

![Screen Shot 2022-10-05 at 5 20 51 PM](https://user-images.githubusercontent.com/882485/194174648-ceb27fac-c8e5-488d-a4d8-e937d9fd3525.png)

![Screen Shot 2022-10-05 at 5 20 20 PM](https://user-images.githubusercontent.com/882485/194174674-f16259b2-4c92-44f5-914f-00eb8fecf618.png)

**Comment by jeff-mccoy** [comment]
Or maybe
![Screen Shot 2022-10-05 at 5 24 27 PM](https://user-images.githubusercontent.com/882485/194174986-e530c8bf-a1fd-4d3f-811c-ea71882f58bd.png)

**Comment by corang** [comment]
@jeff-mccoy Exactly like that. I'm wondering if a flag is actually the wrong way to go for this though, I'd almost like to see a new field in zarf.yaml metadata more, something like `maxSize: 500MB` or `storageMedium: DVD`

**Comment by jeff-mccoy** [comment]
Either or, just like architecture.  

![Screen Shot 2022-10-05 at 5 44 00 PM](https://user-images.githubusercontent.com/882485/194177249-09e07b25-6cb1-49fb-9593-d12c8d231d1d.png)

**Comment by jeff-mccoy** [comment]
^ the flag wasn't set in the screenshot above, though you can now do a flag or viper config/env variable.  Thinking more about this:

- there may be times that the package author will for sure know that this package is giant and should probably be chunked
- but also whoever is running `zarf package create` (which may or may not be the package author) may have a specific env that needs a different chunk size--think to one env it's a data diode (no chunk size), another DVD and another CD
- lastly, now that we have viper, a person running `zarf package create` could actually set a global env variable or config file to always chunk any package to a certain size--or be even fancier and combine w/ [autoenv](https://github.com/hyperupcall/autoenv) to set chunk size per set of folders/packages if they are building a lot of zarf packages.

**Comment by Racer159** [comment]
I would argue for a command flag over a metadata change.  (this is just my experience) but a lot of the time the package author won't know how the package deployer (or really the middle diode persona) is going to want the package chunked beforehand (and it can change over time).  I have seen it where IA has run out of blu-ray discs and so now we have to chunk for DVDs, or maybe our write blocker hard drive isn't available for some reason (usually random policy changes) so now we need to chunk to disc.

**Comment by jeff-mccoy** [comment]
Agree command flag will likely be most common use. But we also have the compression and architecture fields in metadata today so I was grunt to stay consistent. I guess we could make compression a command flag instead too and not do metadata for those.

**Comment by Racer159** [comment]
We could do both, but the "uncompressed" metadata attribute does seem more useful as a command flag too.  What was the original issue for that? (assuming virus scanners not knowing what a zst file is?)

**Comment by jeff-mccoy** [comment]
When the data sets were too large for data injection and already compressed internally it was causing resource issues extracting on low-powered systems.

**Comment by Racer159** [comment]
Yeah that seems like something more worthy of a command flag IMO.  You could run into that if you took a Zarf package and tried deploying it on something low end (although I suppose on gigantic packages that could make sense to have in the definition too).

![porque-no-los-dos](https://user-images.githubusercontent.com/3977569/196256471-3aa4a792-f643-47bc-93cb-41b06c8f4d38.gif)

**Comment by jeff-mccoy** [comment]
There could also be a flag/viper config on package create side to "auto split if larger than max file size"

**Comment by jeff-mccoy** [comment]
We could even set some default (4 gigs for example) so that anything above that threshold splits.

**Comment by jeff-mccoy** [comment]
As I've thought about this more, I really like the idea of setting a "max package size" as a default with the ability for a user to override vs including in the `zarf.yaml` or manual chunk size delimiter as a flag.  It still meets the intent of allowing a user to control what makes sense for their env on `zarf package create` while also not making things inconsistent with other flags such as architecture because this is more a system-wide config like the zarf cache vs package-specific config like the architecture. Also realize I'd have to throw away a chunk of code I wrote, but I'm totally fine with that.

**Comment by Racer159** [comment]
I think that makes sense as long as max package size was reasonably large.  I think 10s-100s of GiBs is fine for a package but probably around maxing out a BD-XL disc (100GB) you should split it just to avoid potential decompression issues with weak CPUs on the other side.
