### ISSUE TITLE
Possible issue with `make all` in examples/Makefile

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#87]
Zarf user reached out via email trying the Big Bang example getting an issue when using `make all` in examples/Makefile. Looks like issue with artifacts stored in the S3 bucket.

```
curl: (22) The requested URL returned error: 403 Forbidden
```

More info to come

**Comment by RothAndrew** [comment]
In the users email the S3 URL looks like `https://zarf-public.s3-us-gov-west-1.amazonaws.com/release//zarf` which means the command `git describe --tags --abbrev=0` didn't work, maybe because they pulled the repo down as a zip file instead of `git clone` or some other reason.

If we updated the release process to host the artifacts in folders according to the release version, but then also in a `.../latest/...` folder, we could simplify this make target to not be dependent on Git.

Thoughts?

**Comment by jeff-mccoy** [comment]
Closing this stale issue, can be re-opened if the community determines it's still needed.
