### ISSUE TITLE
UI not deploying optional components in init package

### ISSUE THREAD

**Issue by mike-winberry** [defenseunicorns/zarf#882]
### Steps to reproduce
1. Build and run the ui
2. Select logging optional component. 
3. click Deploy
4. watch the output from the cli
5. optional but selected components wont be installed. 

### Expected result
- Optional selected components installed. 

### Actual Result
- Only the required components installed. 
- 
### Visual Proof (screenshots, videos, text, etc)

https://user-images.githubusercontent.com/86802655/195140526-c4fd445b-6401-4c46-9f43-55993b885831.mov

### Severity/Priority
High
### Additional Context
- Posted issue first in zarf-team channel on 06 OCT 22. At the time it was a new issue and was not experienced as of the morning/early afternoon on 05 OCT 22.

**Comment by Madeline-UX** [comment]
Replicated issue on Mac (intel chip) with new Kind cluster

https://user-images.githubusercontent.com/92826525/195147130-c2a02984-ce59-4c9b-b8b6-c82e09158872.mov
