### ISSUE TITLE
Zarf exits with a zero exit code even though a package deployment failed.

### ISSUE THREAD

**Issue by brianrexrode** [defenseunicorns/zarf#889]
### Environment
Device and OS: macbook Pro Intel chip / macOS Monterey v 12.6 
App version: v0.21.3
Kubernetes distro being used: k3d
Other:

### Steps to reproduce
1. Build an application zarf package with missing deployment spec (i.e. no selector info or template.metadata)
2. Attempt to deploy package and receive a WARNING Unable to complete helm chart install/upgrade followed by "Zarf deployment complete" message

### Expected result
zarf exits with a non-zero exit code

### Actual Result
zarf exit with zero exit code

### Visual Proof (screenshots, videos, text, etc)
![Screen Shot 2022-10-12 at 8 43 51 AM](https://user-images.githubusercontent.com/90282218/195377579-31ee8d55-b347-4c79-a8fb-67deabe17125.png)

**Comment by jeff-mccoy** [comment]
Yeah been meaning to address that, thanks, added to the final PR going in before the release today.
