### ISSUE TITLE
zarf command line execution error logging and log file readability

### ISSUE THREAD

**Issue by brianrexrode** [defenseunicorns/zarf#890]
**Is your feature request related to a problem? Please describe.**
When executing _zarf package deploy_ from a command line, the erroring reporting seems inconsistent. 
Example 1:
A deployment.yaml is missing spec.selector. 
zarf output:
![Screen Shot 2022-10-12 at 8 43 51 AM](https://user-images.githubusercontent.com/90282218/195379067-791a0765-e000-4231-b1fc-5b423141664a.png)

Example 2:
A deployment.yaml is missing spec.template.metadata
zarf output: 
![Screen Shot 2022-10-12 at 8 47 23 AM](https://user-images.githubusercontent.com/90282218/195379331-9d3608c5-6ac4-4102-922a-d5bf322d4f2e.png)
 
In both scenarios, when trying to review/troubleshoot using the associated log file with linux tools like vi, nano or simply cat the log file piped to less (cat /var/folders/bh/l8qqtz8x57j5vjd8sd33sxt40000gn/T/zarf-2022-10-12-08-46-18-3119412142.log | less) the log file is difficult to read due to the color flags. 
![Screen Shot 2022-10-12 at 9 09 17 AM](https://user-images.githubusercontent.com/90282218/195380279-8dfe39c5-135e-46db-b80c-0c4e49bbed1b.png)

**Describe the solution you'd like**
For example 1, similar logging output to example 2.
The ability to use basic linux tools to easily review and examine the log file for troubleshooting.

**Describe alternatives you've considered**
Manually testing yaml files before building a zarf package (i.e. kubectl apply -f deployment.yaml) to avoid the "WARNING Unable to complete helm chart install/update" messages and application deployment failure.
Don't currently have a good alternative to viewing the logs. I can investigate other editing tools.

**Additional context**

**Comment by jeff-mccoy** [comment]
That's interesting, cat on mac zsh (iterm / vscode) both print the color data as well, can you clarify what OS/terminal/shell you're using?

**Comment by brianrexrode** [comment]
Here's what I'm working with and yeah, I like to use bash instead of zsh but don't have a great reason why 😆 
![Screen Shot 2022-10-13 at 7 43 31 AM](https://user-images.githubusercontent.com/90282218/195614304-ce50269b-0a5e-4fdc-9d1d-3362b0382144.png)
![Screen Shot 2022-10-13 at 7 43 42 AM](https://user-images.githubusercontent.com/90282218/195614348-a753b57b-cd6c-4683-b48c-4a9bb05102f6.png)
![Screen Shot 2022-10-13 at 7 44 14 AM](https://user-images.githubusercontent.com/90282218/195614559-d52568af-ac59-49ab-ac4e-80ceb1256752.png)

**Comment by Racer159** [comment]
In this case I believe the offender is `less`.  Can you try with `more` @brianrexrode? (seems like `less` actually isn't `more` as they say).

less:
![image](https://user-images.githubusercontent.com/3977569/198856670-58e7a614-3b20-4143-b9b2-8396253042d1.png)

more:
![image](https://user-images.githubusercontent.com/3977569/198856661-766b4423-8d52-45b8-b203-7d6262e38680.png)

**Comment by RothAndrew** [comment]
While there may be different tools that makes this better, I believe this is a good enough use case to push forward implementation of a '--no-color' flag (or something to that effect). Likely not super high priority, but this will definitely show up again, like in a CI pipeline where the choice of tool isn't very flexible

**Comment by jeff-mccoy** [comment]
Yeah we can probably look at that, but for FWIW, most CI systems do support ansi colors (I don't know of any that don't).  I missed the fact he was using `less`, which I've always had issues messing up color output for me and prefer more. Also my CI flow is something like this when troubleshooting:

- Grab a debug tar output from the pipeline
- Extract the files
- `cat longfileIcareabout`
- terminal search

But I'm evil and like to use GUIs too...

**Comment by Racer159** [comment]
Linux would set you right @jeff-mccoy :smiling_imp: 

![image](https://user-images.githubusercontent.com/3977569/198856903-a4aea2f7-4aad-43f1-9ad5-abfea9d081cd.png)

**Comment by jeff-mccoy** [comment]
I just like pretty things, I'm sorry I can't help it.  I started using Linux in 1996 and used to live by a terminal only, but I guess I'm just too attracted to pretty interfaces...

**Comment by Racer159** [comment]
You should give the Gnome 40 series a shot sometime. GTK4 and libadwatia are starting to bring the shiny to linux now (though admittedly there are some rough edges still, particularly for phones (yes really https://blogs.gnome.org/shell-dev/2022/09/09/gnome-shell-on-mobile-an-update/) and tablets).

**Comment by brianrexrode** [comment]
I got the same results when using `| more`. I've probably done something weird to my terminal/shell. I'll try converting my profile back to zsh and see what I can find.

Thanks for looking into it.

**Comment by Racer159** [comment]
Reopening this issue since I think it is worth some docs on why we did this, and how to easily view Zarf logs.

**Comment by Racer159** [comment]
cc @Madeline-UX / @Jessy-Morris

**Comment by Racer159** [comment]
More context: https://kubernetes.slack.com/archives/C03BP9Z3CMA/p1677661784686499

**Comment by caesarshift** [comment]
`pterm` has a `DisableColor` function which (largely) resolves this issue. However, zarf prints some log lines before it parses the config which means that the initial log lines still print in color:

Lines with color even with this change:

```
 NOTE  Using config file /Users/jonsmith/git/zarf/zarf-config.toml

 NOTE  Saving log file to
       /var/folders/jl/q_sd6kxx74dg69cf00jgr2hr0000gn/T/zarf-2023-07-07-10-48-47-3648921497.log
```
OR with `--no-log-file`

```
 NOTE  Using config file /Users/jonsmith/git/zarf/zarf-config.toml
```

I'm not sure how or if to handle these log lines.
