### ISSUE TITLE
UI Bug - Deploying Stepper numbering

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#893]
## Current ##

On the deployment page in the wizard - the stepper starts with 0 

<img width="1063" alt="Screen Shot 2022-10-12 at 11 55 12 AM" src="https://user-images.githubusercontent.com/92826525/195403101-93db8c96-9950-4e8f-997c-d384e5379b2f.png">

## Update ##

Change stepper numbering to start with 1 

<img width="779" alt="Screen Shot 2022-10-12 at 11 56 55 AM" src="https://user-images.githubusercontent.com/92826525/195403393-38bed33d-d1ad-4088-99dc-92f9763a0a7b.png">

**Comment by mike-winberry** [comment]
https://user-images.githubusercontent.com/86802655/195691090-51293d3a-8a10-498d-96c8-d544a102b865.mov
