### ISSUE TITLE
~/.zarf-cache not created on package init

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#901]
### Environment
Device and OS: System76 popOS 22.04
App version: v0.22.0
Kubernetes distro being used: k3d
Other: N/A

### Steps to reproduce
1. Run `zarf init` without having an init package or `~/.zarf-cache` directory
2. Answer yes to the download

### Expected result
Zarf downloads the init package and initializes a cluster

### Actual Result
Zarf fails with `ERROR:  Unable to create the destination file`

### Visual Proof (screenshots, videos, text, etc)
![image](https://user-images.githubusercontent.com/3977569/195668965-00f7b6a1-cfdc-463d-826d-d6a02443d658.png)

### Severity/Priority
High

**Comment by jeff-mccoy** [comment]
@Racer159 are you doing a PR to fix this or you want me to?
