### ISSUE TITLE
Deploy Rootless/Non-Privileged Gitea Container

### ISSUE THREAD

**Issue by dsmithbauer** [defenseunicorns/zarf#904]
**Is your feature request related to a problem? Please describe.**
Some security postures for Kubernetes clusters do not allow containers to run as root. These types of clusters often employ PodSecurityPolicies (PSPs) that block scheduling any pods that run as root. The Gitea containers already have rootless versions available.

**Describe the solution you'd like**
If we change the Init package to deploy the existing version of the Gitea rootless container, we will have greater compatibility for target clusters with increased security postures.

**Describe alternatives you've considered**
While it is possible to reduce restrictions or exclude certain applications from PSPs the only sacrifice made by using the Gitea rootless container is a switch to Gitea internal SSH to support the Git protocol instead of OpenSSH. See <https://docs.gitea.io/en-us/install-with-docker-rootless/>

**Additional context**
I have already implemented a solution to this in the form of a new Zarf Init package that deploys the rootless image for Gitea. It may require some testing, but it does deploy fine.

**Comment by jeff-mccoy** [comment]
Would love a PR on this one, we looked at the rootless config some months ago and there were still some issues--if you have a working init package and want to PR to update Zarf's git server init package that would be great!

**Comment by dsmithbauer** [comment]
Alright, I'll test it out with 0.22.0 and put a PR together soon.

**Comment by dsmithbauer** [comment]
Thanks @Racer159!
