### ISSUE TITLE
The CreatePod Function Does Not Consider Nodes that May Have Taints

### ISSUE THREAD

**Issue by dsmithbauer** [defenseunicorns/zarf#905]
**Is your feature request related to a problem? Please describe.**
It is common in some cluster configurations to taint the control plane nodes to not allow most workloads to be deployed there.  For example RKE2 HA documentations suggests adding the following taint that disallows most pods from being scheduled on control plane nodes (see <https://docs.rke2.io/install/ha/#2a-optional-consider-server-node-taints>):

```
node-taint:
  - "CriticalAddonsOnly=true:NoExecute"
```

When Zarf attempts to deploy the agent to a cluster like this, if a tainted control plane node is the first in the list the pod will fail to deploy and startup.  We've been able to work around this for our purposes by modifying the CreatePod function like so:
```
// CreatePod inserts the given pod into the cluster
func CreatePod(pod *corev1.Pod) (*corev1.Pod, error) {
	pod.Spec.Tolerations = []corev1.Toleration{
		{
			Key: "CriticalAddonsOnly",
			Operator: "Exists",
		},
	}
	message.Debugf("k8s.CreatePod(%#v)", pod)

	clientset, err := getClientset()
	if err != nil {
		return nil, err
	}

	createOptions := metav1.CreateOptions{}
	return clientset.CoreV1().Pods(pod.Namespace).Create(context.TODO(), pod, createOptions)
}
```

**Describe the solution you'd like**
This, however, is a specific solution to our use case. It would be better if nodes with taints that would affect the deployment of critical Zarf components could be excluded or a configurable list of taints could be passed in to filter out the ineligible nodes.

**Describe alternatives you've considered**
See workaround above.

**Additional context**
There could be many different taint values used that could prevent deployment so a configurable option/list is probably best.

**Comment by jeff-mccoy** [comment]
We actually may need to go a step further too and prevent those images from being listed otherwise you may run into a situation where the pod could never be scheduled.

**Comment by dsmithbauer** [comment]
Has there been any additional work/consideration for this? We still have to deploy an older/customized version of Zarf due to this limitation and would be delighted to not have to continue doing so. The above provided solution works, but is specific to an RKE2 cluster and the `CriticalAddonsOnly` taint. Would be great if this could be applied more generically.

**Comment by Racer159** [comment]
We could probably also look for the CriticalAddonsOnly taint in this PR by @ragingpastry https://github.com/defenseunicorns/zarf/issues/1730

**Comment by ragingpastry** [comment]
I could certainly add that! I wonder how many taints like this there are that are common though.

**Comment by dsmithbauer** [comment]
We have some nodes that are not tainted. It would be my preference to only return a list of nodes that do not have some kind of NoExecute taint so that the Zarf Injector pod doesn't fail to deploy. No need to add tolerations in my use case. @ragingpastry 's solution looks perfect!
