### ISSUE TITLE
Docs don't line up with CLI - zarf tools get-admin-password

### ISSUE THREAD

**Issue by runyontr** [defenseunicorns/zarf#935]
### Environment

https://docs.zarf.dev/docs/user-guide/the-zarf-cli/cli-commands/zarf_tools_get-admin-password#zarf-tools-get-admin-password

### Steps to reproduce

Run
`zarf tools get-admin-password`

### Expected result

docs to match CLI

### Actual Result

CLI throws an error

### Visual Proof (screenshots, videos, text, etc)

```bash
➜  ~ zarf tools get-admin-password

Saving log file to
/var/folders/7d/2j808fl56k95v_2_n_qwmp9w0000gn/T/zarf-2022-10-20-11-42-33-1362594173.log
Collection of additional tools to make airgap easier

Usage:
  zarf tools [command]

Aliases:
  tools, t

Available Commands:
  archiver         Compress/Decompress tools for Zarf packages
  clear-cache      Clears the configured git and image cache directory
  get-git-password Returns the push user's password for the Git server
  monitor          Launch K9s tool for managing K8s clusters
  registry         Collection of registry commands provided by Crane
  sbom             SBOM tools provided by Anchore Syft

Flags:
  -h, --help   help for tools

Global Flags:
  -a, --architecture string   Architecture for OCI images
  -l, --log-level string      Log level when running Zarf. Valid options are: warn, info, debug, trace (default "info")
      --no-log-file           Disable log file creation
      --no-progress           Disable fancy UI progress bars, spinners, logos, etc
      --tmpdir string         Specify the temporary directory to use for intermediate files
      --zarf-cache string     Specify the location of the Zarf cache directory (default "~/.zarf-cache")

Use "zarf tools [command] --help" for more information about a command.
```

**Comment by Noxsios** [comment]
@runyontr `zarf tools get-admin-password` was changed to `zarf tools get-git-password` when support for external registry was added.  PR https://github.com/defenseunicorns/zarf/pull/943 removes this dead docs endpoint.  This works locally for me on main, and will be included in the next release of zarf.  I believe this issue can be safely closed.

**Comment by runyontr** [comment]
I think we can close it when the PR is reflected on the docs.zarf.dev site.  Does that seem reasonable?

**Comment by Racer159** [comment]
Closing as this has been fixed on docs.zarf.dev (see https://docs.zarf.dev/docs/user-guide/the-zarf-cli/cli-commands/zarf_tools_get-creds)
