### ISSUE TITLE
Bug in UI API - Package build data not the same in CLI and UI

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#946]
### Environment
Device and OS: macOS amd64
App version: current dev build
Kubernetes distro being used: Kind
Other: an example using Init package

### Steps to reproduce
1. Open UI
2. View the cluster or click initialize the cluster
3. Look at package build data

### Expected result
Build data should match the build data displayed in CLI

<img width="564" alt="Screen Shot 2022-10-26 at 1 08 36 PM" src="https://user-images.githubusercontent.com/92826525/198106988-6c1e00ad-bcbb-45ab-a70d-c02c6cfdcfeb.png">

### Actual Result

Package build data shows local machine information for the user, terminal, and timestamp. This does not match the CLI 

### Visual Proof (screenshots, videos, text, etc)

<img width="834" alt="Screen Shot 2022-10-21 at 11 24 27 AM" src="https://user-images.githubusercontent.com/92826525/198107392-66112598-ff6c-44b4-b10f-71cfef076af3.png">

### Severity/Priority
Medium
This needs to be fixed before promoting UI MVP

**Comment by Madeline-UX** [comment]
@jeff-mccoy @Noxsios any insights on this issue?

**Comment by Racer159** [comment]
Closing as a non-issue from our discussion.  (for those who come back to this on GitHub, Zarf will choose the init package that is closest to it, and matches its CLI version)

**Comment by Madeline-UX** [comment]
@Racer159 helped explain this to me - not a bug but it did lead to a great discussion around how to better present this information to users with context
