### ISSUE TITLE
Zarf StorageClass Forecast

### ISSUE THREAD

**Issue by ntwkninja** [defenseunicorns/zarf#947]
Something to keep an eye on

https://kubernetes.io/blog/2021/12/10/storage-in-tree-to-csi-migration-status-update/

**Comment by jeff-mccoy** [comment]
More info on this, new EKS clusters on 1.23 will break without https://docs.aws.amazon.com/eks/latest/userguide/kubernetes-versions.html#kubernetes-1.23
https://aws.amazon.com/blogs/containers/amazon-eks-now-supports-kubernetes-1-23/
https://docs.aws.amazon.com/eks/latest/userguide/managing-ebs-csi.html

**Comment by ntwkninja** [comment]
@Racer159  I think this is resolved with the addition of [EKS testing w/CSI driver](https://github.com/defenseunicorns/zarf/pull/1573)

please reopen if needed
