### ISSUE TITLE
Make variable defaults nilable

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf#969]
**Is your feature request related to a problem? Please describe.**
It would be (potentially) nice to have nilable defaults so that package creators can have more control over the variables that get set on deploy time (allowing for them to intentionally fail a deployment when no value was provided (i.e. when a password or secret was needed without defaulting to an insecure empty string))

**Describe the solution you'd like**
Allow the detection of a non-specified default (as opposed to always defaulting to an empty string)

**Describe alternatives you've considered**
We could leave things as they are and just always use an empty string (and there are other projects that do this, namely GitHub Actions) but this would also mean that we should intentionally accept and communicate side effects.

We could also introduce pattern matching to get around some cases covered by this (i.e. using a `.+` pattern would ensure a string was not empty) but this would require explicit action on the package creator's part and there could be cases where an empty string is a legitimate value.

**Additional context**
This issue is a break away from #675 loading of variables from files.

**Comment by jeff-mccoy** [comment]
😭 that is all 😁

**Comment by Racer159** [comment]
@jeff-mccoy 
![willy-wonka-you-won](https://user-images.githubusercontent.com/3977569/228041318-02c5d7ec-c62a-4dcd-ab55-ed999ba008e8.gif)
