### ISSUE TITLE
We should have our own "test harness" for CI

### ISSUE THREAD

**Issue by RothAndrew** [defenseunicorns/zarf#97]
Right now the CI pipeline is using `cloudposse/test-harness:latest` which is okay for the short term but we should consider making our own

* CloudPosse's has different priorities and uses different versions of tools than we do
* We don't necessarily need to do it right away but we should likely be using images from Iron Bank for our supply chain

High-level objectives are:

* We would like a single docker image to use in CI pipelines that has all of the tools we need to build and test Zarf. This can either be something scoped to Zarf itself or something more organizationally reusable. At my last company we made an organizationally reusable one called [Anvil](https://github.com/saic-oss/anvil). It was great for being a one-stop-shop for all build/test/deploy stuff as well as being able to be used for local development. It's downside was that it is a huge image.
* It should be architected such that it has a clear path to being hosted in Iron Bank, though that doesn't have to be an immediate priority
* If it is to be organizationally reusable the user needs to be able to specify which version of a tool is being used. We did this with Anvil by using [ASDF](http://asdf-vm.com/) which lets you specify the versions of each tool in a file called `.tool-versions`. If the plan is to just have Zarf using it it isn't as big of a deal to have configurable tool versions.

**Comment by jeff-mccoy** [comment]
I'm going to close this right now as we've re-architected how run CI/CD and don't think is a concern for us right now.  Any concerns @RothAndrew?

**Comment by RothAndrew** [comment]
If we've gone from doing container-based builds to VM/runner based then yeah this isn't as important.

**Comment by jeff-mccoy** [comment]
Copy thanks, will re-open if needed in the future.
