### ISSUE TITLE
Windows CLI does not create ~/.zarf-cache directory.

### ISSUE THREAD

**Issue by JasonvanBrackel** [defenseunicorns/zarf#985]
### Environment
Device and OS: Windows 11
App version: Zarf v0.22.2
Kubernetes distro being used: N/A
Other:

### Steps to reproduce
1. Run "zarf init"

### Expected result
Zarf downloads the zarf init package C:\Users\<user>\.zarf-cache

### Actual Result
```pwsh
PS C:\Users\jason> zarf init

Saving log file to C:\Users\jason\AppData\Local\Temp\zarf-2022-11-08-10-11-55-1722182145.log

...

It seems the init package could not be found locally, but can be downloaded from
https://github.com/defenseunicorns/zarf/releases/download/v0.22.2/zarf-init-amd64-v0.22.2.tar.zst

? Do you want to download this init package? Yes
     ERROR:  Unable to create the destination file y
```

You can workaround by creating the ~/.zarf_cache directory

### Visual Proof (screenshots, videos, text, etc)
![image](https://user-images.githubusercontent.com/942110/200603706-ffb2d1e9-f2a9-4893-98e7-29d43e91707f.png)

**Comment by Noxsios** [comment]
This can be fixed w/ the below addition to https://github.com/defenseunicorns/zarf/blob/878a409930aa4893af7be529bc2acf74e32c798f/src/cmd/initialize.go#L72: 

```go
# src/cmd/initialize.go
err = os.MkdirAll(config.GetAbsCachePath(), 0755)
  if err != nil {
  message.Fatalf(err, "Unable to create cache directory: %s", config.GetAbsCachePath())
}
```

Will make a PR branch tomorrow.
