### ISSUE TITLE
Zarf Package SBOM details confusion

### ISSUE THREAD

**Issue by Madeline-UX** [defenseunicorns/zarf#989]
**Is your feature request related to a problem? Please describe.**

The user did not see the SBOM viewer URL and did not open the viewer before deploying
Post-deployment user tried to find the SBOM and discovered it was removed after the deployment. 

User quote: " I expected the ability to go back to those (SBOM) web pages. It was confusing to see them only available for the limited time the init runs. I’m not clear what the intent of their use is if they don’t persist. The docs also talked bout copying the URL, but there was no URL presented that I saw."

Context from @jeff-mccoy "right now it exists to give someone a deeper look at whether they should approve a deployment. Down the road it should be long-lived and consumed by other runtime tools."

Issues:
- Discoverability of SBOM link on deployment
- Not clear to user what the purpose of SBOM is - how they are supposed to use it
- Files are not long lived past deployment and remain in package
- Complicated hidden flow for extracting SBOM files after deployjment

**Describe the solution you'd like**
CLI
- prompt user after package description > would you like to view SBOM first? Y/n
- Use color to distinguish between information text and SBOM UI Link

Future ideas
- store SBOM files in registry via cosign
- Zarf UI used to search across multiple SBOM for all present images in registry

**Additional context**
SBOM is still a new concept. There are a lot of unknowns around how it will be used. We want to stay open and adaptable as SBOM gets adopted to what use cases will arise.

**Comment by Noxsios** [comment]
Related to #2043
